### ISSUE TITLE
Support for 3rd party Nintendo Switch Pro controller (from ebay)

### ISSUE THREAD

**Issue by RohitChapke** [ndeadly/MissionControl#1]
So, after I installed this build of MissionControl on my switch, the Nintendo Switch Pro controllers (knockoffs I bought from ebay) that I had weren't connecting to my switch. I have attached a copy of my addresses at the end. Both the pro controllers are Xenoblade chronicles edition, if that matters.

Help me support these controllers back on my switch.
![InkedSwitch bt addresses_LI](https://user-images.githubusercontent.com/50639785/91373394-48e8d680-e7e4-11ea-9b84-f42ceb76aa24.jpg)

**Comment by AuroraWright** [comment]
My original Nintendo Switch pro controller also doesn't work, looking at the code I think it's due to the device ID not matching the hardcoded one (057e:0330). I think I paired it via USB, maybe it does that when you do it that way

**Comment by ndeadly** [comment]
Yes, the issue is due to the device IDs not being whitelisted. The user has contacted me via reddit and I have solved his issue for now with a custom build. I suspect these cheap knockoffs may just set random device IDs, so the whitelisting them may not be the best solution here.

The current problem with the name-based approach is that I have to mitm the pairing process and rename the controller as `Pro Controller` in order for it to be detected by HOS accross all firmwares. This of course leads to the problem that everything (besides joycons) has the same name in the database. The device ID is the only reliable way to differentiate between different controller types. It's also nicer than having to whitelist a pile of device names instead. 
Ideally, I need to allow the real controller name to be stored and additionally mitm btm and lie to it about the controller name instead. Unfortunately I haven't had any luck in booting with a btm-mitm. Might be related to the boot2 issue.

@AuroraWright that's interesting about the Switch Pro Controller. I didn't know they could get the wrong ID too. A workaround for now would be to re-pair the controller via Bluetooth. You may have to remove all controllers in settings first in order for it to pick up the correct ID

**Comment by AuroraWright** [comment]
@ndeadly what about treating any `Pro Controller` that *is not* an xbox/wii/u/ps4/etc controller as a Switch controller? Assuming that those pids/vids are always the same (which already an assumption you make to make them compatible anyway).

**Comment by ndeadly** [comment]
@AuroraWright this is probably what I will do to increase compatibility for the next release. The problem is with the case where you can't ID a xbox/wii/u/ps4 controller because it uses an unknown ID. The mitm renames it to "Pro Controller", so there is no way to distinguish between an unrecognised non-switch controller, and a knock off Switch Pro Controller with a garbage ID.

**Comment by ndeadly** [comment]
3rd party switch controllers should now work without whitelisting in the new 0.2.0 release.
