### ISSUE TITLE
Some buttons are synced with other controllers: Dualshock 4 & Wii Remote

### ISSUE THREAD

**Issue by blackxithus** [ndeadly/MissionControl#100]
I'm using both a dualshock 4 and a wii remote w/ nunchuck simultaneously for 2 player. Everytime I press the square and triangle button on the dualshock it will do the same on the wii remote. It's like the buttons are synced together. Only the buttons of the DualShock 4 is behaving this way.

**Comment by ndeadly** [comment]
Hey, thanks for reporting. I think this is happening because I use a common "staging" buffer for the translated controller data and wasn't zeroing it out before writing new controller data. This isn't normally an issue, but in controllers that don't map to every face button of a switch controller there are button values that don't get overwritten. I'm actually suprised this didn't get reported sooner.

See if this build fixes the issue
[MissionControl-0.2.1-button-press-fix.zip](https://github.com/ndeadly/MissionControl/files/5286658/MissionControl-0.2.1-button-press-fix.zip)

**Comment by blackxithus** [comment]
Hey! This fixed the problem. Thanks!
