### ISSUE TITLE
Problems connecting bluetooth controllers

### ISSUE THREAD

**Issue by Lapan** [ndeadly/MissionControl#11]
Atmosphere 0.14.1
Hekate 5.3.2
Switch firmware 10.1.0
==============
Tried it with a few controllers, all of them official:
Switch Pro Pad doesn't pair anymore. Still wakes the console and shows "paired" when sync is held, buit doesn't actually do anything but flash the leds, like it's still searching
Wiiu Pro Pad works fine, gets recognized as switch pro pad
Dualshock 4 doesn't pair (Am I supposed to just hold the ps button?) - Pairs fine with a magicns

Tried Disconnect Controllers under the Controllers and Sensors menu, without success

**Comment by raginglazor** [comment]
For the PS4 controller you have to hold share + ps Button to put the controller in pairing mode

**Comment by ndeadly** [comment]
Can you show me the output of btdb.nro (included on the release page). I'm curious why your Switch Pro Controller isn't working. That kind of thing usually happens if the Switch can't read all of the things it wants to from it and doesn't complete the connection. It's possible the switch is making a request that I haven't seen before and don't handle. Any idea what firmware is running on the controller?

Try what @raginglazor suggested for the DS4 and it should work

**Comment by Lapan** [comment]
Share + ps worked for the DS4
Updating the switch pro controller over a wired connection didn't solve the other issue.
The btdb screenshot is attached.
![2020082719144600-C51293948B3B9EB2CF99ABA1B62D91F9](https://user-images.githubusercontent.com/5336032/91474213-37620600-e89a-11ea-9f81-6c584144f4fc.jpg)

**Comment by ndeadly** [comment]
I can see that you have a DS4 and Wii U Pro controller connected there. That last entry `ca40:f938` is not an id that I have whitelisted. Either this is not an official controller, or you need to wipe your bluetooth database and re-pair the controller via bluetooth so that it stores the correct ID. A real Switch Pro should report 057e:2009

**Comment by Lapan** [comment]
It is a real one.
Wiping the bluetooth devices again after the firmware update did the trick though. Now it shows up as 057e:2009 in btdb as well.
![2020082720124900-1E95E5926F1CB99A87326D927F27B47E](https://user-images.githubusercontent.com/5336032/91479554-e48c4c80-e8a1-11ea-8147-ddaa3ae2ad94.jpg)
