### ISSUE TITLE
Controller disconnect issue

### ISSUE THREAD

**Issue by vink2212** [ndeadly/MissionControl#136]
Hey, I'm using the gamesir G4S and the controller disconnects after a min of uses everytime. tried troubleshooting it by reinstalling mission control and clearing the controller list but the issue sitll persists. i am on the latest version of mission control

**Comment by ndeadly** [comment]
Didn't you have this controller working previously? Has something changed?

**Comment by vink2212** [comment]
@ndeadly hey yeah it **WAS** woking correctly but I didn't use it for a week or two and now it just keeps disconnecting when trying to use the controller
possible issues are that I updated AMS and deleted the controller list

**Comment by ndeadly** [comment]
Hmm that's a bit strange. I can't see how updating AMS would affect anything. Had you changed anything else when this started happening? Paired the controller with any other devices?

If you deleted the database and re-paired it's possible you paired again in some different mode that's causing the issues, but by the sound of things you deleted it _because_ you were having problems, right?

You could try installing and running this [debug build](https://github.com/ndeadly/MissionControl/files/5506980/MissionControl-0.3.0-debug-logging.zip) and posting the log it generates (sdmc:/bluetooth-mitm.log) after being able to replicate the disconnection. It's possible the console is sending a disconnect command if it receives something it doesn't like. This happens with the Xbox One controller and I have to patch some event data it sends (though it happens straight away, not after some delay). The real question here is why this has only just started happening now.

**Comment by kakra** [comment]
At least the Microsoft controllers often need to be paired to a different Bluetooth host so link authentication becomes cleared in the controller before you can reliably reconnect it again to the original host whose BT client list you cleared.

**Comment by vink2212** [comment]
@ndeadly yeah i deleted the ist rn cause it was not working correctly and I am using the correct mode as it is the same mode i was using before

**Comment by ndeadly** [comment]
@kakra interesting to know. I don't think I've bumped into that issue on the Switch. The issue I refer to above is some unknown event being generated by the Switch Bluetooth driver with possible a result code that's nonzero in the case of the Xbox One controller. This causes one of the other processes to issue the disconnect command to the controller. The controller would otherwise remain connected (I verified this by redirecting system events so the offending process never receives them). I simply mitm the event and set the value to 0 and everything is fine.

**Comment by ndeadly** [comment]
> @ndeadly yeah i deleted the ist rn cause it was not working correctly and I am using the correct mode as it is the same mode i was using before

Could be that your controller battery is running low? For many of these 3rd party controllers it's not obvious how the battery information is sent  so I haven't mapped it to anything. These controllers will always display the default full battery.

**Comment by kakra** [comment]
For Xbox compatible controllers, Bluetooth battery reports are sent in report opcode 4 with a one byte field appended. The battery info is documented in xpadneo's `docs/` folder. The code also has info how to detect the battery report opcode from the HID descriptor parser - maybe you can use that?

**Comment by ndeadly** [comment]
@kakra the problem is that I don't get the HID descriptor. I guess it's received somewhere inside the Bluetooth driver service. I don't have code execution in the driver itself so can only make use of what's exposed over IPC - not much. I don't know of a good way to instruct non-technical users to obtain the descriptor via some other means. Any suggestions?

From what I've seen, even though many of these would be considered XInput controllers, there is nothing standardised about the way they report battery information. Some send it on a separate report (though I've never seen opcode  `0x04` outside of the Xbox controller itself). Some send it along with the button states. Many I have no idea where it is if it's even sent at all.

**Comment by kakra** [comment]
> I guess it's received somewhere inside the Bluetooth driver service.

@ndeadly Not necessarily... It may be cached as a service descriptor inside the Bluetooth daemon, at least for Linux. So it's not transferred again on later reconnect, just once during pairing. But when looking at the data stored by Bluez, it doesn't look like it stores any descriptors. So they must be transferred on every connect. Do you see the data streams during connect? Otherwise I see no chance of intercepting the HID descriptor.

In Linux, you can get the binary descriptor from `/sys/bus/hid/0005:*/report_descriptor`, `0005` being the bus number (Bluetooth) and `*` being the PID:VID:Index of the device. The report descriptor may be patched by drivers, so it's not a totally reliable source of information. A decoded text version is available in `/sys/kernel/debug/hid/.../rdesc`, and the HID spec has a way of telling that a bit of information is actually the battery level - but that doesn't mean the battery level is a simple value of 0-100 or something. For Xbox controllers, it's a mixed value of feature bits and a capacity level of 1-4.

**Comment by ndeadly** [comment]
@kakra yeah, I meant that at some point, it has to be transferred between the controller and the host. Whether that happens once or every time doesn't really matter, I just need to intercept it once. I only get access to high level (application layer I guess, not familiar with Bluetooth terms) connection events and HID reports. I assume the exchange takes place in some lower layer. Not easy to get access to without considerable effort.

And here lies my problem. Unfortunately I can't expect the average user to just jump on Linux and grab the info I need. I could do this myself, but I don't have access to the controllers. Maybe it's worth trying to write a script to grab everything so that at least moderately technical folk could provide me with something...

**Comment by kakra** [comment]
Yeah, I was thinking about such a script for xpadneo. If I happen to make such a script, I'll share it with you.

**Comment by vink2212** [comment]
@ndeadly no the battery was full, there is a battery indicator light on the controller and it's full

**Comment by ndeadly** [comment]
> Yeah, I was thinking about such a script for xpadneo. If I happen to make such a script, I'll share it with you.

@kakra that would be great.

@vink2212 damn, I was hoping for the simple solution. Then I suggest you try to create a log with that debug build I posted earlier and I'll see whether anything looks amiss.

**Comment by vink2212** [comment]
@ndeadly it seems to be fine now but i think the issue will repeat, i will make a log tmr and send

**Comment by dywersant** [comment]
Having same issue with G3s.
Created logs with debug build, hoping to have this resolved.
[bluetooth-mitm.log](https://github.com/ndeadly/MissionControl/files/5946368/bluetooth-mitm.log)

What i did: rebooted the console, opened Controllers>change grip/order and connected G3s, returned to home menu with home button and the controller turned itself off after about 1 minute.

**Comment by ndeadly** [comment]
@dywersant nothing looks particularly out of place in your log. I suspect that maybe the switch is attempting to send some unsupported command to the controller and it responds by shutting off. I will have to add the extension commands to the bluetooth mitm in order to log them too. I'll post an updated build here when it's ready.

**Comment by dywersant** [comment]
Thanks.
One more observation after fiddling with it.
I am at the main Switch homescreen. I am turning on G3s, it does its led blinking for 2 seconds, then the led lits solid, meaning it connected. Switch is not reporting any controller connected, and its not reacting to controllers input. After about 1 minute G3s
will turn itself off. Repeating these steps for about 5-6 times i can finally get my controller to show up on the homescreen and everything is working fine, its not disconnecting. 
I can capture logs for this scenario if they are needed.

**Comment by ndeadly** [comment]
Interesting. I'm not sure what would cause that behaviour. Here's a new build with more logging capabilities. Log the connection again with this version. Hopefully the extra logging shows what's to blame. You're welcome to try and capture the scenario you described above too if you want

[MissionControl-0.4.1-ext-debug-logging.zip](https://github.com/ndeadly/MissionControl/files/5947734/MissionControl-0.4.1-ext-debug-logging.zip)

**Comment by dywersant** [comment]
Back with reports.
Case 1: After reboot go to Controllers>change grip, turn on controller, pair it, get back to homescreen, controller will turn itself off in 1 minute.
[bluetooth-mitm-via options.log](https://github.com/ndeadly/MissionControl/files/5950496/bluetooth-mitm-via.options.log)

Case 2: fresh reboot, console just sitting on homescreen, turn on the controller, let it pair. The console is not picking up anything, regardless the controller reporting that it is connected. Turn off controller > repeat. I needed like 7-8 tries for the console to correctly sync and connect to G3s.
[bluetooth-mitm- via homescreen.log](https://github.com/ndeadly/MissionControl/files/5950530/bluetooth-mitm-.via.homescreen.log)

**Comment by ndeadly** [comment]
Hmm, looks like it could have something to do with the console calling the SetTsi function on the controller. I'm not exactly sure what this function does but I think it sends some vendor-specific command for broadcom bluetooth chips. Here I've tried dropping the command and faking the response from the controller. See if it makes a difference to either of your scenarios above.

[MissionControl-0.4.1-fake-tsi-response.zip](https://github.com/ndeadly/MissionControl/files/5951865/MissionControl-0.4.1-fake-tsi-response.zip)

**Comment by dywersant** [comment]
That did the trick. Working perfectly now in every scenario.
I have cleared bt database, paired again just to be sure everything is ok. Pairing seems faster now, great.

iam attaching logs from newest version for reference.
Thank You :)
[bluetooth-mitm.log](https://github.com/ndeadly/MissionControl/files/5952883/bluetooth-mitm.log)

**Comment by ndeadly** [comment]
@dywersant awesome! Here's one last build for you to try where I handle everything properly instead of hacking it in. If you could check that I haven't broken anything and report back that would be great. I've also removed the logging from this one so you can continue using it with no performance degradation until the changes make the next official release.

[MissionControl-0.4.1-settsi-mitm.zip](https://github.com/ndeadly/MissionControl/files/5954437/MissionControl-0.4.1-settsi-mitm.zip)

**Comment by dywersant** [comment]
> @dywersant awesome! Here's one last build for you to try where I handle everything properly instead of hacking it in. If you could check that I haven't broken anything and report back that would be great. I've also removed the logging from this one so you can continue using it with no performance degradation until the changes make the next official release.
> 
> [MissionControl-0.4.1-settsi-mitm.zip](https://github.com/ndeadly/MissionControl/files/5954437/MissionControl-0.4.1-settsi-mitm.zip)

Sure!
I did usual testing, wiping database, rebooting couple of times. Everything is working flawlessly.
Thanks for that build, i was about to ask for "logless" version, or a commit :)
