### ISSUE TITLE
Support for Mad Catz C.T.R.L.R. gamepad

### ISSUE THREAD

**Issue by nono2lozere** [ndeadly/MissionControl#139]
Thank you for your usefull tool, I tried it with my Mad Catz C.T.R.L.R. but it doesn't work.
It apear in the controler list but there is no button maping.
The vendor id is 1848, product id is 21094 both in decimal format and the controls are like xbox 360 controller.
Here is Retroarch autoconfig file for reference:
[Mad_Catz_C.T.R.L.R.txt](https://github.com/ndeadly/MissionControl/files/5542544/Mad_Catz_C.T.R.L.R.txt)
I have also the C.T.R.L.R. smart witch is the bluetooth BLE version, the product id is 21091.
Thanks in advance.

Ps: Maybe you can use the Retroarch autoconfig files (https://github.com/libretro/retroarch-joypad-autoconfig) to add support for new controllers.

**Comment by ndeadly** [comment]
Support for this controller has already been added, the changes just haven't been released yet. See #113

Could you make a separate request for the other one so that it doesn't get forgotten? I don't have BLE support working yet so I'll have to get back to it at a later time.

> Ps: Maybe you can use the Retroarch autoconfig files (https://github.com/libretro/retroarch-joypad-autoconfig) to add support for new controllers.

Are you familiar with the file format? It's not clear to me how I would translate these .cfg files to a C/C++ structure, seems easier to just observe the HID reports and translate myself. I don't want the additional overhead of parsing a bunch of definitions at runtime. Might be handy for validating my own definitions though.

**Comment by kakra** [comment]
> It's not clear to me how I would translate these .cfg files to a C/C++ structure

There's no relationship between such config files and the HID reports. If anything, you can maybe infer the button bitmap from these config files that gets sent by the HID reports. But that doesn't help if you don't know the format of those reports: You'd need the full descriptor anyways.

But usually it goes like this: 8, 16, or 32 bits per each axis, followed by a bitmask with one bit per button which probably also comes as a 16 or 32 bit word thus button 0 is the least significant bit. But you still don't know if axes and buttons come in separate reports or in one single state report.

**Comment by ndeadly** [comment]
@kakra thanks for the explanation. As I suspected then. Without access to the descriptor to at least find the report IDs these aren't very useful in my case.

**Comment by nono2lozere** [comment]
Thank you for your quick answer and awesome support. And for the explanation about retroarch config files, I don't know that you work at such "low level".
I will open a separate request for the BLE version.
Issue closed
