### ISSUE TITLE
Support for Razer Serval. 

### ISSUE THREAD

**Issue by juice808** [ndeadly/MissionControl#140]
I would like to request support for Razer Serval. It is xinput... If you could help me please. I would pay for that.

**Comment by ndeadly** [comment]
Have you been able to pair the controller with the console? If so, there will be an entry in the Bluetooth database that you can view with `btdb.nro` from the release page. Post a screen capture of that here so I can see the hardware ID of the controller.

Next step is to use [this tool ](https://github.com/ndeadly/MissionControl/files/5539371/hid_report_viewer.zip)to view the HID reports being sent by the controller. Make sure you don't have any other Bluetooth controllers connected, and note down the numeric output as you press each button on the controller one at a time. I'll also need the output when the analog sticks are at maximum position in X and Y axis.

Once I have all of the above information I can get to work on supporting the controller.

**Comment by faustokill** [comment]
Yes. Thanks alot. 
So here it goes:

I'm thinking that the switch recognized the serval as a Android Controller, because the home and back android buttons are working. In XInput mode it doesnt work.

![Razer Serval](https://user-images.githubusercontent.com/21365956/99192936-78104380-2754-11eb-9907-4c0e8915d064.jpg)


0000 | 01 80 80 80 80 08 00 00 00 00 70 75 Default

0000 | 01 80 80 80 80 18 00 00 00 00 70 75 Xbox A

0000 | 01 80 80 80 80 28 00 00 00 00 70 75 Xbox B

0000 | 01 80 80 80 80 48 00 00 00 00 70 75 Xbox X

0000 | 01 80 80 80 80 88 00 00 00 00 70 75 Xbox Y

0000 | 01 80 80 80 80 08 02 00 00 00 6f 75 Xbox RB

0000 | 01 80 80 80 80 08 00 00 00 ff 72 75 Xbox RT

0000 | 01 80 80 80 80 08 01 00 00 00 70 75 Xbox LB

0000 | 01 80 80 80 80 08 00 00 ff 00 70 75 Xbox LT

0000 | 01 80 00 80 80 08 00 00 00 00 70 75 LS UP

0000 | 01 80 ff 80 80 08 00 00 00 00 70 75 LS Down

0000 | 01 00 80 80 80 08 00 00 00 00 72 75 LS Left

0000 | 01 ff 80 80 80 08 00 00 00 00 6f 75 LS Right

0000 | 01 80 80 80 80 00 00 00 00 00 70 75 Dpad Up

0000 | 01 80 80 80 80 04 00 00 00 00 6f 75 Dpad Down

0000 | 01 80 80 80 80 06 00 00 00 00 70 75 Dpad Left

0000 | 01 80 80 80 80 02 00 00 00 00 71 75 Dpad Right

0000 | 01 80 80 80 00 08 00 00 00 00 6e 75 RS UP

0000 | 01 80 80 80 ff 08 00 00 00 00 6d 75 RS Down

0000 | 01 80 80 ff 80 08 00 00 00 00 6a 75 RS Right

0000 | 01 80 80 00 80 08 00 00 00 00 6c 75 RS Left

0000 | 01 80 80 80 80 08 08 00 00 00 70 75 Xbox Start

0000 | 01 80 80 80 80 08 00 01 00 00 6d 75 Xbox Select

0000 | 01 80 80 80 80 08 80 00 00 00 70 75 Android Home

0000 | 01 80 80 80 80 08 04 00 00 00 6d 75 Android Back

If you need any other thing or help, just say.

**Comment by ndeadly** [comment]
Looks good. Did you forget L3/R3 or does this controller not have them? Also, what is meant by the Android vs Xbox distinctions?

**Comment by juice808** [comment]
0000 | 01 80 80 80 80 08 20 00 00 00 70 75 R3
0000 | 01 80 80 80 80 08 10 00 00 00 70 75 L3

It is a xinput pc controller, also an Android controller. The Home and Back buttons doesnt work in PC, and could be home as home and back as printscreen.

**Comment by ndeadly** [comment]
Here we go. See if I got the mappings right first try.

[MissionControl-0.3.0-razer-serval.zip](https://github.com/ndeadly/MissionControl/files/5542975/MissionControl-0.3.0-razer-serval.zip)

**Comment by juice808** [comment]
Its working perfectly! Superb!!!! You're the best! Thank you so much.

**Comment by ndeadly** [comment]
No problem. Enjoy :)
