### ISSUE TITLE
Chinese wireless pro gamepad (fake wiiu pro controller) 

### ISSUE THREAD

**Issue by blue32gt** [ndeadly/MissionControl#142]
Hi,

was wondering if its possible to get this controller to work on the switch? my last chinese fake wiiu pro controller worked fine but this one wont connect. It does work on my wiiu however. 

This is the controller I bought from aliexpress;
https://www.aliexpress.com/i/4000245715873.html

Info i could pull from the pc for the controller;
Device HID\VID_0471&PID_0666\7&2e1b13b3&0&0000 was not migrated due to partial or ambiguous match.

Last Device Instance Id: HID\VID_0E8F&PID_0035\7&366F15&0&0000
Class Guid: {745a17a0-74d3-11d0-b6fe-00a0c90f57da}
Location Path: 
Migration Rank: 0xF000FC00FFFFF100
Present: false
Status: 0xC0000451

or failing that what is the cheapest analog controller i can buy that will work with the switch mission control?

**Comment by ndeadly** [comment]
Quite a few people have had problems with fake WiiU controllers so I can't promise anything. I think many of them use a chipset that's incompatible with the Switch. 

That said, since you can connect it to a PC without issue I might be able to make yours work. It looks as though this one is setting its own hardware ID rather than using the ID from the official controller. Normally the controller would still connect as an unrecognised pad, but in the case of the Wii controllers I need to recognise them first in order to send a pairing pin code back to the controller.

I'll try whitelisting the hardware ID for you after work today to see if it works. The issue that I have with this though is that these Chinese knockoff controllers don't conform to any rules and often just steal the hardware ID of some other device (eg. VID 0x0471 you posted above is the vendor ID for Phillips) or even just set it to some random garbage. There's no guarantee that the ID uniquely identifies this controller type, or that other units of the same controller even use the same ID.

> or failing that what is the cheapest analog controller i can buy that will work with the switch mission control?

Not sure what you mean by analog controller. I can't really answer the question of what's the cheapest controller you can use as there are so many out there. I only own official console controllers myself. The only thing I can suggest is to look up the prices of the ones I've listed as supported.
In theory, I can add support for any controller that doesn't use Bluetooth LE as long as it can be detected by the Switch hardware. Controllers marketed for use with Android seem to work well from my experience. I would say known brands would be a safer bet than some generic knockoff from aliexpress.

**Comment by ndeadly** [comment]
See if your controller pairs with this build. I whitelisted both of those hardware IDs shown in what you posted above, so if it works could you show me the output of btdb.nro so I know which one worked?

[MissionControl-0.3.0-aliexpress-wiiupro.zip](https://github.com/ndeadly/MissionControl/files/5562308/MissionControl-0.3.0-aliexpress-wiiupro.zip)

**Comment by blue32gt** [comment]
No luck unfortunately, probably not worth you wasting your time on this junk. i can just save up and buy a decent controller. 

Is it possible it spits out a different random code each time? i just plugged into my pc now and I can see these codes which look different to the one I posted earlier;

device not migrated
Device HID\VID_0471&PID_0666\7&1d120e23&0&0000 was not migrated due to partial or ambiguous match.

Last Device Instance Id: USB\VID_046D&PID_C05B\7&28CCDA35&0&3
Class Guid: {745a17a0-74d3-11d0-b6fe-00a0c90f57da}
Location Path: 
Migration Rank: 0xF000FFFFFFFFF100
Present: false
Status: 0xC0000719

device configured
Device HID\VID_0471&PID_0666\7&1d120e23&0&0000 was configured.

Driver Name: input.inf
Class Guid: {745a17a0-74d3-11d0-b6fe-00a0c90f57da}
Driver Date: 06/21/2006
Driver Version: 10.0.18362.175
Driver Provider: Microsoft
Driver Section: HID_Raw_Inst.NT
Driver Rank: 0xFF1004
Matching Device Id: HID_DEVICE_UPR:FF00-FFFF
Outranked Drivers: input.inf:HID_DEVICE:00FF1005
Device Updated: false
Parent Device: USB\VID_0471&PID_0666\6&2d5ba513&0&2


device started
Device HID\VID_0471&PID_0666\7&1d120e23&0&0000 was started.

Driver Name: input.inf
Class Guid: {745a17a0-74d3-11d0-b6fe-00a0c90f57da}
Service: 
Lower Filters:

**Comment by blue32gt** [comment]
just plugged in again got these numbers... i am not computer savvy but they just seem to be changing each time i plug it in :) 


on the device started time stamp
Device USB\VID_0471&PID_0666\6&37c525a8&0&4 was started.

Driver Name: input.inf
Class Guid: {745a17a0-74d3-11d0-b6fe-00a0c90f57da}
Service: HidUsb
Lower Filters: 
Upper Filters:

**Comment by ndeadly** [comment]
I don't know what half of those fields are actually describing. The important part is `VID_0471&PID_0666`, which appears to remain constant.

If you like you could try running this build with debug logging enabled and post the log (`sdmc:/bluetooth-mitm.log`) it produces after trying to pair the controller a few times. I can take a look to see if there are any clues as to where it's going wrong.

[MissionControl-0.3.0-debug-logging-aliexpress.zip](https://github.com/ndeadly/MissionControl/files/5577561/MissionControl-0.3.0-debug-logging-aliexpress.zip)

**Comment by blue32gt** [comment]
[bluetooth-mitm2nd.log](https://github.com/ndeadly/MissionControl/files/5579160/bluetooth-mitm2nd.log)
[bluetooth-mitm1st log.log](https://github.com/ndeadly/MissionControl/files/5579161/bluetooth-mitm1st.log.log)
here you go, did a 2nd as i connected a real switch pro controller in the 1st file. Wasnt sure if that would confuse things.

**Comment by ndeadly** [comment]
I see no evidence of the switch seeing any WiiU controller during discovery in either of those logs. Just a nearby TV and your Pro Controller. I think this one might be a lost cause just like most of the other fake WiiU controllers.
