### ISSUE TITLE
Request - Mocute 050 gamepad support

### ISSUE THREAD

**Issue by luxrayss** [ndeadly/MissionControl#144]
I'm using the last version of Mission Control, and when I try to connect my Mocute 050 on my Switch, it does get recognized, but none of the buttons works, maybe incompatibility? 
I tried every method of pairing that that gamepad supports (iOS, Android, PC...), but the result was always the same.
Can you add support to that controller?

**Comment by ndeadly** [comment]
Already done, just not officially released yet. See #128

**Comment by mrcnza** [comment]
hi i know this is kinda old but i have a different version of the mocute 050(mine has an F version), since its not noticed on my switch hoping for a respond .

![image](https://github.com/ndeadly/MissionControl/assets/148602619/f7d4c08a-1a28-4291-9e4e-839c78df5a61)

![image](https://github.com/ndeadly/MissionControl/assets/148602619/e9835a5c-5535-4b72-abac-91cf861f3dc7)

it works the same as the ones presented here but idk why it just doesnt show up on my switch.

**Comment by ndeadly** [comment]
Somebody else spoke of an F version of another mocute controller that appears to possibly be using Bluetooth LE, which isn't officially supported right now. I have some experimental builds supporting the protocol being shared in the #testing channel of my discord channel. Feel free to join and give the controller a try with the latest test build.

**Comment by mrcnza** [comment]
thanks for the response, may I ask where I can locate your discord? appreciate it alot, cheers to you

**Comment by ndeadly** [comment]
There's an invite link on the purple discord badge at the top of the project readme here on GitHub (sorry don't seem to be able to share the link from mobile)
