### ISSUE TITLE
Xbox one controller behavior

### ISSUE THREAD

**Issue by itchyd** [ndeadly/MissionControl#151]
It may not be solvable but when using an Xbox 1 controller if you go to change grip/order and all connected controllers turn off (so I can make myself player 1 for example) Xbox one controllers do not turn off.  They go back into a blinking mode and will usually reconnect as a first player.  

The same thing happens when the console is put to sleep the Xbox one controller is put into blinking mode and tries to reconnect. 

A kill signal or something like it is needed. 

This is a big (small) problem because I usually want to be first player so I don't end up staring at menus in Mario kart waiting for someone to press start

**Comment by ndeadly** [comment]
I'm surprised nobody has complained of this one sooner. I'm aware of it and it can be a bit annoying, but I'm not sure if anything can be done about it. The console already sends a disconnect signal to controllers in these cases. I'm not sure why the Xbox behaves as if the signal dropped instead. There might be a special command for it (your kill signal). I've seen a command documented by someone as "crashing" the controller. Maybe that can be used. I will look into it.

**Comment by kakra** [comment]
That "crash" command can be used with USB connections only. Bluetooth HID mode does not have such a command. There are also no power or energy related commands in this mode. If you manage to crash the controller in Bluetooth HID mode (which is possible by sending rumble commands with a certain timing and pattern), it will usually reboot and reconnect after 30 seconds.

**Comment by ndeadly** [comment]
@kakra do you have this same issue with xpadneo?

**Comment by kakra** [comment]
Yes, if I disconnect the controller from Bluetooth by issuing a disconnect command in `bluetoothctl`, the controller goes into blinking state and reconnects after 10-30 seconds. If the controller crashes, it freezes for about 30 seconds (until either itself or the Bluetooth stack disconnects it due to timeout), then it reconnects itself - usually with rumble turned off, so the controller seems to "know" it crashed in the rumble code. But the latter may simply be a software issue where rumble APIs do not pick up the control that re-appeared.

If you want it to turn off, you'd need to remove its pairing from the Bluetooth stack. The blinking state times out after one or two minutes, and then it turns itself off. I'm not sure if you can access the pairing data but then it would be possible to temporary removing pairing and adding it back in the correct order.

If the controller turns off, it will send a final battery packet indicating this:
https://github.com/atar-axis/xpadneo/blob/bf8a3c3d7e28162d074744539d0b228566cb0e32/hid-xpadneo/src/hid-xpadneo.c#L658-L663

I never tried if it would be possible to actually **send** this HID report. I don't think it would be possible.

**Comment by itchyd** [comment]
There has to be a way to do it as turning off an Xbox connected to an Xbox one controller turns off the controller.

**Comment by ndeadly** [comment]
The controller doesn't use Bluetooth when connected to the console though.

**Comment by kakra** [comment]
Yeah, only GIP protocol mode has a command to turn it off. Bluetooth doesn't.
