### ISSUE TITLE
DS4 Left Analog Stick, wrong mapping?!

### ISSUE THREAD

**Issue by Digileandro** [ndeadly/MissionControl#152]
The left analog stick of the dual shock 4 controller is moving the camera, making impossible to play some games. Can this be fixed? Thx!

**Comment by ndeadly** [comment]
Good catch, I can confirm that something is up with that. I recently refactored some of the stick handling code so that could the the cause. At a glance, everything looks fine though, and other controllers I tested didn't have the issue so I'm a bit confused why this is happening. I'll try to look into it today.

**Comment by ndeadly** [comment]
Fixed now. It was a stupid copy/paste bug between the 2 different input report formats for ds4. Redownload the 0.4.0 release for the fix. I didn't think it warranted a new release.

**Comment by Digileandro** [comment]
Awesome, thanks you so much 😊
