### ISSUE TITLE
DS4 connection problems

### ISSUE THREAD

**Issue by MistaMelon** [ndeadly/MissionControl#157]
My DS4 controller (v2) does not want to connect to the switch. I have the latest version of mission control and atmosphere. I have tried with just the normal way (share and ps button). And also tried with L1 and R1 pressed in while connecting but sadly nothing.

**Comment by ndeadly** [comment]
Don't worry about the L + R thing, it's mostly so the system can know which mode you're using the Joycons in. The controller will show up by itself when it connects. Are you on the `Change Grip/Order` screen why you're trying this? Check that lightbar is blinking in a heartbeat pattern too. If not, then you're not entering sync mode successfully.

If you're doing all the above, then you might just need to keep trying. Some DS4 controllers can be troublesome and take a few cycles before they finally complete the pairing process. I think it's due to variations in the hardware. I've only heard of one DS4 that refused to connect at all, and the user suspected it may have been a convincing fake.

**Comment by MistaMelon** [comment]
Thanks for the quick response! But sadly no luck yet, been trying for the last 30min. I can confirm that I am in the change grip order screen (with the 1, 2, 3, 4 boxes). I can also confirm that I am indeed going into sync mode with the controller and that its a real one since it came with an actual ps4. Tried resetting the controller but that didn't do much sadly. Switched between docked and undocked but also no luck.

**Comment by ndeadly** [comment]
Have you rebooted the console since installing MissionControl? Do you have any other non-nintendo controllers to confirm it's actually running?

**Comment by MistaMelon** [comment]
I have just rebooted the console and after 3 tries it got connected, terribly sorry to waste your time like this, but thank you very much for the quick responses and for the amazing app!

**Comment by ndeadly** [comment]
All good. You just need to be aware that most sysmodules are only loaded at boot time so you need to reboot whenever you install/upgrade. Glad it was a simple fix.
