### ISSUE TITLE
GEN GAME S3: Controller works but not listed

### ISSUE THREAD

**Issue by Fahim732** [ndeadly/MissionControl#172]
This is the hardware ID from Windows 10 BTHENUM\Dev_FF10DF026325
This is the one of the cheapest controller I have and fortunately this works with my Nintendo Switch with MissionControl. Just one downside is home button emulation can be executed by mode 2 of this controller just by pressing "select" button, where mode 2 is actually mouse mode of this controller, mode 1 is as gamepad input.

**Comment by ndeadly** [comment]
> This is the hardware ID from Windows 10 BTHENUM\Dev_FF10DF026325

I don't know exactly what that ID is, but it's not the vendor/product one that I need. Can you post the output of btdb.nro? If you don't already have it you can find it here with the 0.3.0 release https://github.com/ndeadly/MissionControl/releases/tag/v0.3.0

This controller isn't listed because I haven't explicitly added support for it. The fact that it works at all probably means it's using the same hardware ID as one of the other controllers I support and being detected as that. A lot of the cheap controllers use things like `0000:0000` as a hardware ID. I guess it was only a matter of time before there was a clash.

This controller likely needs its own handler created to work properly, I just need to figure out how to uniquely identify it.

**Comment by kakra** [comment]
FF10DF looks like a MAC address OUI, we use those in xpadneo to tell models apart that use identical PID/VID. Maybe MC could do something similar?

Here's the Microsoft docs on this:
https://docs.microsoft.com/en-us/windows-hardware/drivers/bluetooth/installing-a-bluetooth-device

But that doesn't even reflect that format of the ID.

**Comment by Masamune3210** [comment]
That is the generated device path for the bluetooth device on Windows. It is generated from a number of things iirc, including device id, mac, and some other information. I forget exactly all that Windows does to create unique device paths but it might be useful to look into. They have to be unique per device so it would prob be similar to what this needs

**Comment by Fahim732** [comment]
> > This is the hardware ID from Windows 10 BTHENUM\Dev_FF10DF026325
> 
> I don't know exactly what that ID is, but it's not the vendor/product one that I need. Can you post the output of btdb.nro? If you don't already have it you can find it here with the 0.3.0 release https://github.com/ndeadly/MissionControl/releases/tag/v0.3.0
> 
> This controller isn't listed because I haven't explicitly added support for it. The fact that it works at all probably means it's using the same hardware ID as one of the other controllers I support and being detected as that. A lot of the cheap controllers use things like `0000:0000` as a hardware ID. I guess it was only a matter of time before there was a clash.
> 
> This controller likely needs its own handler created to work properly, I just need to figure out how to uniquely identify it.

Hey, sorry for late reply cause I was sleeping.
the PID/VID from btdb.nro of my controller is 1949:0402 and it says GEN GAME S3 on the output screen.

**Comment by ndeadly** [comment]
> FF10DF looks like a MAC address OUI, we use those in xpadneo to tell models apart that use identical PID/VID. Maybe MC could do something similar?

@kakra that's not a bad idea if that's a reliable identifier. I like that better than falling back on device names like I currently do.

@Masamune3210 thanks for the explanation. Knowing exactly how Windows generates the identifier probably isn't all that useful to us though. The Switch only passes on a subset of the available device info that it cares about. The information we have is enough to uniquely identify a controller, you just never know what these cheap controllers are going to do. They're free to set all identifying info to that of some other device but then send a completely different packet format if they want to.

> Hey, sorry for late reply cause I was sleeping.
the PID/VID from btdb.nro of my controller is 1949:0402 and it says GEN GAME S3 on the output screen.

@Fahim732 no problem. Looks like your controller uses the same ID as some of the ipega controllers so this explains what's going on. Is the controller working correctly in gamepad mode or not at all? This wasn't clear from your original post. That's the mode you should be using it in. I'm not so fussed if mouse mode is broken.

**Comment by kakra** [comment]
> @kakra that's not a bad idea if that's a reliable identifier.

It seems reliable so far, we can clearly find out if the controller is a remake from a different manufacturer. I think this is because the MAC is also used in broadcast radio signals (Bluetooth) and thus needs to use a separate vendor specific identifier and that's independent from the PID/VID which is usually just an ID that can be re-used by everyone who makes compatible devices: It doesn't identify a distinct single device anyways in contrast to MAC addresses which do this. We even patch the PID/VID in the driver so games would see our controller as one that's compatible and we patch the HID reports to match that expectation.

We are defining the filters here:
https://github.com/atar-axis/xpadneo/blob/6d9025629811baf917362621137941cf925b9ebe/hid-xpadneo/src/hid-xpadneo.c#L82-99
```c
#define DEVICE_NAME_QUIRK(n, f) \
	{ .name_match = (n), .name_len = sizeof(n) - 1, .flags = (f) }
#define DEVICE_OUI_QUIRK(o, f) \
	{ .oui_match = (o), .flags = (f) }

struct quirk {
	char *name_match;
	char *oui_match;
	u16 name_len;
	u32 flags;
};

static const struct quirk xpadneo_quirks[] = {
	DEVICE_OUI_QUIRK("E4:17:D8",
			 XPADNEO_QUIRK_NO_PULSE | XPADNEO_QUIRK_NO_TRIGGER_RUMBLE |
			 XPADNEO_QUIRK_NO_MOTOR_MASK | XPADNEO_QUIRK_NINTENDO),
	DEVICE_OUI_QUIRK("44:16:22", XPADNEO_QUIRK_SHARE_BUTTON),
};
```

Some vendors may actually sub-divide their OUIs by using a fourth byte but usually the first three bytes identify the vendor and sometimes also the model uniquely. As you can see, `441622` identifies the new Xbox One X|S controller. This only works for Bluetooth connections but since MC is all about Bluetooth, it is probably the right solution as long as you can fetch the MAC address somehow.

We also had model name matching at some point (`DEVICE_NAME_QUIRK`) but that wasn't too reliable as it might change after firmware updates.

`E417D8` for 8BitDo is a bit more complicated as they seem to ship very different models under the same OUI label (some with and some without analog sticks) but at least their HID protocol is the same so that match is still good enough for xpadneo. You may need to look at further hints, tho, i.e. how long the HID report packets actually are that you're receiving in the Bluetooth stack: Different models sometimes carry one or more extra bytes for additional state reports (e.g., Xbox Elite 2 sends the paddle state and various other info in such additional bytes). That means: As soon as we see a HID report of a certain length, we know that we are seeing a different model or an older firmware version with different behavior/quirks.

Example:
https://github.com/atar-axis/xpadneo/blob/6d9025629811baf917362621137941cf925b9ebe/hid-xpadneo/src/hid-xpadneo.c#L841-852
```c
	/* XBE2: track the current controller settings */
	if (report->id == 1 && reportsize >= 21) {
		if (reportsize == 55) {
			hid_notice_once(hdev,
					"detected broken XBE2 v1 packet format, please update the firmware");
			xpadneo_switch_profile(xdata, data[35] & 0x03, false);
			xpadneo_switch_triggers(xdata, data[36] & 0x0F);
		} else {
			xpadneo_switch_profile(xdata, data[19] & 0x03, false);
			xpadneo_switch_triggers(xdata, data[20] & 0x0F);
		}
	}
```

If the report size is 55, we know that we are seeing a controller with an older buggy firmware.

**Comment by Fahim732** [comment]
> > FF10DF looks like a MAC address OUI, we use those in xpadneo to tell models apart that use identical PID/VID. Maybe MC could do something similar?
> 
> @kakra that's not a bad idea if that's a reliable identifier. I like that better than falling back on device names like I currently do.
> 
> @Masamune3210 thanks for the explanation. Knowing exactly how Windows generates the identifier probably isn't all that useful to us though. The Switch only passes on a subset of the available device info that it cares about. The information we have is enough to uniquely identify a controller, you just never know what these cheap controllers are going to do. They're free to set all identifying info to that of some other device but then send a completely different packet format if they want to.
> 
> > Hey, sorry for late reply cause I was sleeping.
> > the PID/VID from btdb.nro of my controller is 1949:0402 and it says GEN GAME S3 on the output screen.
> 
> @Fahim732 no problem. Looks like your controller uses the same ID as some of the ipega controllers so this explains what's going on. Is the controller working correctly in gamepad mode or not at all? This wasn't clear from your original post. That's the mode you should be using it in. I'm not so fussed if mouse mode is broken.

not a problem bro, mouse mode works fine with my android TV but for sure this controller is working and listing it won't be bad idea. If I get a chance, I'll try another controller too. 
My controller is working correctly with gamepad mode and I played Super Mario Odyssey with it without any issues.

**Comment by ndeadly** [comment]
@kakra thanks for the detailed explanation, I'll definitely look into this. Do you have much experience with cheap Chinese controllers? These are the ones of most concern as they tend to do whatever they feel like. It wouldn't surprise me to see them setting random OUI values.

@Fahim732 oh ok, then I might just consider this an ipega clone and leave it how it is now that we understand what's happening. It's much easier to just tell users to use the gamepad mode than it is to try to support other modes that use the same report ID. I'll add it to the list of supported controllers though, thanks for reporting.

**Comment by kakra** [comment]
> thanks for the detailed explanation, I'll definitely look into this. Do you have much experience with cheap Chinese controllers? These are the ones of most concern as they tend to do whatever they feel like. It wouldn't surprise me to see them setting random OUI values.

@ndeadly The only thing I found so far is that Chinese remakes often have an incomplete rumble implementation that either doesn't support all features, or simply ignores some values. Other than that there's not much left that could be done wrong.

**Comment by ndeadly** [comment]
@kakra good to know. Yeah, as I've mentioned before, I don't have any way to retrieve the HID report descriptors. This would be a non-issue otherwise
