### ISSUE TITLE
Bluetooth headphones support

### ISSUE THREAD

**Issue by AndradeMatheus** [ndeadly/MissionControl#177]
Any chance that this is viable now? From what everybody speculated, it was impossible to connect any kind of device that wasn't Nintendo™ wirelessly due to how the switch bluetooth works, but from what I've tested with MissionControl and gamepads, it works flawlessly!

**Comment by ndeadly** [comment]
No. The switch bluetooth driver service implements only a small set of required bluetooth services, and there is nothing for audio transport included amongst those. It won't be possible without adding the missing features via a bluetooth service reimplementation or possibly some form of code injection/function hooking. Both of which would require a large amount of work with no guarantee it will work smoothly under HOS in the end. I doubt anyone will bother with it. 

The reason bluetooth controllers can be "unlocked" is because the hid peripheral handling code is already present. MissionControl just needs to make the incoming data look like it comes from an official controller so it doesn't get rejected by the console.
