### ISSUE TITLE
Error Code: 2143-0263 (0x20e8f)

### ISSUE THREAD

**Issue by aphexgiba** [ndeadly/MissionControl#178]
First of all, congratulations on Mission Control!

Randomly, sometimes when I put the switch in sleep mode after playing in the dock, after a few minutes in sleep mode, I get the following error message on the screen: Error Code: 2143-0263 (0x20e8f)
The system is stops on the on the error screen until I press the power button, so it´s restarts.

Looking at the error, I came to the conclusion that it has to do with the bluethoot of the controller.

I use a Dualshock 4.

**Comment by ndeadly** [comment]
Could you post the error report here? The code alone doesn't tell me much about what is happening.
Also some information about your environment would be useful. HOS/Atmosphere/MissionControl versions, any other sysmodules you might have running etc. 

The only times I've seen these kind of errors have been during dev when I've been doing something funny that the system doesn't like. I wasn't aware of any such cases in any of the release versions. Is this something you've been experiencing frequently or can reproduce reliably?

**Comment by aphexgiba** [comment]
Ow, that´s was fast! Sorry of the lack of information, where i go.

![IMG_20210112_183106](https://user-images.githubusercontent.com/77361136/104377630-90f36600-5505-11eb-9c6c-a4fb5515dd09.jpg)

Im using hekate v5.3.4. and the last version of Mission Control 0.4.1 (11 dec)

_Is this something you've been experiencing frequently or can reproduce reliably?_
The first time I saw the error happen was a week after installing Mission Control, with an average of 30 hours of play. After the first error, it happens twice a week (I play almost every day for 3 hours).

I tried to reproduce the error by turning the Switch on and off, but it doesn't happen. Today it happened again.

The dualshock is always charged, and using wirelessy.

Thank you for the fast response.

**Comment by ndeadly** [comment]
Looks like it's something to do with power management, and the console going to sleep/waking up, but it's hard to say exactly what's triggering it. Could be some kind of timing thing if it's only happening occasionally. I'll keep an eye out for it and see if there's any way I can reproduce on my console. These sort of intermittent things are always hard to track down.

It might also be interesting to see if you still get the issue running the lastest HOS/AMS, as that's what I've tested the newer builds with.

**Comment by impeeza** [comment]
Latest AMS & Hekate have corrected some sleep related issues

**Comment by lBenevides** [comment]
Having the same problem, was playing Ori and WW docked with my dualshock 4 and put the console to sleep mode, just a few minutes later and I look at the console and shows this error. It's the second or third time this happens.
 
My system is on 10.2.0 | AMS M17.0|E

Have a sysnand with the most recent firmware

![20210114_000255](https://user-images.githubusercontent.com/58781731/104540029-76041d00-55fd-11eb-9493-0a5fbafb115d.jpg)

**Comment by lBenevides** [comment]
Sorry for the lighting in the screenshot haha

**Comment by ndeadly** [comment]
@lBenevides thanks for confirming it's not an isolated incident. Are you a new user or has this issue just started for you recently?

I notice you're both using Hekate, I wonder whether there's any connection there with regards to how sleep is handled. I mostly boot my console through fusee.

I'm familiar with these sort of errors though, they're usually caused by something not being cleaned up properly before the console goes to sleep. Does the light bar on your DS4 go out shortly after you put the console to sleep or does it stay lit even when the error screen shows? One way you might be able to avoid this error for now is to turn off the controller by holding `ps` before putting the console to sleep. I'm also fairly confident you'll only see these errors on sleep, so I wouldn't worry too much about games crashing and losing progress during play.

**Comment by lBenevides** [comment]
Yeah, i'm not worried about crashing during play. I've played for good 3/4 hours and nothing happed. Will update my console to the latest firmware on emuNAND and see if still happens and will let you know. 

Thanks for the support and the awesome job building this.

**Comment by jacoghi** [comment]
Just got the same issue,
![IMG20210219204904](https://user-images.githubusercontent.com/13020415/108579323-5b0b8380-72f4-11eb-9495-2a87fd0546e8.jpg)

**Comment by ndeadly** [comment]
@jacoghi the lightbar staying on means the console didn't disconnect the controller before going to sleep. Not doing so will cause a crash like you have have seen. I encountered this a lot in the early days of development before I figured out how to receive Bluetooth events without denying them to the rest of the system. The problem now is that the disconnection should be handled automatically by the `btm` module upon sleep. I don't really have any control over this process.

I have seen some mentions of power management related bug fixes mentioned in commit messages for libnx/atmosphere. With a bit of luck this issue could just be due to some subtle inaccuracy in these libraries and could go away in future builds. I have changes in my development branch to patch out sending a vendor command that could potentially cause problems with some controllers. Otherwise it may be some behaviour of the DS4 controllers that doesn't play nice with the switch Bluetooth that we might just have to live with. I'd be interested to know whether any other controllers can trigger the same crash or if it's just the DS4. As I mentioned above, the best way to avoid it for now would be to make sure you power down the controller yourself before putting the console to sleep. I might add it to the list of known issues in my readme at least.

**Comment by jacoghi** [comment]
@ndeadly I fully understand man, trust me, this is a beautiful piece of software in my opinion. I'll test some scenarios out here and see if I can get a crash with a different controller. This afternoon I basically forced it into crashing by connecting / disconnecting the DS4 till I got the lightbar to stay on. I didn't do anything different, it's completely random from the user input since I just stuck to the home screen, connected, sleep, repeat. I have one V1, one V2 and one Doubleshock 3rd party, I'll cycle them through and see if I can identifiy some root cause.
