### ISSUE TITLE
Razer raiju tournament edition

### ISSUE THREAD

**Issue by martiz54** [ndeadly/MissionControl#179]
It's me , again. Please add support for raiju tournament edition .

**Comment by martiz54** [comment]
Raiju connect to nintendo switch on both mode (pc and ps4) but dont recognize buttons.

**Comment by ndeadly** [comment]
Can you post the output of btdb so I can see the controller name and ID?

**Comment by martiz54** [comment]
Ps4 mode
![20210115_205708](https://user-images.githubusercontent.com/76749597/104773103-cbaf0580-5774-11eb-889e-e9aef8504f22.jpg)
Pc mode
![Uploading 20210115_205921.jpg…]()

**Comment by martiz54** [comment]
Sorry for quality

**Comment by ndeadly** [comment]
The second image isn't working. Are the entries different for each mode?

**Comment by martiz54** [comment]
Second image (i dont but have switch on backplate).
![Uploading 20210115_205921.jpg…]()

**Comment by ndeadly** [comment]
Looks like that ID is the same for both modes. It's probably more trouble than it's worth trying to support both modes since it looks like they can't be distinguished without inspecting the packets. I think I'll whitelist this one as a PS4 controller since that seems to be what it's marketed as, so use PS4 mode. .

See if this build allows the controller to work correctly in PS4 mode
[MissionControl-0.4.1-razer-raiju-tournament.zip](https://github.com/ndeadly/MissionControl/files/5822796/MissionControl-0.4.1-razer-raiju-tournament.zip)

**Comment by martiz54** [comment]
Work on both mode 
Thank you

**Comment by Badabid** [comment]
@martiz54 do you have latency on the Raiju TE? BTW controller now connects thank you

**Comment by martiz54** [comment]
Yes and analog drift,  i back this controller to store
