### ISSUE TITLE
AMS 0.17.1 FW 11.0.0 not working

### ISSUE THREAD

**Issue by josete2k** [ndeadly/MissionControl#183]
As I wrote...

Atmosphere 0.17.1 and FW 11.0.0 seem don't work...

**Comment by ndeadly** [comment]
Please explain what you mean by not working. This really doesn't give me any information. You also failed to mention the MissionControl version you're running.

**Comment by josete2k** [comment]
Sorry.

Lastest version of MissionControl

No pairing... I've tested with Onyx HORI (not pro) and DS4 v2 with no success

**Comment by josete2k** [comment]
WiiU pro controller is working instead

**Comment by ndeadly** [comment]
The DS4 should work, assuming it's genuine. I also support the Onyx, but I did have another user recently who wasn't able to get it to connect, so that one's a maybe.

If you can connect your WiiU Pro controller then it sounds like the software is running properly and you're on the correct screen for pairing. All of the PS4 type controllers have been problematic to some degree. Some work without issue, but many can require multiple attempts before they will connect. I think there are variations in the bluetooth hardware used. I suggest you keep your switch on the pairing screen and keep trying to pair. You might find that they connect after a while. Also make sure that you're entering pairing mode on the controller correctly. If done properly the lights on the DS4 will flash in a heartbeat pattern.
