### ISSUE TITLE
Rumble is not working for 8bitdo adapter

### ISSUE THREAD

**Issue by acamir1369** [ndeadly/MissionControl#191]
Hi my friend 
Hope you are well.
My question is that why rumble is not working on my 8bitdo adapter when missioncontroll is working?there is any way rumble work with my 8bitdo adapter on my dualsense as my first controller and use my xboxone controller as second controller with missioncontroll same time?
Missioncontroller knows 8bitdo adapter as pro controller?
If you remove pro controller support from missioncontroller problem will be slove?rumble will work?

Thanks

**Comment by ndeadly** [comment]
Mission Control shouldn't change the behaviour of your 8bitdo adapter. Those adapters handle the Bluetooth connection themselves, but act as a USB controller to the Switch. The controller never makes a direct Bluetooth connection to the console, so will not be picked up my Mission Control. There should be no issues with using the two together.

I would guess either your controller is connecting to the switch Bluetooth instead of the adapter, or you have rumble disabled somewhere. You might also want to confirm the 8bitdo actually supports rumble for that controller too if you haven't already.
