### ISSUE TITLE
Fatal error when opening tinfoil

### ISSUE THREAD

**Issue by stefluid7** [ndeadly/MissionControl#197]
AMS - 1.18.1
SFW - 11.0.1
Program ID: 0100000000000004
Error Desc: std::abort() called (0xffe)

I get this error every time I open tinfoil with mission control enabled/installed. I have found mission control to be the source of the problem. Not too sure what to do moving forward. Might try archbit and see if that helps.

**Comment by jacoghi** [comment]
What other modules do you have installed? How did you confirm it's mission control the culprit? This error is associated with the sm extension, it's possible to be happening due to many modules that used that exgtension before. Try tinleaf or goldleaf to see if you get the same error.
Reference for a similar issue. I'm a missioncontrol user and I tested one by one of my modules to narrow the issue down, and mission control is not the culprit.

https://github.com/spacemeowx2/ldn_mitm/issues/83

**Comment by ndeadly** [comment]
As @jacoghi stated, title ID `0100000000000004` indicates an `sm` fatal error. Atmosphere 0.18.0 introduced some breaking changes requiring homebrew sysmodules that register services to be updated. Somehow the presence of Mission Control appears to be triggering these errors, but I don't believe it's the root cause. You likely have another sysmodule installed that requires updating (or removal). A user [reported](https://github.com/ndeadly/MissionControl/issues/195) a similar issue a few days ago that was caused by saltynx. If you are unsure how to proceed, post a picture of the contents of your `/atmosphere/contents` directory.

Also, piracy is not supported. Please cease any further discussion of piracy-enabling tools.

**Comment by stefluid7** [comment]
I was able to narrow it down to mission control after I saw another issue in atmosphere GitHub. I preceded to disable it and it started working again. I have sys-botbase, tesla (emuiibo), sysdvr, and possibly some others. 
![435](https://user-images.githubusercontent.com/77551816/108429401-2799fd80-71fd-11eb-8b76-f7639bae785c.PNG)

**Comment by jacoghi** [comment]
To narrow it down, you should start only with atmosphere in your SD card. Drop missioncontrol on top of it (only mission control, nothing else is necessary, not even the tesla menu) and see if the problem still happens. There are a lot of people reporting problems with this, that or whatever modules without properly testing them, so you should kinda ignore these repo issues right now and perform your own testing by individually testing the modules. I did so and missioncontrol turned out to be harmless to my setup, AMS 0.18.1. It was another module which was triggering the crash. After missioncontrol is installed and if nothing crashes, keep dropping the modules till you notice the crash. Only then you will know what the real culprit is. After that, you can go one step further by removing missioncontrol contents and seeing if without it, the system still crashes. If it doesn't, then it's a combination of the two modules, otherwise it's just the last installed module.

**Comment by ndeadly** [comment]
@stefluid7 as I said before, no doubt that the presence of Mission Control is triggering the crash, but it seems to be other outdated sysmodules that are setting it up to fail. I don't fully understand what's going on, but it might simply be due to the fact Mission Control makes a lot of service calls in the background to process controller inputs vs other modules that may lay idle most of the time.

Follow the advice from @jacoghi. I'm going to bet it's emuiibo (`0100000000000352`) to blame.

**Comment by stefluid7** [comment]
Yeah I just wiped contents and left mission control and it is working now. I will further diagnose and test emuiibo. Thanks!

**Comment by jacoghi** [comment]
Good to know. So my stable setup is currently mission control, sys ftpd light, emuiibo 0.6.2 (previous versions will trigger a crash as well), sys clk, and all tesla related stuff (ovlmenu, nxovlloader, sysmodules) and it's rock solid. In my case the culprit turned out to be ldn_mitm, so I don't think emuiibo will be issue here either.

**Comment by stefluid7** [comment]
Removing emuiibo seemed to fix it but removing mission control did as well... I will try to narrow it down more.

**Comment by ndeadly** [comment]
@stefluid7 emuiibo has been [updated ](https://github.com/XorTroll/emuiibo/releases/tag/0.6.2) for Atmosphere 0.18.0 (should work with 0.18.1 too as the breaking changes came in 0.18.0). If you install the updated version I imagine you should be able to run both emuiibo and Mission Control without issue.

**Comment by stefluid7** [comment]
I appear to be on the newest version of both. I isolated and ran the two and was still having the same issue. Someone else in the emuiibo github had a similar issue. I started having the problems after I updated emuiibo. I tried an older version with no success. I will attach the crash log if you are able to take a look at it.
[report_0000000032f046ac.zip](https://github.com/ndeadly/MissionControl/files/6006813/report_0000000032f046ac.zip)

**Comment by stefluid7** [comment]
Nvm it's sys-clk.

**Comment by stefluid7** [comment]
I just removed it and everything works again. Will look into this more.

**Comment by stefluid7** [comment]
Yeah I'm rlly confused at this point. I removed sys-dvr and things are work. It was most likely due to me throttling the system with all the sys modules. I am fine without sys-dvr for the time being.

**Comment by ndeadly** [comment]
Yeah, it is starting to sound a bit like an issue of resource exhaustion due to too many sysmodules. Though the `0100000000000004` error still hints that it's a sysmodule that needs to be updated for latest Atmosphere. Is this still the error message you're seeing?

**Comment by stefluid7** [comment]
Yeah still getting that, not to sure which module is the culprit because deleting anyone one of them fixes the issue,

**Comment by 923017006** [comment]
Same problem occurred to me as well. I found it will crash when I active  sys-clk, tinfoil and NSAInstaller. After deleted Mission Control everything turns normal again.

**Comment by Ti800** [comment]
same crash here.emuiibo cant work with missioncontrol .and they are all the latest version.

**Comment by impeeza** [comment]
I do use ONLY emuiibo, ftp light and mission control sysmodules at same time and no problem at all.  Please check for others sysmodules getting on the way.  Run the minimum of sysmodules and start to add one by one of the others and you will find the culprit.
