### ISSUE TITLE
Using 3rd party controllers to wake the system 

### ISSUE THREAD

**Issue by vink2212** [ndeadly/MissionControl#199]
I understand this is a limitation of mission control and also most 3rd party controllers that they cannot be used to wake the switch up but since you've been developing for the switch's BT protocol I was wondering is there a possibility to use an application to wake up the switch by using a smartphone or something along those lines. Also, have you found an answer as to why most 3rd party controllers are not able to wake the switch from sleep?

**Comment by ndeadly** [comment]
Depending on how it's done it might be possible to wake the console from a PC. Doing so with a smartphone may also be possible, but would probably require the device to be rooted/jailbroken. I suspect you would need to send low level Bluetooth commands not exposed by the available APIs.

It's not clear to me whether you mean non-switch controllers or 3rd party knockoff pro controllers when you say third party controllers. The former can't do it because they haven't been designed for the Switch, so can't possibly know what to send to the console (there is no standardised "wake command").  For the latter, I'm not so sure. Maybe they just haven't been able to figure out how it's done. Probably requires reverse engineering the firmware of the bluetooth chip or expensive bluetooth sniffing hardware.

**Comment by vink2212** [comment]
yeah so when i say "non-switch" i simply mean 3rd party (eg 8bitdo,gamesir,powerA, etc) I have a rooted phone. is there a possibility to develop an app that can wake the switch like a remote? if so  would like to help/learn how to make one my self lol 
i know some powerA controllers can actually wake the switch yet most controllers don't hence why i am interested in figuring this out might be useful to some people

**Comment by ndeadly** [comment]
It might be possible, but it would first require understanding how wake via controller is actually implemented. The Bluetooth chips also allow for OOB (Out Of Band) wake-from-sleep, which means that the signal to wake the host doesn't even necessarily have to be sent via Bluetooth. 

I've had a bit of a poke around but so far haven't been able to find any clues as to how it's being done. We are only able to log Bluetooth communications after the console is awake and the CPU is running. In all likelihood, it will require some combination of opening up the controller and probing around, intercepting the wireless signals or dumping and dissecting the firmware of the controller/Bluetooth chip. If these are within your skillset, by all means take a look and see what you can find out. Once the mechanism is understood, writing an app to emulate it is the easy part (assuming it's possible with smartphone hardware).

**Comment by ndeadly** [comment]
If you're seriously interested in investigating this further, you can find the datasheet for the switch bluetooth chip [here](https://pdf1.alldatasheet.com/datasheet-pdf/view/1018098/CYPRESS/BCM4356XKUBG.html). 

dekuNukem also has some datasheets for the controller side of things in his [repo](https://github.com/dekuNukem/Nintendo_Switch_Reverse_Engineering/tree/master/datasheets)

**Comment by HelloRayH** [comment]
> It might be possible, but it would first require understanding how wake via controller is actually implemented. The Bluetooth chips also allow for OOB (Out Of Band) wake-from-sleep, which means that the signal to wake the host doesn't even necessarily have to be sent via Bluetooth.
> 
> I've had a bit of a poke around but so far haven't been able to find any clues as to how it's being done. We are only able to log Bluetooth communications after the console is awake and the CPU is running. In all likelihood, it will require some combination of opening up the controller and probing around, intercepting the wireless signals or dumping and dissecting the firmware of the controller/Bluetooth chip. If these are within your skillset, by all means take a look and see what you can find out. Once the mechanism is understood, writing an app to emulate it is the easy part (assuming it's possible with smartphone hardware).

Recently, I was analyzing the wake-up mechanism of the switch game console. I found that the handle wakes up the switch console through CH37 (2402MHz), CH38 (2426MHz), and CH39 (2480MHz). In other words, the wake-up data interaction is completed through the BLE broadcast channel.
At first, I used an old 2.4G RF chip to monitor the wakeup between the game controller (Pro controller or Right Joycon) and the switch game console. This method is too cumbersome and time-consuming.
![image](https://github.com/user-attachments/assets/6410a896-2fd4-451d-adb8-770fa6f6da32)
ater, it will be much more convenient to use SDR to capture wake-up data, but it will often encounter problems such as data bit confusion or loss.
![image](https://github.com/user-attachments/assets/c0750758-0bf5-482d-a0ae-04c8748bbbf8)

**Comment by HelloRayH** [comment]
After I sent the wake-up code obtained from the switch game console in the form of data through the 2.4GRF chip or Bluetooth chip, I found that the console responded to the data sent.
![image](https://github.com/user-attachments/assets/e01bef82-ec2a-4f4d-92c5-ca296681089c)
![image](https://github.com/user-attachments/assets/1c54d0de-2890-4be8-8271-1b64622cbad3)

As you can see, the switch and the controller responded to each other.
![image](https://github.com/user-attachments/assets/bb3a0c05-fe39-4460-902d-9ffebe9e42a6)
Now, the problem is how to generate the correct wake-up code and how to let the Bluetooth chip receive the response packet from the switch. There are two problems involved here. One is the wake-up code, which is a 4-byte data sequence, which is somewhat similar to the OOK wake-up mechanism of EFR32xG22
https://www.silabs.com/documents/public/presentations/tech-talks-wake-bluetooth-from-deep-sleep-using-an-rf-signal.pdf

**Comment by HelloRayH** [comment]
Another one is the access code. How to generate the correct access code so that the Bluetooth chip can receive the response data packet from the switch.
As for the wake-up code, after analysis, it was found that the wake-up code is only related to the host. The handles that have been paired and connected to the specified host all send the same wake-up code. It can be boldly guessed that the wake-up code is related to the Bluetooth MAC address of the host. But how to convert the wake-up code from the Bluetooth MAC address of the host is still unknown.
As for the access code, according to the sync word definition given by the Bluetooth specification, it involves (64,30) expurgated block code and pseudo-random noise (PN) sequence. Although the Bluetooth specification gives a relatively detailed description and provides sample data in the appendix, I have no experience with this and don’t know how to start. Can anyone help me?

**Comment by adrastious** [comment]
Hopefully someone can find out how to do this with CFW :D 
It's annoying to lay down and forget to turn the switch on when docked

**Comment by ndeadly** [comment]
It can't work from the CFW side, because all running software is suspended when in sleep.

**Comment by monkeycc** [comment]
Hello, I've been researching the wake-up issue of the Switch Pro controller recently. I was wondering if there has been any resolution to this issue after all these years
@HelloRayH

**Comment by ndeadly** [comment]
There's no "resolution" in the context of third party controllers being able to wake the system. That is never going to happen. Someone in my discord server recently shared a PoC for ESP32 though https://github.com/608/NS1-Wakeup-Demo

**Comment by monkeycc** [comment]
> 在第三方控制器能够唤醒系统这件事上，没有所谓的“解决方案”。那永远不会发生。不过我Discord服务器里有人最近分享了一个ESP32的PoC https://github.com/608/NS1-Wakeup-Demo

Thank you for your help
Many third-party gamepads in China have already achieved wake-up functionality

**Comment by ndeadly** [comment]
> Many third-party gamepads in China have already achieved wake-up functionality

Third party Switch controllers where the developers have control of the hardware and/or firmware, sure. But the issue you are replying to is regarding arbitrary pre-existing bluetooth controllers.

**Comment by monkeycc** [comment]
Can I join your Discord @ndeadly

**Comment by ndeadly** [comment]
Sure, invite link can be found at the top of the project readme or in the release notes
