### ISSUE TITLE
Request for the 8BitDo FC30

### ISSUE THREAD

**Issue by PinooXx** [ndeadly/MissionControl#206]
Please include the wonderful FC30 from 8BitDo. I really would appreciate the work.

Thanks  and mission control is great :)

**Comment by ndeadly** [comment]
Is the FC30 firmware upgradeable? Many 8BitDo controllers will support Switch natively with the latest firmwares. I can't find this one listed on their website though.

If not I'll need the output of my [btdb ](https://github.com/ndeadly/MissionControl/releases/download/v0.3.0/btdb.nro) app after succesfully pairing the controller to the console, and a transcription of the raw controller data for each button press using [this ](https://github.com/ndeadly/MissionControl/files/5539371/hid_report_viewer.zip) tool.

**Comment by ndeadly** [comment]
Found a [manual](https://download.8bitdo.com/Manual/Controller/N30+F30/N30+F30_Manual_V4.pdf) that seems to suggest Switch mode is supported.

**Comment by impeeza** [comment]
Hi, All 8Bitdo have 4 different modes of working. With exception of 8Bitdo Zero which only uses D-Input(Android) mode and  SN30 Pro which only uses X-Input method emulating a original XBox controller.

The methods can be selected Keeping pressed a button before turn on the controller.  for the majority of models the modes are:

D-Input Mode (android mode)   B+Start
X-Input Mode (Emulating a original X-Box controller)   X+Start
Switch Mode (Emulating a original Switch pro controller)   Y+Start
D-Input Mode (mac os compatible)  A+Start

Actually Mission control support the D-Input Mode (Android) for the 8Bitdo Zero,  and X-input Mode because for all effects is a X-Box controller and no needed for Switch mode because the switch identifies as a original controller.

Please go to www.8bitdo.com and search the manual and latest firmware for your controller and you get all functions working fine.

**Comment by PinooXx** [comment]
Thanks for your help. Wasn't aware that the old 8bitdo already has the switch support. 

Many thanks :))
