### ISSUE TITLE
Issue with tinfoil

### ISSUE THREAD

**Issue by Akirakurusu0** [ndeadly/MissionControl#210]
Having missioncontrol installed on atmosphere 0.18.1 messes up tinfoil, it crashes on startup and shows this error![Snapchat-1188249964.jpg](https://user-images.githubusercontent.com/46596185/110960272-ddfd8800-834e-11eb-90b0-ef7f3a3c0b91.jpg)

This only happens when missioncontrol is installed, when removed, tinfoil starts normally

**Comment by ndeadly** [comment]
I don't believe mission control is the root cause of the problem, it just triggers it. See https://github.com/ndeadly/MissionControl/issues/197

Show me the contents of your `/atmosphere/contents` directory if you're unsure of how to proceed.

Also, I don't provide support for piracy enabling tools. Any further discussion of them and the issue will be removed.

**Comment by Akirakurusu0** [comment]
![Screenshot (44)](https://user-images.githubusercontent.com/46596185/110975458-0fcb1a80-8360-11eb-9730-f6c4011dce86.png)
Tried the build you provided, same error, But here's my contents folder (minus the atmosphere ones)

**Comment by ndeadly** [comment]
```
0100000000000352	emuiibo
4200000000000010	ldn_mitm
```

It's almost certainly one of these two (or both) to blame. `emuiibo` and `ldn_mitm` frequently cause problems after Atmosphere updates. Make sure you have the latest release installed for both of those. I don't know whether they've been updated for the latest Atmosphere though. You may have to disable/delete them if not.

Anyway, the fact that you still get the error with that build pretty much proves that Mission Control isn't the culprit.

**Comment by Akirakurusu0** [comment]
thank you so much, after some trial and error and updating everything, it now works

one question though, how'd you recognize the sysmodule from the titleid alone though? is there any program for that or something?

**Comment by ndeadly** [comment]
> one question though, how'd you recognize the sysmodule from the titleid alone though? is there any program for that or something?

You get pretty good at recognising them when people are continually reporting similar issues either here or the Atmosphere issue tracker :p

I've also been working on putting together a little tool to scan the contents directory and identify possible causes of issues to eliminate the need to users to have to post screencaps of their contents directory like we've done above. I compiled a list of known sysmodules for that from switchbrew and github so I can also easily search that rather than relying on memory. I uploaded it here if you're interested https://gist.github.com/ndeadly/a4b8c01bb453028cd0008f282098f696
