### ISSUE TITLE
MissionControl Stops Goldleaf 0.9 from working.

### ISSUE THREAD

**Issue by muddpunk** [ndeadly/MissionControl#220]
I install MC today.. and I love it. I can finally stop using my drifting joy cons and utilize my spare Xbox one controllers. However, since installing MC, I can no longer use Goldleaf. I don't know what incompatibility issues there are, but after removing MC I was able to launch Goldleaf again.

I posted this in the Goldleaf issues
-----------------------------------------
Goldleaf fatal report
-Goldleaf version: 0.9.0
-Current time 19:40:36
-Fatal result 0x4B59

When I try to run Goldleaf again I get:

Panic occurred while running Atmosphere.
Title ID 0100000000000004
Error: std::abort <0xFFE>

Press POWER to continue.

Current system version: 11.0.1|AMS M.18.1|S
------------------------------------

I'm not entirely sure if it bugged out because I grabbed it from the Homebrew App Store and not directly from here, but I shouldn't see why that should make much difference anyway. I will grab the release from here and try again. 

I will update this comment if it is successful but if I don't update.. Assume I was unsuccessful 😅

**Comment by ndeadly** [comment]
Which other sysmodules do you have installed? There have been a number of these kind of errors surfacing since the atmosphere 0.18.0 update. I'm aware that the presence of mission control will trigger the fatal crash in `sm` (TID `0100000000000004`), but I'm fairly convinced it's not actually the cause of the issue. Other people having reported similar crashes when launching other applications have turned out to have had outdated versions of sysmodules such as emuiibo or ldn_mitm and updating those has resolved the problem.

> I'm not entirely sure if it bugged out because I grabbed it from the Homebrew App Store and not directly from here, but I shouldn't see why that should make much difference anyway. I will grab the release from here and try again.

In theory it shouldn't make a difference, but as the dev I'm biased toward recommending you use the github releases so that you can be sure you have the latest unmodified release.

**Comment by muddpunk** [comment]
Thank you for getting back to me promptly 😅 

I've just checked Sysmodules in the tesla overlays (sysmodules 1.2.1) and I have emuiibo 0.6.2 (which as far as I can tell is the latest) and MissionControl (I merged the folder from the latest release on here).

Here is the screenshot from the directory /atmosphere/contents
![2021-04-10](https://user-images.githubusercontent.com/48693062/114283339-2937b300-9a41-11eb-82ec-6d668cc6f1c3.png)

**Comment by ndeadly** [comment]
You've also got ldn_mitm in there (`4200000000000010`)

**Comment by muddpunk** [comment]
Ah ok. So I just had a browse through my homebrew menu and saw I did in fact have ldn_mitm. Clicked it and it was enabled. Just disabled it and I'm back to being able to use Goldleaf again 😅 Thanks for helping me out so quickly btw. MissionControl is absolutely legendary and I appreciate the work you have done 😄

**Comment by ndeadly** [comment]
No problem. Taking a look at ldn_mitm on github, it looks like it hasn't actually been updated since atmosphere 0.16.1, presumably because it appears to work with the latest versions. Atmosphere 0.18.0 made changes that required any sysmodules that register services (which it does) to update. I think it's just luck that it somehow works without an update. You'll probably need the dev to release an updated version to be able to use it in conjunction with Mission Control.

**Comment by muddpunk** [comment]
> No problem. Taking a look at ldn_mitm on github, it looks like it hasn't actually been updated since atmosphere 0.16.1, presumably because it appears to work with the latest versions. Atmosphere 0.18.0 made changes that required any sysmodules that register services (which it does) to update. I think it's just luck that it somehow works without an update. You'll probably need the dev to release an updated version to be able to use it in conjunction with Mission Control.

Luckily I don't use it. I only tried to get it working about a week ago so as I could play local with my son, unfortunately it didn't work, so I'll probably just remove it anyway if I'm honest. Thank you for looking in to it further 👍

**Comment by kronictripy420** [comment]
@ndeadly I know this is closed but I have an issue with Mission Control I thought I had to open through hblmenu 😂😂😂😂, so I look on gethub and seen that there is a master 
on there that changes some file for MC to run better on 13.2.1., after I put files in the exact folder were included in .zip file, now when I try to connect my PS4 con. to switch it blinks while in change grip/order then solid still can't use con. So shut con. off then try to reconnect via. Bluetooth then almost immediately after Atmosphere has a panic while running Atmosphere. 

TitleiD: 0100000000000BD00
Error: std: : abort <0xFFE>

Press POWER to continue

**Comment by ndeadly** [comment]
@kronictripy420 I'm not sure why you're commenting on this issue. It doesn't seem to be related in any way. 

Please open a new issue of your own and attach the error report.
