### ISSUE TITLE
[BUG] WiiU Pro Controller not pairing on latest

### ISSUE THREAD

**Issue by cybercuate** [ndeadly/MissionControl#239]
OFW: 12
CFW: ATM 19
MissionControl: 0.4 and 0.5Alpha

Official wiiu pro controller
Used to work well on OFW 11 w/ATM now doesn't pair.
I wiped the controllers db and not working.

**Comment by ndeadly** [comment]
Yes, this is a known issue. The the release notes for the 0.5.0 pre-release state that many controllers won't pair under 12.0.0.
Wii(U) controllers are a special case because they use legacy bluetooth pairing that the switch doesn't handle by default and requires a command to be sent manually by mission control to make it work. This command was changed in 12.0.0 and needs to be updated, and since this firmware broke pairing for most controllers anyway I made the 0.5.0 pre-release without updating it. This should be fixed by the time 0.5.0 is officially released.

You should be able to downgrade below 12.0.0 to pair controllers then upgrade again as a workaround for now

**Comment by ndeadly** [comment]
I've finally figured out the problem and created a set of ips patches for all 12.x.x firmwares to make Wii controllers work again. They will be included in the final 0.5.0 release which I will make over the weekend, but for anyone who is feeling impatient, here they are. Enjoy.

[12.x.x_bluetooth_patchset.zip](https://github.com/ndeadly/MissionControl/files/6796122/12.x.x_bluetooth_patchset.zip)

**Comment by ndeadly** [comment]
0.5.0 has now been release with full support for Wii/WiiU controller pairing https://github.com/ndeadly/MissionControl/releases/tag/v0.5.0

**Comment by jonblacksmith** [comment]
I think WiiU Pro controller pairing is broken again. 

Xbox One controller pairing works great however!

**Comment by ndeadly** [comment]
Works fine for me. I updated ips patches for 13.0.0 specifically for this.

**Comment by jonblacksmith** [comment]
Oh, I didn't realize that Atmosphere updated to 1.1.1. Updated from 1.1.0 pre-release and now all is good. Thanks.

**Comment by ndeadly** [comment]
Atmosphere version shouldn't have made a difference. Maybe you just forgot to reboot or something
