### ISSUE TITLE
Cant connect Dual Sense + 2 joypads

### ISSUE THREAD

**Issue by GeorgeCalderoESP** [ndeadly/MissionControl#240]
Hello.

I dont know if im doing somethig wrong.

I want to connect Dual Sense and the two NSW joypads.

Joypads are well recognizes but Dual Sense was recognized but doenst work.

Any ideas?

Thanks.

**Comment by ndeadly** [comment]
Which firmware are you on? 12.0.0 made some nontrivial changes to the Bluetooth service and introduced a bug that broke pairing for many controllers. This seems to be fixed in 12.0.1

**Comment by GeorgeCalderoESP** [comment]
Im using 10.2.0. And Mission Control under 4.1. 

Enviado desde mi iPhone X

**Comment by impeeza** [comment]
> Im using 10.2.0. And Mission Control under 4.1. Enviado desde mi iPhone X

Please read the others  posts.  For now you should be using the latest version of firmware (12.0.1) and mission control

**Comment by ndeadly** [comment]
@GeorgeCalderoESP I wouldn't expect any issues from that combination, but you should update Mission Control to the 0.5.0-alpha to get all the latest bugfixes and features. It's labelled alpha/pre-release because of some 12.0.0 compatibility issues, but should be just as stable as 0.4.1 for older firmwares.

> Dual Sense was recognized but doenst work.

What do you mean by this? It pairs with the console but the buttons don't work?

**Comment by GeorgeCalderoESP** [comment]
I updated to 12.0.1, Atmosphere and mission control to 5.0 alpha and it works!! Thanks



Enviado desde mi iPhone X
