### ISSUE TITLE
Insane Latency and Dropped inputs problem on Sony Dualshock 4 V2 (Pre-release 0.5.0. AMS 19.1/FW 12.0.1)

### ISSUE THREAD

**Issue by SwigS-27** [ndeadly/MissionControl#246]
Recently updated to Firmware 12.0.1 and also updated MissionControl to 0.5.0.
Since then, when trying to play rhythm games there's been a massive latency problem often resulting in dropped inputs also.
Below is a video (with a Controller Overlay) that should hopefully illustrate the problem I'm facing here

https://youtu.be/3Qqt6kJ9qeM

With how I played in the video above, the final result should've been either a "Perfect" if not a high percentage "Excellent" but because of the dropped inputs and latency issues, that's far from the case

In previous versions of MissionControl on 10.x and 11.x, input was perfectly fine with little to no delay with inputs. Probably something to do with what was added in 12.0.x. Don't know but I thought it'd be a good idea to report what happened nonetheless

**Comment by ndeadly** [comment]
As someone who doesn't play a lot of rhythm games it's hard for me to see the issue clearly with so much going on in that video :p

But that's interesting. Nothing much should have changed in the way inputs are processed between firmwares. Does this happen everywhere or just in this game? (what game is that by the way? Native? Emulator?)

Are you able to downgrade back to 11.x.x with mission control 0.5.0 and see if it still occurs there. I'm curious whether it's something I've changed since 0.4.1 or it's a firmware thing.

**Comment by SwigS-27** [comment]
It doesn't just happen in that game, no. Experienced it in Taiko no Tatsujin as well. 
The game shown in the video is "Hatsune Miku: Project DIVA Mega Mix" and it runs natively and not through emulation.

And I could downgrade to 11.x as I still have the firmware dumped on my SD Card. 
So I'll give that a try

**Comment by SwigS-27** [comment]
Okay after downgrading back to 11.0.1, the latency and dropped inputs problem is no longer occurring and as such, I'm able to play just fine once again. Going to update back to 12.0.1 so I can check is if nx-btred possibly caused the problems

**Comment by SwigS-27** [comment]
Alright so I updated back to 12.0.1 and yeah, no latency issue.
It was entirely because of nx-btred. Sorry about making this whole issue thread about it - I was tried last night and didn't even think that was a possibility.
So I can confirm though:
Having nx-btred + MissionControl causes the latency problems even if no audio device had been connected on boot.
MissionControl on it's own has no problems and works perfectly fine.

**Comment by ndeadly** [comment]
Don't worry about it. Input latency is a legitimate concern, even if not caused by mission control itself. It has been speculated that latency issues may be why Nintendo haven't officially enabled support for Bluetooth audio. It's good to have had someone test it out and document their findings either way. 

Anyway, glad you were able to resolve it.
