### ISSUE TITLE
PS4 third-party controller request

### ISSUE THREAD

**Issue by Luucas99** [ndeadly/MissionControl#247]
Hi, i've tried using MissionControl to connect via bluetooth my PS4 third-party controller but it doesn't work.
If you could help me solving this problem i would be very thankful, i don't know how i could send you my controller details but if you tell me how i can try.

Thanks in advance.

**Comment by ndeadly** [comment]
Does the controller pair with the console? You may have to try several times as some PS4 controllers can be stubborn. If you're doing everything correctly and it still won't connect there may not be much I can do. Some third party clones don't work for whatever reason.

If you're able to connect it, but it's not working, it probably just has a new hardware ID that needs to be whitelisted. You can check the details with https://github.com/ndeadly/MissionControl/releases/download/v0.3.0/btdb.nro

**Comment by vontdeux** [comment]
Hi, I have this 3rd party ps4 controller too, it can connect, but after few minutes it will hang, unresponsive, with led still lit up, and other controller will simply replace its position(if it was blue, the next controller connect will be blue)

Anyway, how to whitelist it?

**Comment by ndeadly** [comment]
@vontdeux normally you shouldn't hijack issues of others like this as it creates confusion as to whether the original issue was resolved. I'll let it slide though because this issue seems pretty much dead anyway.

Does the controller work at all before it hangs, or does it simply show up as connected to the console as a controller with red buttons under the controller menu? If the buttons are working for a period then nothing needs to be done with regards to whitelisting, it's already being recognised. The hangup is some other issue. If you see the red buttons then your device is using a different hardware ID and needs to be whitelisted. Use the btdb app I posted in the link above to display your paired devices and post a screenshot here so I can see the hardware ID

**Comment by vontdeux** [comment]
Well, the reason I reply to this because I don't want to unnecessary new issue, I have a 3rd party ps4 controller and it does not work, and the creator of issue doesn't reply after you suggest a solution. Whatever it is if I'm hijacking, I'm sorry

After connecting, it will work for few minute all button (similar to original ps4 controller), so I guess I should open a new issue or is there already a same issue on going? (again I don't want to create unnecessary new issue)

**Comment by ndeadly** [comment]
That's a good attitude to have, but in the case of requesting controller support I think it's fine to start your own issue. There's no way to tell from "PS4 third party controller" (the original author has given no other identifying information) that you have anything in common with the original author other than also owning a controller that will work on PS4. They're not all created equal. Anyway, it's not a big deal, I just wanted to make a point that sometimes it's fine to create a new issue even if it sounds like a duplicate.

Ok, then the controller is being detected as a regular DS4 and something else is causing it to stop responding. Possibly the chipset it uses doesn't like the SetTsi command the console sends. This issue hasn't been reported previously though, so I would suggest opening a new issue for it.
