### ISSUE TITLE
trying to create a build, error on Atmosphere libs 

### ISSUE THREAD

**Issue by Wat6656** [ndeadly/MissionControl#251]
got this error when trying to build the Atmosphere-libs, any idea? thanks!!! 

/MissionControl/Atmosphere-libs/libmesosphere/include/mesosphere/kern_k_memory_region_type.hpp:167:127: error: '<anonymous>' is not a constant expression
  167 |  auto KMemoryRegionType_DramKernelBase   = KMemoryRegionType_Dram.DeriveSparse(0, 3, 0).SetAttribute(KMemoryRegionAttr_NoUserMap).SetAttribute(KMemoryRegionAttr_CarveoutProtected);
      |                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by ndeadly** [comment]
My guess would be that something in your setup is out of date. Make sure you've updated your devkitpro environment, and built and installed my libnx fork rather than the latest stable release. 

Does this error actually cause the build to abort? I can't check right now, but I seem to recall seeing some errors relating to libmesosphere that didn't affect the building of libstratosphere, which is what we actually care about.

If the above doesn't resolve your issue this question might be more suited for the [Atmosphere-libs](https://github.com/Atmosphere-NX/Atmosphere-libs) github repo, however.

**Comment by Wat6656** [comment]
just updated and added all the libs. still get the error while it it complining and causes it to abort. will post in the other forum. thanks!

**Comment by ndeadly** [comment]
Actually, now that I look closer, I can tell from that file path and the line that the error occurs on that you're trying to build from master. libnx and Atmosphere-libs are probably out of sync due to the force-push I mentioned above.

Run `git checkout develop`, re-build and install libnx (`make && make install`), and then your Atmosphere-libs build should work.

**Comment by Wat6656** [comment]
will just download from github. its on there

**Comment by Wat6656** [comment]
take that back, cant find it

**Comment by ndeadly** [comment]
Did you build and reinstall libnx after switching to develop? That error suggests it's potentially finding an old version that doesn't have that file present. You may also want to run `make clean` before attempting to build Atmosphere-libs again after switching branches

**Comment by Wat6656** [comment]
got this when i was buidling libnx tar: include/switch/services/htcs.h: Cannot open: Permission denied

**Comment by Wat6656** [comment]
odd cause that was the only file that i got denied permission. all others built, running a clean then trying again

**Comment by ndeadly** [comment]
Which platform? You may need `sudo make install` instead if not on Windows. Not sure why else you'd see a permission denied error.

**Comment by Wat6656** [comment]
yup started working on that as you posted this. i might have to do a fresh install of my OS. using WLS2 on windows, using Kali.  Thank you!!

**Comment by ndeadly** [comment]
You probably need `sudo` on WSL(2) on Windows too. Not sure, I build using the devkitpro msys2 terminal.
