### ISSUE TITLE
Ipega PG-9025 not working in a new update.

### ISSUE THREAD

**Issue by Darkjhonf** [ndeadly/MissionControl#257]
My Firmware 12.0.1 AMS m.19.2
I try to pair again, but it cannot connect to the console, in previous versions it did work.

**Comment by ndeadly** [comment]
I think ipega controller pairing might still be broken since the 12.0.0 update. 12.0.1 fixed the issue for most controllers, but somebody else reported another ipega controller still not working too. You could try updating to 12.0.2 to see whether it fixed anything. Other than that this is a little beyond my control for now and I can only really suggest you downgrade below 12.0.0 temporarily to pair the controller as a workaround.

**Comment by Darkjhonf** [comment]
Ok guys its working on Firmware 11.0.1 AMS m.19.3

**Comment by ndeadly** [comment]
These [patches](https://github.com/ndeadly/MissionControl/issues/271#issuecomment-864234121) I created for 12.x.x may allow ipega controllers to work again on the latest firmwares. Let me know if you have any success with them.

**Comment by ndeadly** [comment]
Closing as patches have been verified to fix the issues with ipega controllers and 12.x.x firmwares
