### ISSUE TITLE
Does not recognize anything

### ISSUE THREAD

**Issue by Gosetox** [ndeadly/MissionControl#260]
I tried to synchronize two xbox one controllers, an Ipega, a wiimote and neither recognizes it, although I have put the most recent version in the SD which says that it is compatible with atmosphere 0.19.3 in 12.0.2, it is as if I did not have activated the mission control, is there a way to know what is active on my console?

**Comment by impeeza** [comment]
Sysmodules on tesla overlay

**Comment by Gosetox** [comment]
The module was active but still does not recognize any control, a better option was to install the sys-con module to play by usb at least

Thanks for the help

**Comment by ndeadly** [comment]
@Gosetox Wii (U) controller pairing hasn't been updated to work with firmwares 12.0.0+ yet, and a couple of people have reported ipega controllers not pairing since the 12.0.0 update. Xbox One controllers should work though (the new Xbox series X/S controllers will not, however). Make sure you're on the `Change grip/order` screen for pairing. 

As for determining whether the module is running, there isn't currently any reliable way. While the sysmodule overlay status is probably a good indicator, I think all this is actually doing is detecting the presence of the boot2.flag file in the module directory. There is still a small chance that the module may not be running if something has gone wrong.

**Comment by luizlago** [comment]
@ndeadly you talked about Xbox Series S/X controllers, can you tell what firmware is working theses controllers? I tried on 12.0.2 and 11.0.1 and not work in both

**Comment by ndeadly** [comment]
@luizlago you've misunderstood, they're not currently supported at all due to using Bluetooth LE

**Comment by spooferek** [comment]
I am waiting for WiiU Pro controller support, currently is not recognized at all with 12.0.0 FW. When this feature should be expected?

**Comment by ndeadly** [comment]
When I figure out why it's broken. Downgrade below 12.0.0 temporarily if you need to pair your controller.

Please remember that these issues are not a Q&A discussion forum.

**Comment by secondYUEN** [comment]
Please check you  ‘’contents” file folder in PC，when DBI software connect PC。
if the contents  file folder like a file，DEL，and rebuild。
enjoy~

**Comment by ndeadly** [comment]
> Please check you  ‘’contents” file folder in PC，when DBI software connect PC。
> if the contents  file folder like a file，DEL，and rebuild。
> enjoy~
> 
> 
> 

🤨

**Comment by ndeadly** [comment]
These experimental [patches](https://github.com/ndeadly/MissionControl/issues/271#issuecomment-864234121) I created _may_ allow your ipega controller to work with 12.x.x. Wii controllers still require some work. Let me know if you have any success.
