### ISSUE TITLE
Will 0.4.1 work with Atmosphere 0.19.3 on 11.0.1 (emuMMC)? 

### ISSUE THREAD

**Issue by dbw-holic** [ndeadly/MissionControl#262]
Hi @ndeadly, thank you very much your work, really appreciated. 
I am currently running HOS 12.0.2 on sysNAND and 11.0.1 on emuNAND, powered by the latest atmosphere 0.19.3

I am aware of the official support for Mission Control 0.4.1 is up to 11.0.1 with Atmosphere 0.16.1. I prefer the stable version if I don't have to use the current alpha version that has support for Atmosphere 0.19.3

When looking at the condition "Updated to support 11.0.1 firmware/Atmosphere 0.16.1", should I take it 11.0.1 AND 0.16.1 or, 11.0.1 OR 0.16.1? 

Regards,
David.W

**Comment by ndeadly** [comment]
Just use the latest release. It's not really an alpha, it's stable and was just labelled as alpha because I had assumed 12.0.0 had broken everything and I would have to do a bunch of additional work to support it. It turned out most of my problems were issues with official Nintendo software that were fixed in 12.0.1. The only thing missing is updated support for Wii(U) controllers on 12.x.x, which will be added in the final release of 0.5.0.

If you really insist on using 0.4.1, you will need to compile it yourself with an up to date version of libstratosphere if you want to be able to run it on the latest atmosphere.

In the future, please use the discussions page for asking questions. Issues is for software bugs and feature requests.

**Comment by dbw-holic** [comment]
> Just use the latest release. It's not really an alpha, it's stable and was just labelled as alpha because I had assumed 12.0.0 had broken everything and I would have to do a bunch of additional work to support it. It turned out most of my problems were issues with official Nintendo software that were fixed in 12.0.1. The only thing missing is updated support for Wii(U) controllers on 12.x.x, which will be added in the final release of 0.5.0.
> 
> If you really insist on using 0.4.1, you will need to compile it yourself with an up to date version of libstratosphere if you want to be able to run it on the latest atmosphere.
> 
> In the future, please use the discussions page for asking questions. Issues is for software bugs and feature requests.

Thank you for your prompt response. I will keep that in mind to use the discussions page in the future.
