### ISSUE TITLE
Request - Xiaomii gamepad

### ISSUE THREAD

**Issue by yovin** [ndeadly/MissionControl#269]
The gamepad work fine but the home button not working, can someone help me to make it working?

**Comment by ndeadly** [comment]
On some gamepads meant for Android the home button doesn't work with the switch. Use the button combo `minus + dpad_down` instead

**Comment by kakra** [comment]
Yeah, those buttons usually come in a separate HID report. You'll need to synthesize a proper input event from that.

**Comment by ndeadly** [comment]
Yeah, I receive a report that contains the home button in most cases. The issue is that unlike the other button presses, it doesn't hold its state and the bit is only set for a single report even if the button is held down. This doesn't register with the console for some reason. I think maybe the next report comes in and unsets it again before the controller state is polled by the application.

**Comment by kakra** [comment]
Usually, there's one bit reserved in report 0x01 which is for the same button. Depending on the firmware version, it may flip on press or it doesn't. You could use report 0x02 to statically flip or unflip that bit in the 0x01 report - essentially patching the report. But if you detect that 0x01 also flips the bit on its own, you should disable the patching for this device from then on.

On model XB1S and XBE2, this should be bit 13. This is also probably true for the XBXS controller (the one with the Share button) but it uses BLE and may have a very different code path in your code.

If in doubt, you could just tell the models apart by looking at the report size as the SDL2 source code does: All models currently have distinctive report sizes.

**Comment by yovin** [comment]
> On some gamepads meant for Android the home button doesn't work with the switch. Use the button combo `minus + dpad_down` instead

Thanks that's work

**Comment by ndeadly** [comment]
> Usually, there's one bit reserved in report 0x01 which is for the same button. Depending on the firmware version, it may flip on press or it doesn't. You could use report 0x02 to statically flip or unflip that bit in the 0x01 report - essentially patching the report. But if you detect that 0x01 also flips the bit on its own, you should disable the patching for this device from then on.

This is essentially what I'm doing with controllers that send multiple report types in order to merge the button state into the switch report format. This doesn't really work with the controllers I've described though, since there's no corresponding report sent when the button is released to unflip the bit. Sure, I could unset it after some time has passed, but I'm not sure I want to deal with the added complexity this will bring to the way inputs get handled. Remember that mission control is more of an hid report translation mod and doesn't have nearly the amount of flexibility that a driver would.

**Comment by kakra** [comment]
Report 0x2 is sent once when pressed with the bit=1, and sent once when pressed with the bit=0. The original Xbox One S controller may send reports repeated times but this should be ignored, it's supposed to send only one report per state change. See here:
https://github.com/libsdl-org/SDL/blob/157c3f8097403c08cc9747082de37276fb2ab28c/src/joystick/hidapi/SDL_hidapi_xboxone.c#L792

They look at the bit and set the button to either pressed or released.

**Comment by ndeadly** [comment]
> Report 0x2 is sent once when pressed with the bit=1, and sent once when pressed with the bit=0. The original Xbox One S controller may send reports repeated times but this should be ignored, it's supposed to send only one report per state change. See here:
> https://github.com/libsdl-org/SDL/blob/157c3f8097403c08cc9747082de37276fb2ab28c/src/joystick/hidapi/SDL_hidapi_xboxone.c#L792
> 
> They look at the bit and set the button to either pressed or released.

Yeah, this is what the older firmwares on the Xbox One controller did and that worked fine. These are not Xbox controllers that we're talking about though, and many of them don't send the report with bit=0. I'm guessing it's meant to trigger a navigation event on Android and they don't care about the button state.

I may have caused confusion earlier when I mentioned the bit being zeroed out again. I am setting it to zero unconditionally when handling the primary button report to avoid the issue of it getting stuck in the pressed state.

**Comment by kakra** [comment]
Then these clone controllers are buggy but yes, it's actually meant for Android but still this report is a normal button and should send a press and release event, otherwise Android won't detect the button release, after all, it's only processed by the Linux input layer. It maps to the KEY_HOME event there.

It should be enough to send the Guide bit once with the next state packet, then let it clear back to 0 with the following cycle. It should be enough to trigger an event but of course it's not possible to use it as a press and hold button then (but it's also the power button so nobody probably wants that anyways). Reading your last sentence, it seems that is what you currently do but maybe the events are overlapping?

**Comment by ndeadly** [comment]
> It should be enough to send the Guide bit once with the next state packet, then let it clear back to 0 with the following cycle. It should be enough to trigger an event but of course it's not possible to use it as a press and hold button then (but it's also the power button so nobody probably wants that anyways). Reading your last sentence, it seems that is what you currently do but maybe the events are overlapping?

The only events to get triggered on the switch are the ones I'm intercepting to modify the report data. Other than that the data just gets written into hid shared memory and polled out by applications. Either it's changing back to zero too quickly to be read, or maybe the switch requires multiple consecutive reports/polling cycles before considering a button to be pressed. Whatever the case, it doesn't get detected with these controllers unless being latched. 

The switch also makes use of press and hold of the home button to bring up a quick menu, which is another reason I haven't invested much time into this and just tell people to use the button combo instead.

**Comment by kakra** [comment]
If it's put into shared memory, the report spamming of the XB1S controller will overwrite the bit immediately, probably before software can even see it. I'm not sure if clone gamepads do the same thing. At least the ones I saw in xpadneo didn't spam HID reports.
