### ISSUE TITLE
Ipega 9076 Request

### ISSUE THREAD

**Issue by Yeison017** [ndeadly/MissionControl#271]
Hi people, I have problems trying to connect my Ipega control on de 12.0.1 and Atmosphere 19.2, the model is Ipega 9076, I was able to connect it running the fw 11.0.x, but now with the 12.0.1 it isn't working, can you help me? Thank you!!

**Comment by ndeadly** [comment]
Yeah, I've had a few people report now that ipega controllers are still not pairing after the 12.0.1 update which fixed many of the others that broke after 12.0.0.

I'm not really sure why this is, but Wii controllers are not working either and I suspect this might be because 12.0.0 started checking device class or something in order to identify bluetooth headphones. I just haven't been able to figure out where this might be taking place, and none of the debugging tools I've been using work on 12.x.x yet.

The Wii controllers don't use the same device class flags as most other controllers, maybe ipega controllers are the same. Maybe you could connect the controller to a PC and try to find the device class property for me?

It's only pairing that doesn't work though, so if you need to use the controller you can temporarily downgrade below 12.x.x to pair it and then upgrade back.

**Comment by ndeadly** [comment]
So I think the reason these ipega controllers aren't working is because they advertise themselves as keyboards rather than gamepads and the new device class checks introduced in 12.0.0 are preventing them from being connected. Here are some test [patches](https://github.com/ndeadly/MissionControl/files/6678907/12_x_x_device_class_patches.zip) I created to modify the device class checks on these firmwares. Let me know if they make any difference for you.

**Comment by Yeison017** [comment]
Yes, and yeeeeesss
Thank you very much man, with those test patches the Ipega 9076 is working again perfectly, thanks for the help 😁👍👍

**Comment by ndeadly** [comment]
Awesome, wasn't expecting it to work first try 😁 You can keep the test patches, but I suggest you move them into `atmosphere/exefs_patches/bluetooth_patches` so they don't interfere if I update the patches included with the release in the future.
