### ISSUE TITLE
Crash when attempting LAN play

### ISSUE THREAD

**Issue by veidtt** [ndeadly/MissionControl#277]
Whenever I try to create/join a local room in Monster Hunter Rise I get a crash with the error message: std: :abort (0xffe). After some research I found out that it was supposedly because I'd be running an out of date version of Mission Control but I made sure to grab the latest one (0.5.0 pre-release 3) after updating atmosphere, hekate and my firmware (12.0.2). This is also happening in other games that feature a LAN play option.
I uploaded the crash report:
[report_000000016407c920.zip](https://github.com/ndeadly/MissionControl/files/6561554/report_000000016407c920.zip)

**Comment by ndeadly** [comment]
This has already been reported [here](https://github.com/ndeadly/MissionControl/issues/243) and [here](https://github.com/ndeadly/MissionControl/issues/250). I posted a build of Mission Control in the first issue about a week ago with some logging enabled but so far nobody has gotten back to me with any results. If you want to give it a try and post the log that would be much appreciated. Unfortunately I don't have a second switch to test with myself.

**Comment by ndeadly** [comment]
Is that crash report from before or after running the latest Mission Control? That's `sm` crashing, not the game or Mission Control. This usually happens when you have an outdated sysmodule on the system. If it's still crashing after updating to the latest Mission Control, it's likely either a different crash, or there's another sysmodule that needs an update. There have been cases recently where outdated sysmodules like ldn_mitm or emuiibo don't crash the system by themselves, but will cause Mission Control to appear to trigger a crash like this. Could you show me your `/atmosphere/contents` directory?

**Comment by veidtt** [comment]
Here are the crash report and log you requested:
[logs.zip](https://github.com/ndeadly/MissionControl/files/6561711/logs.zip)

And here's the contents directory: 
![VqcI0vM](https://user-images.githubusercontent.com/84979615/120005800-80391d80-bfd8-11eb-8b91-311159858ceb.png)

**Comment by ndeadly** [comment]
So `4200000000000010` is ldn_mitm. I highly suspect this requires updating based on that crash report (and the fact that ldn_mitm is also related to LAN play). Try the [latest version ](https://github.com/spacemeowx2/ldn_mitm/releases/tag/v1.8.0) and see if you still get the same crash. If it doesn't make a difference, delete it from your SD and see whether Mission Control alone will trigger the issue.

I don't see anything of interest in the bluetooth-mitm.log. Looks like either you didn't connect any bluetooth controller, or you rebooted your console before grabbing the log and it got overwritten.

**Comment by veidtt** [comment]
I updated ldn_mitm and I'm still getting the crash. I'm not sure as to how to remove it from my SD, should I simply delete the `4200000000000010 ` directory or do I have to remove the nro file too?
As for the bluetooth log, I tried to connect my Xbox series controller but no luck so far.

**Comment by veidtt** [comment]
Well, just looked up the ldn issues and apparently I'm not the only one troubled with this https://github.com/spacemeowx2/ldn_mitm/issues/94
I don't really understand why it's only affecting certain people though.

**Comment by ndeadly** [comment]
Where do you get the impression it's only affecting certain people? Could be a number of things such as combinations of different versions atmosphere, HOS and ldn_mitm, and like I said above, it could be the fact that they're also running Mission Control like you.

> There have been cases recently where outdated versions of sysmodules like ldn_mitm or emuiibo don't crash the system by themselves, but will cause Mission Control to appear to trigger a crash like this

I would still try removing ldn_mitm and see what happens, as those other issues I linked seemed to indicate that there is actually another problem related to Mission Control and LAN play.

**Comment by veidtt** [comment]
You can see a bunch of people still able to play here http://www.lan-play.com/
And yeah I removed the sysmodule and it stopped crashing so I guess we can close this since it's not related to MissionControl. Thanks for the help.

**Comment by ndeadly** [comment]
Cool, happy to help. For what it's worth, ldn_mitm probably just requires recompilation with the latest Atmosphere-libs. I've had to do it for each of the 0.19.x atmosphere releases or else my sysmodule crashes the system on boot (due to an overzealous version check that has now been [relaxed](https://github.com/Atmosphere-NX/Atmosphere-libs/commit/b5b55f60d8567ea4608163abc299e5e238381d44)). I'm not sure how ldn_mitm gets away with it.

And if you do encounter the LAN play errors from the other issues, please consider adding to the discussion :)

**Comment by vkaziv** [comment]
> Cool, happy to help. For what it's worth, ldn_mitm probably just requires recompilation with the latest Atmosphere-libs. I've had to do it for each of the 0.19.x atmosphere releases or else my sysmodule crashes the system on boot (due to an overzealous version check that has now been [relaxed](https://github.com/Atmosphere-NX/Atmosphere-libs/commit/b5b55f60d8567ea4608163abc299e5e238381d44)). I'm not sure how ldn_mitm gets away with it.
> 
> And if you do encounter the LAN play errors from the other issues, please consider adding to the discussion :)

I'm a noob here how do I do a recompilation of the libs I can't do lan play on my hack switches :(

**Comment by ndeadly** [comment]
@vkaziv this isn't a support forum. If you can't figure it out for yourself either raise the issue with the ldn_mitm dev or seek assistance on one of the various discord servers related to Switch hacking.

**Comment by ndeadly** [comment]
So curiosity got the best of me and I tried building ldn_mitm myself with libstratosphere master. This is untested and I make no promises this will solve the problem, nor will I provide any support for it, but if this stops people blaming mission control for the crash then that's a win for me.

[ldn_mitm-ams-0.19.3.zip](https://github.com/ndeadly/MissionControl/files/6572394/ldn_mitm-ams-0.19.3.zip)

**Comment by vkaziv** [comment]
Will try sorry also didn't mean to bug just wanted to know what to use to recompile sorry if I worded it wrong. I appreciate you taking the time to write libstratosphere master as what you use cause now I know what to use for the recompile ty <3

**Comment by ndeadly** [comment]
No problem, I didn't mean to sound rude either. Just that typically someone asking questions like yours has no idea what they're doing and is going want their hand held and start blowing up the discussion with a bunch of unrelated support questions. 

What you want for compiling is the devkitPro toolchain set up for switch development. Atmosphere-libs is where you'll find libstratosphere and that's included as a git submodule when you check out ldn_mitm. I'll leave it to you to figure out the rest, since this discussion is still off-topic.

**Comment by veidtt** [comment]
Lmao you're based for trying to solve it. 
If it's not working, booting with Hekate is the workaround right now. I can still test it if you're curious about the result though.

**Comment by ndeadly** [comment]
@veidtt if booting via hekate fixes it, then the build I posted above probably does too. The latest changes to libstratosphere to relax version checks were motivated by some discussion on discord around sysmodules not failing when hekate was used due to hekate incorrectly configuring the firmware version.

**Comment by vkaziv** [comment]
Well that file didn't work it stop the crash but when looking for lobby it doesn't find my other switch and vise versa  but on my other 2 switches they can do it perfectly but those are the ones that didn't crash either. Also I booted in latest hakate. I formatted sd started from scratch same problem not sure what's going on with that 1 switch

**Comment by vkaziv** [comment]
Idk just a thought I notice when making a lobby my switch will show wifi from what I thought when doing local should it have a L by the wifi signal bars? If so mine isn't showing the L in a lan lobby but the other two switches that work does

**Comment by ndeadly** [comment]
@vkaziv again, this is not a support forum. I posted the build above in an attempt to be helpful to people, under the condition that it may not work and I will not be providing support. This is no longer a mission control issue and you will need to take it up elsewhere. I have no idea how LAN play is supposed to work with or without ldn_mitm.
