### ISSUE TITLE
[Controller request] AtGames Legends Pinball

### ISSUE THREAD

**Issue by jeremiz-github** [ndeadly/MissionControl#280]
The AtGames Legends Pinball can be connected to the Switch using wireless dock mode, and it appears as a Pro Controller.
But no button actually work.
Connecting the pinball to an Android phone work like a typical bluetooth controller.

**Comment by ndeadly** [comment]
Run [btdb](https://github.com/ndeadly/MissionControl/releases/download/v0.3.0/btdb.nro) and post a screenshot of the output so I can get the hardware ID of the controller.

Next run [hid_report_viewer](https://github.com/ndeadly/MissionControl/files/5539371/hid_report_viewer.zip) with no other bluetooth controllers connected and note down the changes to the numeric output on the screen as you press each button on the controller.

And lastly, since this is an unconventional controller, do you have any idea how would you map the available buttons to a standard controller layout? I'm guessing mapping the paddle buttons to the triggers on a controller would probably make sense.

**Comment by jeremiz-github** [comment]
Thanks for taking into account the issue. I will try what you said as soon as possible.
Flipper buttons should be mapped to the triggers, d-pad to either stick or d-pad, others to plus and minus, and A. I will report back when I have the time to try your suggestions!

**Comment by jeremiz-github** [comment]
So, I ran btdb, here is the result:
48:98:ca:bc:49:81 1d6b:0246 HA8819-04A70E
![1622663003214](https://user-images.githubusercontent.com/85137351/120543761-f7ade900-c3ec-11eb-9d4f-c03daeac224d.jpg)

hid_report_viewer run on 12.0.1, but when pressing buttons, nothing appears.
It is written HID REPORT VIEWER
NO REPORT DATA

For the control, based on Pinball FX3:
![pinball-screen-just-for-games-zoom](https://user-images.githubusercontent.com/85137351/120546979-c6cfb300-c3f0-11eb-91be-9153e2a6b642.jpg)

**Comment by ndeadly** [comment]
Cool thanks, that's a good start.

> hid_report_viewer run on 12.0.1, but when pressing buttons, nothing appears.
> It is written HID REPORT VIEWER
> NO REPORT DATA

Ok, I might need to update it. I'll get back to you when I've figured out what's up on 12.x.x

**Comment by ndeadly** [comment]
@jeremiz-github this one should work on 12.x.x

[hid_report_viewer_12.x.x.zip](https://github.com/ndeadly/MissionControl/files/6587611/hid_report_viewer_12.x.x.zip)

**Comment by jeremiz-github** [comment]
It works!
So:
No button press: 0000 | 01 00 00 00 00 08 80 80 80 80 80 00
Red Left Flipper button: 0000 | 01 00 04 00 00 08 80 80 80 80 80 00

**Comment by ndeadly** [comment]
Sorry for the wait, I've been busy the past few days. Let's see it I got all the controls correct...

[MissionControl-0.5.0-alpha.3-feature_atgames-legends-support-8297650.zip](https://github.com/ndeadly/MissionControl/files/6603342/MissionControl-0.5.0-alpha.3-feature_atgames-legends-support-8297650.zip)

**Comment by jeremiz-github** [comment]
Thanks a lot. It works.
However:
**Red Left Flipper button**: 0000 | 01 00 04 00 00 08 80 80 80 80 80 00 should be mapped to **ZL and L**
**Left Nudge button**: 0000 | 01 10 00 00 00 08 80 80 80 80 80 00 should be mapped to **Left stick to the right**
**Red Right Flipper button**: 0000 | 01 20 00 00 00 08 80 80 80 80 80 00 should be mapped to **ZR and R**
**Right Nudge button**: 0000 | 01 00 08 00 00 08 80 80 80 80 80 00 should be mapped to **Left stick to the left**
**Plunger from release to full pull**: 0000 | 01 00 00 00 00 08 80 80 80 80 80 00 (neutral) --> 0000 | 01 00 00 00 00 08 80 80 fe 80 80 00 (fully pulled) should be mapped to **neutral right stick to right stick down**

Everything else seems to works like it should (Dpad, plus etc...)
Again, thanks for your work, it is now possible to play pinball fx3 using the built in buttons!

**Comment by ndeadly** [comment]
How's this?

[MissionControl-0.5.0-alpha.3-feature_atgames-legends-support-19cfda9.zip](https://github.com/ndeadly/MissionControl/files/6604233/MissionControl-0.5.0-alpha.3-feature_atgames-legends-support-19cfda9.zip)

**Comment by jeremiz-github** [comment]
Almost flawless! 
Just the plunger does not do anything. Using hid report viewer it works, but it does nothing in game or in controller settings menus.

**Comment by ndeadly** [comment]
Ahh my bad. It's sent in the hid reports as what would normally be the x-axis of an analog stick, but I was using the y-axis instead. What about now?

[MissionControl-0.5.0-alpha.3-feature_atgames-legends-support-68decef.zip](https://github.com/ndeadly/MissionControl/files/6604268/MissionControl-0.5.0-alpha.3-feature_atgames-legends-support-68decef.zip)

**Comment by jeremiz-github** [comment]
Incredible! It works! I can pull the plunger and release it as it should!
I based the control with Pinball FX3 default control, maybe as a last request, the **Play front button**: 0000 | 01 80 00 00 00 08 80 80 80 80 80 00 should only be mapped to A and not to A AND X. And that's it. There is no more buttons left, but it is entirely playable! Thanks

**Comment by ndeadly** [comment]
[MissionControl-0.5.0-alpha.3-feature_atgames-legends-support-527b7fa.zip](https://github.com/ndeadly/MissionControl/files/6604322/MissionControl-0.5.0-alpha.3-feature_atgames-legends-support-527b7fa.zip)

**Comment by jeremiz-github** [comment]
Thanks you, I think we can close the case as it is working now :)

**Comment by SK360** [comment]
As @jeremiz-github only had the original DPad control panel when making this request the ABCXYZ buttons on the arcade control panel do not work.  I verified the joystick represents the same as the DPad however.

Is it possible to get support added for ABCXYZ? I have the HID report here.

A: 0000 | 01 00 01 00 00 08 80 80 80 80 80 00
B: 0000 | 01 04 00 00 00 08 80 80 80 80 80 00
C: 0000 | 01 00 20 00 00 08 80 80 80 80 80 00
X: 0000 | 01 40 00 00 00 08 80 80 80 80 80 00
Y: 0000 | 01 08 00 00 00 08 80 80 80 80 80 00
Z: 0000 | 01 00 10 00 00 08 80 80 80 80 80 00

Since I'm assuming there's no way to tell if a user has the control panel installed or not I don't think my preferred mapping would be possible (Switch home button where + is currently mapped). However perhaps mapping A, B, X, Y to the arcade buttons as well as the current buttons and then adding Minus and switch home to C/Z would make the most sense?

![IMG_8412](https://user-images.githubusercontent.com/6358878/210421546-b75d68a0-9f80-4f4e-94db-ebe43cee1a7f.jpg)

**Comment by SK360** [comment]
I opened a new request to get this mapping updated for the AtGames arcade control panel. #558
