### ISSUE TITLE
Add Bluetooth headset support?! (yes I read the FAQ)

### ISSUE THREAD

**Issue by weirdal3333** [ndeadly/MissionControl#282]
I've recently seen some stuff floating around on the internet on how Nintendo added bluetooth audio support in the 12.0.0 update, but haven't done anything with it. I think this should be looked into.

If you're just waiting for them to make Bluetooth headphones an official feature instead of adding it yourself, you can close this suggestion.

**Comment by parkerlreed** [comment]
Except this already exists... Why would a controller application add on the task of supporting audio?

https://github.com/plutooo/nx-btred

**Comment by ndeadly** [comment]
Yeah, the FAQ hasn't been updated to reflect the current state of things. As @parkerlreed  says, nx-btred already exists for this. While it's usable, it's still more of a proof of concept than anything. In particular, there are issues with Bluetooth audio introducing controller input delay. This may be a limitation of the system, rather than any fault of nx-btred and could be the reason Nintendo haven't actually activated the support for the end user. I suspect it might be something intended for the upcoming "switch pro" hardware revision. I'm not particularly interested in taking on the burden of supporting an entirely different class of device that doesn't have native OS support, especially when it impacts the performance of controllers. If Nintendo ever officially enable the feature I may change my stance, but at that point you probably won't need a homebrew application for anything unless they decide to restrict support to certain headsets.
