### ISSUE TITLE
/atmosphere/fatal_errors/report_0000000008d50a5f.bin

### ISSUE THREAD

**Issue by blackxithus** [ndeadly/MissionControl#284]
![191190005_506582043819289_8626620455786780933_n](https://user-images.githubusercontent.com/71927089/121225647-50352880-c8bc-11eb-8e1a-e7b83cb5a84e.jpg)

I'm on CFW 12.0.2 AMS 0.19.3 and whenever I transfer the files on atmosphere folder I get this error

**Comment by ndeadly** [comment]
This only happens when you've got an outdated sysmodule or atmosphere version. Since your firmware and atmosphere are up to date I'm guessing you grabbed the 0.4.1 release from December off the main github page. This is outdated, you need to click on [releases](https://github.com/ndeadly/MissionControl/releases) to see the [latest pre-release](https://github.com/ndeadly/MissionControl/releases/tag/v0.5.0-alpha.3) that works with the versions you listed above.

**Comment by blackxithus** [comment]
Oh wow that fixes it thank you! but now my dualshock 4 is not connecting, the bar just lights up with a color white and when I try to pair it nothing happpens.

**Comment by ndeadly** [comment]
Make sure you're following the [usage](https://github.com/ndeadly/MissionControl#usage) and [pairing](https://github.com/ndeadly/MissionControl#pairing-controllers) instructions.
Additionally, some Dualshock 4 controllers (particularly the v1 controller) can be a bit stubborn to get paired so you may have to keep trying until it succeeds. I've also heard resetting the controller may improve reliability.

**Comment by blackxithus** [comment]
Thank you so much for being responsive. I fixed the problem by using archive bit fixer from hekate and now it's working.

**Comment by ndeadly** [comment]
I don't think the archive bit fix can actually affect anything related to controllers, probably just coincidence. But good to know it's working for you now
