### ISSUE TITLE
missioncontrol.ini config location

### ISSUE THREAD

**Issue by pixeltester** [ndeadly/MissionControl#309]
Hi,

So I guess this is relatively minor but I'm just wondering why you use atmosphere configs location for missioncontrol.ini ?

The standard for homebrew would be SD/config/MissionControl/missioncontrol.ini

This aids in preserving configs if user wipes atmosphere folder for an update for example.

**Comment by ndeadly** [comment]
Firstly, the issue section is for reporting bugs or requesting features. Questions like this should be directed to the discussions section in the future.

To answer your question - I was not aware of there being any particular location considered "standard", but the rationale being that since mission control is an atmosphere extension module capable of causing system instability rather than a standard homebrew application that it might make sense that its config _was_ deleted along with the atmosphere folder to aid with troubleshooting. Much like the atmosphere config files, I consider the module config to be more of a power user thing for enabling/disabling components or features that should only be messed with by people who know what they're doing. Deleting the entire directory is a pretty heavy-handed solution and is rarely actually required anyway. It is often just suggested when things break after an update because it's an easy way to reset to a clean slate without having to trust that a user is following instructions correctly or has reported everything they might have installed/modified.

When controller profiles have been implemented, I will place these outside of the atmosphere directory for the reason you state above and they will be mostly managed by a standalone homebrew app. The settings for things like disabling rumble or motion controls will be moved there, leaving behind only the more advanced settings that the average user shouldn't need to touch.

**Comment by pixeltester** [comment]
Perhaps I worded the issue too casually for you but I believe this would be considered perfectly valid for github issues by most developer's definitions, however in the future I will of course respect your request to use the discussion section unless absolutely specifically a bug request or a feature request.

This I believe is the first time a third party config has ever been placed in atmosphere config directories, MissionControl is a third party extension and not part of atmosphere as far as I'm aware so really has no business being in the atmosphere config directory in any capacity.

**Comment by ndeadly** [comment]
> Perhaps I worded the issue too casually for you but I believe this would be considered perfectly valid for github issues by most developer's definitions, however in the future I will of course respect your request to use the discussion section unless absolutely specifically a bug request or a feature request.

If your intent is to suggest I move the config, then sure it's perfectly acceptable to have it here. It just read as more of a question of curiosity.

> This I believe is the first time a third party config has ever been placed in atmosphere config directories, MissionControl is a third party extension and not part of atmosphere as far as I'm aware so really has no business being in the atmosphere config directory in any capacity.

Probably, I couldn't find that many examples of config files being used in general. Do you have any specific homebrew in mind as an example? All third party sysmodules and other mods/patches etc are also installed into subdirectories under the `atmosphere` directory. You could use the same logic to argue that those don't belong in there either, but those are the official locations.

I am not particularly attached to the location in any case, it just made the most sense in my mind. I'll ask for opinions amongst the atmosphere devs and if they disagree with my choice I'll change it.

**Comment by pixeltester** [comment]
> 
> If your intent is to suggest I move the config, then sure it's perfectly acceptable to have it here. It just read as more of a question of curiosity.
> 

That was my intent, sorry if I wasn't clear to begin with.
> 
> Probably, I couldn't find that many examples of config files being used in general. Do you have any specific homebrew in mind as an example?
> 

- nx-hbmenu
- NX-Activity-Log
- TriPlayer
- Tesla
- sys-clk
- sys-con
- sys-ftpd
- SimpleModManager

There are also some homebrew that use their own folder within SD/switch and a few others that use arbitrary locations. MissionControl is the first to use the atmosphere config location.

**Comment by ndeadly** [comment]
So the consensus seems to be: there is no agreed upon standard location for config files, but the location you mentioned is maybe the most common; SciresM doesn't care that I use the atmosphere config folder. but said it probably doesn't really belong in there.

I guess I can consider changing it for the next release.

**Comment by ndeadly** [comment]
.ini location has been changed in the new 0.5.0 release
