### ISSUE TITLE
Crash when pairing first generation DS4

### ISSUE THREAD

**Issue by zestian56** [ndeadly/MissionControl#31]
Hello when i try to pair the first generation DS4, atmosphere instantly crashes (On the pair controller screen)

It works great with the last generation DS4, it's only failing on first generation

**Comment by ndeadly** [comment]
I've had several reports of problems with the DS4 v1 now. Seems it's behaving strangely. Try resetting the controller and see if it makes any difference.

Failing that, install this build with logging enabled and post the `btdrv-mitm.log` file it makes on your SD root. The log is wiped on console boot, so if your Switch crashes, make sure you grab the log before allowing it to boot back into HOS

[MissionControl-0.1.0-debug-logging.zip](https://github.com/ndeadly/MissionControl/files/5146287/MissionControl-0.1.0-debug-logging.zip)

**Comment by ndeadly** [comment]
@zestian56 giving it some more thought, it's possible that your issue could be caused by one of the battery level bugs other users have reported (#9 #18 )

Give this build a try and see if it makes any difference.

[MissionControl-0.1.0-ds4-battery-fix.zip](https://github.com/ndeadly/MissionControl/files/5158494/MissionControl-0.1.0-ds4-battery-fix.zip)

**Comment by zestian56** [comment]
Hello, Thanks for your answer... it doesn't crash, but it's not being recognized either... it just keeps blinking all the time

**Comment by ndeadly** [comment]
So just to be clear, while this hasn't solved your pairing issue, it has stopped the crash?

It's starting to sound like the DS4 v1 Bluetooth is a little flakey. I had another user complain of similar issues here #12. He was able to pair the controller eventually after multiple attempts, so it might be worth trying some more. Also, double check you are actually entering pairing mode correctly. On the v2 at least, the flashing resembles a heartbeat when it's in pairing mode, but just flashes on and off at regular intervals otherwise. I assume you already know this sounds you paired your v2, but it did take me a while to notice the flash patterns are actually different .

You should still try to make a log with the previous build I posted. Might help shed some light on the issue._

**Comment by ndeadly** [comment]
Thanks for the update. I think that once you get it to pair everything should be good. I'm still curious why it's taking so many tries to pair the v1 though. If you don't mind, could you make a log of the pairing process with this new build with extended logging of the pairing process enabled? This will help me understand what's going wrong and if there's anything I can do about it.

[MissionControl-0.1.0-debug-logging2.zip](https://github.com/ndeadly/MissionControl/files/5163793/MissionControl-0.1.0-debug-logging2.zip)

**Comment by zestian56** [comment]
[btdrv-mitm.log](https://github.com/ndeadly/MissionControl/files/5165540/btdrv-mitm.log)
This is the log... it never paired up

**Comment by ndeadly** [comment]
That log doesn't show any device discovery events at all. Even if the controller didn't work, I would expect to see events in there just  from entering the pairing menu. As mentioned earlier, the log gets wiped and starts over on reboot. Could this be what has happened?

**Comment by zestian56** [comment]
Does reboot counts in hekate payload? since i took the log then went to hekate and copied the file

**Comment by ndeadly** [comment]
No that's fine as long as you don't let it boot back into HOS.
