### ISSUE TITLE
Older Wii controller (RVL-003) fails to connect, but it looks like the switch tries to connect

### ISSUE THREAD

**Issue by weirdal3333** [ndeadly/MissionControl#311]
When connecting to the Wii controller, I can tell that it's trying to connect to the controller, but the pairing fails. This happens about 4 times before the red button cycle runs out. I have attached logs from the debug alpa build 0.5.0-alpha.3-debug-log-3171270, but if a newer debug version is available I can use that.
[bluetooth-mitm.log](https://github.com/ndeadly/MissionControl/files/6795474/bluetooth-mitm.log)

**Comment by ndeadly** [comment]
Wii controller pairing has been broken since 12.0.0. It's not mission control's fault, but something that changed in the bluetooth module that causes controllers using legacy pincode pairing to no longer be accepted. The controllers are actually paired successfully, but the firmware doesn't store their details to the database or attempt to open a connection to them afterwards. I am actively looking into it.

Closing because there are several existing issues tracking this

**Comment by weirdal3333** [comment]
Oh ok I wasn't sure if it was fixed in the latest build or not...
Couldn't we roll back to the older Bluetooth module, or would that break things?

**Comment by ndeadly** [comment]
Nah, if you read the release notes you'll see I mentioned it was the last thing outstanding before I make the final 0.5.0 release.

> Couldn't we roll back to the older Bluetooth module, or would that break things?

It would break things. Some of the IPC commands changed in 12.0.0, so anything that calls them will send the wrong thing which will likely result in a crash.

All that said, tonight has proven productive. Unzip this to your SD card ;)
[enjoy.zip](https://github.com/ndeadly/MissionControl/files/6796081/enjoy.zip)

**Comment by weirdal3333** [comment]
Alright, so it worked... EXTREMELY WELL!
Also, a neat side effect, a few different counterfeit Wii controllers work with this! What did you change?
All of the buttons work too. Not sure if the gyro works, as I don't have any games to test it. Remapping the buttons from the Wii menu works.

**Comment by ndeadly** [comment]
> What did you change?
I had to patch in some code that was missing from the code path that handles legacy pincode pairing, and then detour to it. 12.0.0 introduced some kind of temporary database slot that is then used to copy the details of a successfully paired controller into the database and open an hid connection to the controller. Controllers that use the newer SSP pairing method had code that copies them into this slot, but that was missing for legacy pairing (presumably because no official Switch controller uses it) so even though the pairing was successful these controllers weren't being written to that slot so never got added to the database.

> All of the buttons work too. Not sure if the gyro works, as I don't have any games to test it. Remapping the buttons from the Wii menu works.

It was only the pairing that was broken, the rest of the functionality comes from mission control and is exactly the same as it was before so none of this is any surprise. Gyro support hasn't been added yet so you don't need to waste your time testing for it.

**Comment by weirdal3333** [comment]
Well, thanks for fixing it! Might I suggest having a toggle in the settings file to enable logs on any version?
 It would make it way easier to debug if you could just have someone change a 0 to a 1 and reboot to make the Bluetooth log appear. I also think that the flag should be disabled after 5 minutes so the log isn't wiped on boot, and so you have enough logs to work with.

**Comment by ndeadly** [comment]
Yeah, this might be a good idea for some of the core bluetooth stuff like pairing. I wouldn't put it in any "hot" paths that process inputs though. I'll consider adding it to the next release.

If logging were something that could be disabled, I'd probably just make it create a new timestamped log on each boot.
