### ISSUE TITLE
[request] Audio hook for wireless controllers

### ISSUE THREAD

**Issue by weirdal3333** [ndeadly/MissionControl#312]
Many wireless controllers have Audio ports or speakers in them, including Xbox, PlayStation, Wii, and even the stadia controller!

I'm sure that putting this in will be difficult, and we may need someone to develop open source switch drivers first, so this request should go to the absolute bottom of your Todo list.

You might want to ask plutooo to work together on this if you ever get to it,since he's the guy who's developing nx-btred.

**Comment by ndeadly** [comment]
I very much doubt there's anyone with the time or motivation to reimplement an open source bluetooth driver. It's a _lot_ of work. It might not actually be required though, since we now have bluetooth audio functions as of firmware 12.0.0. 

I don't know whether these controllers do audio via standard bluetooth audio or whether they stream it via their own proprietary protocols, but it should be noted that running `nx-btred` has performance impacts on bluetooth controllers. This is something that may very well be a limitation of the current switch hardware, and may be the reason why Nintendo hasn't officially enabled support for it. I'm not sure I want to introduce something that degrades controller performance as a core part of my module.

Then there's the question of things like how to go about selecting controllers to output audio to, volume control etc that isn't supported by the OS in any way. All in all I think it's just way too high effort for too little benefit. People that want wireless audio can just use nx-btred

> You might want to ask plutooo to work together on this if you ever get to it,since he's the guy who's developing nx-btred.

Yeah, I helped plutooo with questions he had when writing nx-btred. I don't think he has much interest in continuing beyond proving it could be done though.
