### ISSUE TITLE
Control sticks calibration 

### ISSUE THREAD

**Issue by Asdsas123** [ndeadly/MissionControl#324]
So i have slight drift on my Wii u pro controller left stick, after calibration the stick on switch works fine but after reconnecting the controller it goes back to default and have to recalibrate every time that i connect the controller, is there a possible way that you could make the calibration saves or anything that helps.
appreciate your cooperation.

**Comment by ndeadly** [comment]
Oh interesting, you can actually complete the calibration now? It used to be the case that it would just generate an error dialog if you tried to do it on an unofficial controller.

I've been thinking about how to handle this problem recently actually. Since I made the improvements to analog stick accuracy in the latest release I get the impression that the stick drift has become a little more pronounced on the Wii U controller, making a means to calibrate more necessary.

It's definitely possible to intercept and store this data, it's more a question of how to do it. Official controllers have an onboard SPI flash memory that the calibration data gets read from/written to. I currently just ignore/fake these operations for the important things, but maybe now it's the time to consider redirecting all read/write commands to a file on the SD card.

**Comment by ndeadly** [comment]
Calibrations can now be stored and retrieved with the latest release https://github.com/ndeadly/MissionControl/releases/tag/v0.5.1
