### ISSUE TITLE
AfterGlow WiiU Pro Controller

### ISSUE THREAD

**Issue by JinxDojo** [ndeadly/MissionControl#327]
I have tried my WiiU AfterGlow Pro Controller with two combinations: Atmosphere 0.18.1 with MissionControl 0.4.1; and Atmosphere 0.19.5 with Mission Control 0.5.0. Neither seem to enable it to pair.

I am not familiar with how to discover the "VID/PID". Is there a simple way to do so?

**Comment by ndeadly** [comment]
Are you trying to pair from the correct menu (`Change Grip/Order`)? Keep in mind that some third party WiiU controllers seem to be fundamentally incompatible with the Switch bluetooth hardware, and it doesn't seem the console even attempts to pair with them. If your controller falls into this category there isn't a lot that I can do unfortunately, unless someone were to donate me a controller to investigate why it doesn't work with a debugger.

You could try logging your pairing attempts with [this debug build](https://github.com/ndeadly/MissionControl/files/6826165/MissionControl-0.5.0-dbg-21c541d.zip). It will make a log at `sdmc:/bluetooth-mitm.log` that you should post here, This should make it clear whether the switch is actually trying to pair with your controller or not. 

VID/PID can be found using my [btdb](https://github.com/ndeadly/MissionControl/releases/download/v0.3.0/btdb.nro) homebrew app after pairing has succeeded. In your case it's unlikely that you need it though because WiiU controllers are already supported. Even unsupported controllers should still pair, the VID/PID is just used to identify the controller type in order to map the buttons correctly.

**Comment by JinxDojo** [comment]
Thank you for the prompt reply, ndeadly! I really appreciate your work on this software.

I am waiting to pair on the "Change Grip/Order" menu as the instructions say. Nothing happens. I'm happy to try a debug build if that might help--though I just reverted to Atmosphere 0.18.5--is there a debug version that will work for that? Or does that lose too many of your recent additions and make it even less likely to support this particular controller?

(I wish I had known this sort of thing might be possible last year--I would have happily bought you an AfterGlow back when they were <=$15 new! Now they seem to be >$30 even for used ones! Sadly, these days I can't even afford to buy myself a new controller--hence why I'm trying to use this WiiU one on Switch!)

**Comment by ndeadly** [comment]
> though I just reverted to Atmosphere 0.18.5--is there a debug version that will work for that?

What's your reasoning for using an outdated Atmosphere version? It's completely backwards compatible with older firmwares. The only valid reason I can think of would be some homebrew you rely on that hasn't been updated in a long time and doesn't work with latest. Not only are you denying yourself the stability and features of the latest Atmosphere releases, but you're also unable to use any libstratosphere homebrew like Mission Control that was compiled for the latest version. I have made quite a few improvements in 0.5.0 that I wouldn't really recommend using 0.4.1 anymore. It was also [suggested to me](https://github.com/ndeadly/MissionControl/issues/311#issuecomment-877716748) that some combination of version 0.5.0 changes and firmware 12.x.x  may have improved compatibility for some third party WiiU controllers (though I'm not sure whether the user was implying they didn't work before, or he just didn't expect them to work without further changes)

If you really insist on sticking with the older Atmosphere and 0.4.1, there's probably a debug build for it posted somewhere in the issue tracker that I could dig up.

> (I wish I had known this sort of thing might be possible last year--I would have happily bought you an AfterGlow back when they were <=$15 new! Now they seem to be >$30 even for used ones! Sadly, these days I can't even afford to buy myself a new controller--hence why I'm trying to use this WiiU one on Switch!)

It's all good. I can't promise having access to the controller would even lead to support anyway, it's just the only way there's any chance of progress at all if we don't see any attempts at pairing from the Switch software itself (there may still be activity within the bluetooth stack). If it's actually an incompatibility at the hardware level then it's likely a lost cause.

**Comment by JinxDojo** [comment]
My reasoning is that, far more often than not, fussing with something that's working well leads to it not working at all. I realize "YMMV", but my experience has taught me this lesson repeatedly over the years. (This same case happened when I tried to update to Atmosphere 0.19.5; "just extract the zip and overwrite" was the advice I received. Well, the advice failed and all my games refused to load--at a very inopportune time as well. Apparently, the advice neglected to inform me of another critical step in the process.)

Having said that, I'm willing to try again if you feel it will help. I'm still on FW 10.1 though (with no intent to change unless I'm unable to adapt/edit e.g. Skyward Sword to run on 10.1), so I don't know that I'd benefit at all. But if it helps get the controller supported (even if not for me / my versions), I'll try again. Please let me know if that's what you think is best.

I understand that it's possible the hardware simply won't be compatible. Hopefully we'll find out one way or the other!

(By the way: I second the suggestion in #311 to have a "Debug=1" toggle in an INI or text file for future versions.  :) )

Thanks again for not only writing this code initially, but also keeping up an effort to support more controllers. I do appreciate it!

**Comment by Masamune3210** [comment]
There are almost 0 reasons that just copying over the latest atmos release and overwriting files would stop working unless you are doing something that is unsupported. Atmosphere needs to be kept at latest if you want homebrew, and especially services like missioncontrol to work correctly, latest firmware also is usually a good idea for things that deeply interact with the firmware like this

**Comment by ndeadly** [comment]
Well, the instructions on updating Atmosphere were not wrong. I won't continue that discussion here, but there are certain things you're always going to have to make sure you update when updating atmosphere versions, Mission Control included. Usually this is not a huge problem so long as you wait a few days for other devs to update their stuff following the new Atmosphere release. Avoiding updating rather than learning what else you might need to update at the same time seems a bit silly to me, but that's your perogative.

For now you could try this [0.4.1 debug build](https://github.com/ndeadly/MissionControl/files/5951865/MissionControl-0.4.1-fake-tsi-response.zip) if you want, but it would be ideal if you could use the 0.5.0 build, as I can't say for sure whether the ones floating about the issues tracker log all the parts of interest. A lot of those builds were made to log for specific problems.

> (By the way: I second the suggestion in #311 to have a "Debug=1" toggle in an INI or text file for future versions. :) )

I will consider adding some basic general logging in the future, though I think it has limited utility at this stage of development as most problems require more problem-specific logging anyway

**Comment by JinxDojo** [comment]
Thank you again for the reply, ndeadly. I appreciate your attitude and being willing to help even if you view my desire to avoid unnecessary updates as "silly." :)  (I understand and agree that it's important to learn/understand what one is doing--and I do know what I failed to update along with Atmosphere--but the nature of the update process failing without any clear course of action is my inevitable complaint regarding most sorts of updates from all fields; the complication for anything but the most standard usage creates a new sort of "one-size-fits-all" model of software development--though we need not go on about that here, I suppose.)

I will give the 0.4.1 debug build a try when I'm next able, and report the results here. If that doesn't glean anything, I'll try updating Atmosphere (and MissionControl) again and give the 0.5.0 debug build a shot. Thank you again!
