### ISSUE TITLE
WiiU Pro Controller analog sticks are centered incorrectly since 8ece58d151d2ad17b7a84ceb264a26cff643f299

### ISSUE THREAD

**Issue by AuroraWright** [ndeadly/MissionControl#331]
I noticed while playing a game requiring precise left analog stick movement that there was a small "drift" on my WiiU Pro controller. After checking in HOS settings, it seems the issue is present using both sticks. I remembered the issue not being there in the past so I bisected it to this commit https://github.com/ndeadly/MissionControl/commit/8ece58d151d2ad17b7a84ceb264a26cff643f299, more specifically it seems the data here https://github.com/ndeadly/MissionControl/commit/8ece58d151d2ad17b7a84ceb264a26cff643f299#diff-50f122326108a8eeedeb95280398b6bc77f15631b00391b789e7b9c9f1f9fc3eR24-R27 is causing the issue (if I 0xFF all of it sticks are properly working again).
I uploaded a short video of the issue here: https://youtu.be/SgQkVTONslY (I show both sticks).
Feel free to ping me on Discord if you need testing on any kind.

**Comment by Banz99** [comment]
I'll write this on behalf of Ndeadly: that 0xFF initialization was only a placeholder and probably forced the switch itself to use a default calibration that was working better for you than the valid calibration data that is now being passed. The solution here should be to use the built in calibration tool on the switch settings (that now seems to work when passing valid data), with the only downside being that it can't be saved for now and needs to be redone at each controller connection (see #324). In case even that doesn't fix it, there'll be an option for custom deadzones in the future.

**Comment by AuroraWright** [comment]
Thanks for clarifying, I can confirm calibration fixes it, I then hacked away at the code a bit and managed to dump the user calibration values, it seems for the left analog stick a single byte is written to 0x8010 of the flash, and another byte at 0x801B for the right analog. In my WiiU Pro Controller's case, both sticks are exactly 0xB2 so it's possible the default is controller-specific.

**Comment by bibliophilical** [comment]
I notice the drift on my Wii U Pro Controller too on the latest update that was not present before.

**Comment by ndeadly** [comment]
I aready spoke with @AuroraWright on discord regarding the issue, but I'll leave this here for the sake of others.

As @Banz99 has said above, prior to mission control v0.5.0 all requests for SPI flash reads from the controller (besides the one for controller colours) were being responded to with blocks of `0xff`, which corresponds to uninitialised flash memory. The console accepts this without issue and everything seemed more or less fine. It seems that a default calibration gets applied, and I had just chosen an arbitrary scaling factor of 1.5 for the WiiU Pro controller that seemed to work well to map the stick values to the range used by the Switch.

In v0.5.0 we now pass valid analog stick calibration data corresponding to a stick that utilises the entire 12-bit range used by the Switch. This fixes an issue that was present for _all_ controllers where the sticks were maxing out too soon due to the default calibration. I have noticed the issue reported here with my own WiiU Pro controllers, and I think one of two things is happening -either the improved accuracy has exposed an issue that was always present but was minimised by my scaling factor being lower than it should have been, or that in passing a valid calibration the console is now expecting to read valid deadzone information from SPI flash also, and since we don't provide it, is no longer applying the inner deadzone that would have corrected for the off-center stick values.

A fortunate side-effect of passing the valid calibration data is that now the user calibration for the analog sticks in the Switch settings menu can be completed for unofficial controllers. This can (and should) be used to calibrate the sticks of the WiiU Pro controller, because unlike Switch controllers, they don't store any calibration information for the analog sticks. The calibration works great, but the only issue is it can't be stored on unofficial controllers and must be done every time the controller is connected.

A week or two ago (in response to https://github.com/ndeadly/MissionControl/issues/324) I implemented something I've been meaning to do for a while - a virtual SPI flash system to redirect the reads/writes to a file on the SD card for each unofficial controller. This allows the calibration to be stored and retrieved just like a real Switch controller, and should allow for anything else that tries to write to the controller memory (besides firmware updates, obviously) to function correctly. It has not been merged yet due to some additional decision making/code cleanup that needs to be done, but is fully functional for anyone interested who is capable of compiling for themselves. You can find it here https://github.com/ndeadly/MissionControl/tree/virtual-spi-flash

**Comment by ndeadly** [comment]
This is now implemented in the latest release https://github.com/ndeadly/MissionControl/releases/tag/v0.5.1
