### ISSUE TITLE
[Request] Gamecube Triggers

### ISSUE THREAD

**Issue by LeafStorm14** [ndeadly/MissionControl#333]
Is it possible to have the Gamcube controller's analog triggers activate halfway into pressing down? I'd like to not have to press down all the way until the trigger "clicks" to get an input.

I'm using an adapter for the Wiimote that allows me to emulate a Gamecube controller as a Wii Classic controller.

**Comment by ndeadly** [comment]
It should be possible. The Classic controller format sends both an analog and digital value for the triggers. Currently I only consider the digital value, which I think works fine for the classic controller but I guess your adapter maps this value to the button click at the end of the gamecube trigger.

Leave it with me to decode the [stupid format](http://wiibrew.org/wiki/Wiimote/Extension_Controllers/Classic_Controller) that the trigger values are packed into and I'll get back to you with a build to test out.

**Comment by ndeadly** [comment]
Try this and see if I got the triggers correct.

[MissionControl-0.5.0-wii-classic-triggers-72951f6.zip](https://github.com/ndeadly/MissionControl/files/6992627/MissionControl-0.5.0-wii-classic-triggers-72951f6.zip)

**Comment by LeafStorm14** [comment]
The function of having analog trigger input works, but there are some issues I'm having.

-The analog triggers input as ZL and ZR with the "click" press of the digital button as L and R. Some games let the L,R buttons override the ZL,ZR analog triggers and some don't
-Physical ZL and ZR buttons have lost their functionality

If you could, have both analog and digital triggers be mapped to L,R with the ZL,ZR buttons still intact as it was beforehand. If both analog and digital triggers can't be mapped as the same input, it's fine to remove the digital press and just have the analog triggers mapped to L,R.

**Comment by ndeadly** [comment]
Sorry if I'm not understanding this correctly, you're saying the changes I made for the triggers are working correctly as the ZL/ZR buttons but you want the click to be mapped as L/R? I guess this would make sense in the context of the gamecube controller where there is no ZL/ZR. Your original post sounded like you just wanted it changed to trigger at 50% pressed instead of 100%.

While it's possble to make a build that will do what you describe, I can't really make changes to the public code that alter the current mappings as this will break the behaviour of actual Wii Classic controllers since we have no way to differentiate them from your gamecube controller pretending to be one via the adapter.

**Comment by LeafStorm14** [comment]
Here's a [demonstration](https://www.youtube.com/watch?v=DlX8jMNSUsU) on the mapping problem I said. 

The Gamecube controller with the official usb adapter functions with 100% press as L,R, but with 50% press as nothing. Upon research, this should be the same case with the Wii Classic controller as that controller has analog triggers too. If the 100% press could be changed to 50% press, I don't think that would break the behavior for the Wii Classic controller; it would just lessen the travel time for the triggers to activate.

**Comment by ndeadly** [comment]
I'm still confused about what you're trying to explain. When you write L/R can you clarify which controller/mapping you're actually referring to (gamecube, wii classic or switch), and similarly with the trigger press (do you mean 100% of the analog travel before the button click, or the click itself)

In the video it looks to me like L/R (gamecube button) is mapped to L/R (switch) and L/R (gamecube trigger @ 100%) is mapped to ZL/ZR (switch). My current release for the wii classic controller maps L/R (wii classic) -> L/R (switch) and ZL/ZR (wii classic button) -> ZL/ZR (switch) and ignores the analog data. In the build I posted above I changed it to use ZL/ZR (wii classic trigger @ 50%) instead. From what I understand, your adapters are treating the analog vs digital data as separate buttons in order to allow for L/R and Z/L (wii classic) to be pressed when the gamecube only has Z/L. In order for me to use the analog data instead it would appear I'm effectively switching these two buttons that your adapter has mapped. In order to fix this to behave as you expect I would have to switch the L/R and ZL/ZR mappings for the wii classic controller, and since it can't be done conditionally this would cause the position of these buttons to be switched with respect to a switch pro controller for anyone using an actual wii classic controller.

**Comment by LeafStorm14** [comment]
When I write L/R, it's referring to the input that shows up in the button test and to the shoulder buttons for all controllers that have L/R written on their button. To restate the goal I have in mind, it's to use the Gamecube controller's analog L/R @ 50% pressed as the Switch's digital L/R.

I've done some testing and I don't think this is a Gamecube controller issue; it's a Wii Classic controller issue. The build you posted earlier does change the inputs for the Wii Classic controller as well. So moving forward, I'll only talk about the Wii Classic controller.

Going back to talk about the current release, I think you made the Wii Classic controller's ZL/ZR ignore analog, but haven't done so with L/R too. L/R on the Wii Classic controller also has analog input.

Scrapping all the theory crafting at this point, could you make a build to ignore analog data from the Wii Classic controller's L/R? This build being without the changes from the one you posted earlier.

**Comment by ndeadly** [comment]
Ahhh I see the issue. I assumed Zl/ZR were the analog triggers because of how they're placed on the wii classic/wiiu pro controllers, but looking at that documentation I linked earlier I see it's actually L/R that are analog on the wii classic controller. This makes your initial observations make a lot more sense.

See if this works now. This should also be compatible with the public code.
[MissionControl-0.5.0-wii-classic-triggers-df179f0.zip](https://github.com/ndeadly/MissionControl/files/6994767/MissionControl-0.5.0-wii-classic-triggers-df179f0.zip)

**Comment by LeafStorm14** [comment]
Yep! That's it! Works perfectly now! My Gamecube adapter also works the same way a Wii Classic controller should now too.

**Comment by ndeadly** [comment]
Nice. I'll merge this then and it will be included with the next release

**Comment by LeafStorm14** [comment]
Awesome. Glad to be part of a small fix. Closing now.
