### ISSUE TITLE
Gamesir T1 connection

### ISSUE THREAD

**Issue by TheRealBorak** [ndeadly/MissionControl#337]
The gamesir t1 controller connected the first time I tried to connect it, now it won't connect again (no matter which connection mode i use).

**Comment by ndeadly** [comment]
Not sure why this would happen. Once the controller has paired you should be able to just wake it up and it will reconnect to the console. I don't think the mode matters when just waking it up (though I could be wrong, never used these controller before). Does the controller have a reset button? If so you could try pressing that. Otherwise, wiping the pairing database with the `Disconnect Controllers` option in the controller settings menu might help.

**Comment by TheRealBorak** [comment]
I tried reconnecting it after writing the post and now it just works. I guess my controller is just faulty (it's pretty old). Sorry for bothering you. I also want to thank you for such a great app.
