### ISSUE TITLE
[Bug Report]: btdb.nro crash

### ISSUE THREAD

**Issue by lowburger** [ndeadly/MissionControl#349]
### Switch Firmware Version

12.1.0 (Latest)

### Atmosphère Version

1.0.0 (Latest)

### Mission Control Version

0.5.1 (Latest)

### Boot Method

Fusée

### Issue Description

Hi. My version not listed in issue template so far but I will tell it's switch version 13.0.0 and atmosphere 1.1.0

I understand mission control need update for new atmosphere but I report that btdb.nro crashes when open in this versions. As I see it's not attach with latest releases but it's still working on last atmosphere and firmware version.

You can fix and do new btdb release for latest versions or this homebrew not suppported any longer? Thx.

**Comment by ndeadly** [comment]
btdb is mostly a tool for aiding me in supporting new controllers, so is not really neccesary for the end user except in cases someone has an unsupported controller to report. Since having it as part of the releases confused many users, and the people I actually needed to use it rarely downloaded it without being instructed I stopped bothering adding it to new releases. That said, I wasn't aware of anything that should have broken it. I will look into it. Thanks for the report :)

**Comment by RafaelDiasCampos** [comment]
In my case, atmosphere doesn't boot with the sysmodule installed. I had to remove it in order to load into firmware 13.0.0 with atmosphere 1.1.0.

**Comment by ndeadly** [comment]
@RafaelDiasCampos yes, this is expected after a major update, as @lowburger has acknowledged above.

I wasn't home last night when the Atmosphere update released so haven't had a chance to create an update to support 13.0.0 yet. This may happen later today, or could take several days  or longer depending on how much was changed in 13.0.0

**Comment by ndeadly** [comment]
Here's a version of `btdb` updated for the commands that changed in 13.0.0 for anyone who needs it. I probably won't include it with the official release for 13.0.0 support as the app has always been a bit of a messy hack. I'd prefer to include its functionality when I get to writing a proper companion applet for mission control.

Please let me know if there are any issues encountered with it, as I did the bare minimum to make it run again :p
[btdb-1300.zip](https://github.com/ndeadly/MissionControl/files/7227157/btdb-1300.zip)
