### ISSUE TITLE
CTR Nitro Fueled, while i am playing, the DS4 controller keep rumbling every time [Bug Report]: 

### ISSUE THREAD

**Issue by Tiwan010203** [ndeadly/MissionControl#354]
### Switch Firmware Version

12.1.0 (Latest)

### Atmosphère Version

0.20.1

### Mission Control Version

0.5.1 (Latest)

### Boot Method

Hekate

### Issue Description

I am using nintendo switch lite. While i am playing CTR nitro fueled on it, my ds4 controller keep rumbling every time. I tried to play another game like Fifa 21, it didn't rumbling like i played CTR. I am using firmware 12.1.0 | AMS M.20.1 | E, hekate v5.57

**Comment by kabir0000** [comment]
Facing similar issue only for FE3H (As far as I have seen) on my Dualsense controller. 
Firmware and Mission Control version same as above, using Atmosphere 1.0.0

**Comment by ndeadly** [comment]
This likely depends on how a particular game implements rumble. Switch controllers will vibrate for about 10ms after receiving a rumble packet before shutting off by themselves. Usually, there wil be a "neutral" packet sent to stop the vibration anyway, but it seems in some cases this doesn't happen.

Other controllers such as the DS4 will vibrate for several seconds from a single packet. Not a big deal for a Switch controller, as you're not going to notice a 10ms difference, but for controllers like the DS4 this will cause it to ring out for several seconds. This is an even bigger problem for Wii controllers, that won't switch off their rumble at all until the neutral packet is received. If your controller appears to vibrate non-stop, it might be that the game is sending pulses of rumble commands with no terminating neutral packets. 

I guess the solution would be to have some kind of watchdog thread checking if some time has passed since the last rumble packet was received for each controller. I will look into it when I have time. This is not super high priority for me at the moment.

**Comment by impeeza** [comment]
> This likely depends on how a particular game implements rumble. Switch controllers will vibrate for about 10ms after receiving a rumble packet before shutting off by themselves. Usually, there wil be a "neutral" packet sent to stop the vibration anyway, but it seems in some cases this doesn't happen.
> 
> Other controllers such as the DS4 will vibrate for several seconds from a single packet. Not a big deal for a Switch controller, as you're not going to notice a 10ms difference, but for controllers like the DS4 this will cause it to ring out for several seconds. This is an even bigger problem for Wii controllers, that won't switch off their rumble at all until the neutral packet is received. If your controller appears to vibrate non-stop, it might be that the game is sending pulses of rumble commands with no terminating neutral packets.
> 
> I guess the solution would be to have some kind of watchdog thread checking if some time has passed since the last rumble packet was received for each controller. I will look into it when I have time. This is not super high priority for me at the moment.

Great work @ndeadly   thanks for all your efforts

**Comment by detuur** [comment]
> 
> 
> This likely depends on how a particular game implements rumble. Switch controllers will vibrate for about 10ms after receiving a rumble packet before shutting off by themselves. Usually, there wil be a "neutral" packet sent to stop the vibration anyway, but it seems in some cases this doesn't happen.
> 
> Other controllers such as the DS4 will vibrate for several seconds from a single packet. Not a big deal for a Switch controller, as you're not going to notice a 10ms difference, but for controllers like the DS4 this will cause it to ring out for several seconds. This is an even bigger problem for Wii controllers, that won't switch off their rumble at all until the neutral packet is received. If your controller appears to vibrate non-stop, it might be that the game is sending pulses of rumble commands with no terminating neutral packets.
> 
> I guess the solution would be to have some kind of watchdog thread checking if some time has passed since the last rumble packet was received for each controller. I will look into it when I have time. This is not super high priority for me at the moment.

This is not the situation here, I'm assuming. I'm getting random rumbles as well in FE3H with a DualSense controller, and these are entirely random rumbles, turning on and off randomly dozens of times per second, constantly. This happens from the second the game is started, even on the initial loading screen. There should be no rumble commands being sent at loading screens.

My completely wild guess is that these games might be sending "keepalive" rumble commands, with nonzero values that are below the Switch controllers' threshold. Passing these values through unmolested to DS controllers causes them to rumble because their thresholds are different.

**Comment by ndeadly** [comment]
Hey guys, I came up with a potential fix for this issue. Please see my response in this issue https://github.com/ndeadly/MissionControl/issues/325#issuecomment-959785469, try out the build and let me know how it's working for you.

**Comment by ndeadly** [comment]
This should be resolved now with v0.6.2
