### ISSUE TITLE
[Bug Report]: MissionControl 0.6.2 crashes on bootup on HOS 13.2.0 / AMS 1.2.5

### ISSUE THREAD

**Issue by malSet** [ndeadly/MissionControl#398]
### Switch Firmware Version

Other (please specify in issue description)

### Atmosphère Version

Other (please specify in issue description)

### Mission Control Version

0.6.2 (Latest)

### Boot Method

Hekate

### Issue Description

HOS Version: 13.2.0
AMS Version: 1.2.5

Crashes the system at the Switch logo on bootup. Likely a HOS issue, as my emunand, which is on 13.1.0, still works fine even with AMS 1.2.5.

### Error Report

Panic occurred while running Atmosphere.

Title ID: 010000000000bd00
Error: std::abort (0xFFE)

Report saved to /atmosphere/fatal_errors/report_092655a4.bin

### Additional Context

Here's the crash report. No idea if its useful to you or not, but I might as well include it for comprehensiveness.

[report_092655a4.bin.zip](https://github.com/ndeadly/MissionControl/files/7630421/report_092655a4.bin.zip)

**Comment by lowburger** [comment]
Yes I have the issue. I think 13.2.0 update has nothing which cause problem for MissionControl and just need new atmosphere library.

**Comment by ndeadly** [comment]
The problem is not caused by 13.2.0 directly, but since this is a bump to the firmware minor version Atmosphere will throw a fatal error when it sees a sysmodule using an older version of libstratosphere on the assumption that these updates can break API compatibility. All that is required is recompilation with the latest libstratosphere. 

I thought we were done with these kind of updates, but according to SciresM this behaviour is intended, and only bumps to the micro version number can be assumed not to break support.

Anyhow, I made a new release for 13.2.0 support https://github.com/ndeadly/MissionControl/releases/tag/v0.6.3

**Comment by giridharvc7** [comment]
v0.6.3 still crashes on AMS 1.2.5 when installed from hb app store

**Comment by ndeadly** [comment]
I don't maintain the hb appstore releases and cannot vouch for them working correctly. However, as far as I am aware they more or less just pull the releases from github.

Have you tried to see whether the official release from this github is working for you? If that works you will need to take the issue up with the hb appstore maintainers. Otherwise please post the error report for the crash. These versions definitely work together on the latest firmware, so it is more likely a problem with your setup.

**Comment by impeeza** [comment]
As referenced try to install from github and as test, backup & delete content folder from Atmosphère and install missioncontrol again it should work
