### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by FrannLp** [ndeadly/MissionControl#405]
### Switch Firmware Version

13.2.0 (Latest)

### Atmosphère Version

1.2.5 (Latest)

### Mission Control Version

0.6.3 (Latest)

### Boot Method

Hekate

### Issue Description

DualShock4 Controller (PS4) Randomly rumble and it does not stop after i paired joy-cons on nintendo switch. 
This happens only with this version.

**Comment by ndeadly** [comment]
Are you absolutely sure that you're running the version you reported you are? This sounds exactly like the issue I fixed in 0.6.2 and I haven't been able to reproduce it since.

If you're certain you have the latest version, please provide me with step by step instructions on exactly how the issue can be triggered so that I can try to reproduce it on my console.

**Comment by FrannLp** [comment]
It worked ! i downloaded the latest version of mission control :) thanks !
