### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by itchyd** [ndeadly/MissionControl#410]
### Feature Description

Wake from sleep

### Rationale

wake from sleep

### Additional Details

You describe the switch as not being wake-able because the controllers can't send the specific signal to the switch.  Can you change the bluetooth stack(?) in the switch so that the signal requirement is changed to the one that the controllers do send?  Likely already thought of and impossible but just thought i would mention it.

**Comment by impeeza** [comment]
The "protocol" for waking up the console is not a Bluetooth standard, and is handled by "hardware" no software, so no piece of software can change it.  Even the mission control isn't executing while the console is on standby. (I think)

At last there is now some knockoffs cheap controllers what can wake up the console even have NFC function

**Comment by Masamune3210** [comment]
You are correct, nothing is executing when the console is asleep other than the BPMP and maybe some things needed to assist the console in waking back up

**Comment by ndeadly** [comment]
This has already been asked about in these issues

https://github.com/ndeadly/MissionControl/issues/199
https://github.com/ndeadly/MissionControl/issues/204

The above posters are correct, wakeup is handled by the bluetooth chip itself, which then signals the CPU to wake up. The datasheet suggests there are even multiple ways that you could wake up the bluetooth chip using out-of-band methods (ie not related to bluetooth at all). I have no idea how it's done with official controllers or even where to begin looking.

Even if it were possible to modify something to look for alternate signals while the console is asleep, there are no standards dictating how other controllers wake their intended consoles when out-of-band signalling is an option. They could send a special bluetooth packet, but there's nothing stopping them from using any other form of wireless signalling that may require special receiving hardware on the other side. I am yet to see this documented for any other controllers either, so it would be one hell of a reverse engineering effort to figure it out how it's done for each controller.

I think something like a phone app that could wake the console would be much more feasible than trying to make it work for all the different controller designs out there. Whether this is even possible remains to be seen, again because I have no idea how the Switch does it, but also what eg. the Android SDK allows in the event it's even a bluetooth packet or something.

**Comment by Masamune3210** [comment]
The whole controller wake up for their respective systems point is a good one. I know for a fact that the PS4 and the Xbox one handle wake from sleep and sleep in general drastically differently from each other alone
