### ISSUE TITLE
[Bug Report]: Failing to launch, reboot after install doesn’t work.

### ISSUE THREAD

**Issue by gregnant** [ndeadly/MissionControl#429]
### Switch Firmware Version

13.2.1 (Latest)

### Atmosphère Version

1.2.6 (Latest)

### Mission Control Version

0.6.4 (Latest)

### Boot Method

Fusée

### Issue Description

I tried installing mission control from my pc and it doesn’t work, and then I tried the one off of the hb shop and after I reboot it still doesn’t start up.

**Comment by ndeadly** [comment]
> then I tried the one off of the hb shop

This is the official repository for the project. If the releases posted here don't work, then nothing will.

> after I reboot it still doesn’t start up.

How are you verifying this? Mission Control is a sysmodule (ie. background process), so the only way you will know it is running is if you successfully pair a controller. Which controller(s) are you trying to use?

**Comment by gregnant** [comment]
I can view it in my sysmodules in my Tesla menu.  Right next to mission control is says I need to reboot it.  I also have either a series x or one x controller, don’t really know or remember, but I tried my friends controller which is a normal Xbox one controller and it also wouldn’t connect.

**Comment by ndeadly** [comment]
The Tesla menu sysmodules overlay only controls whether or not a sysmodule _should_ be launched at boot, I don't think it actually know whether the module is actively running or not. If you're seeing Mission Control listed in there then chances are it's installed correctly and running though.

Xbox Series X/S controllers won't work, because they use a different bluetooth standard (LE) that isn't supported currently. Xbox One controllers do work, however a recent firmware update converts them to also use bluetooth LE. If your controller is on one of these firmwares (I think it's 5.x.x.x upwards) then you need to [downgrade](https://answers.microsoft.com/en-us/xbox/forum/all/revertrollbackdowngrade-xbox-controller-firmware/25f07169-3244-4fe0-838c-949951b7c109?auth=1) it using an Xbox console in order for it to work.

**Comment by gregnant** [comment]
I’ll go over everything in the morning when I get up, I’ll let you know if I can get anything to change.  Thanks man I appreciate the help.

**Comment by gregnant** [comment]
So I reinstalled mission control from here and put it on to my switch.  I rebooted from payload, and when I open up the sysmodules tab in my tesla menu it says on.  I tried to connect my controller and it doesn't work.  This is a shot in the dark, but, I tried to downgrade the firmware on my controller 3 times using my friends xboxes, and none of them were able to get the revert firmware option, telling me that my controller is just up to date.  Any chance you know why this is happening?

**Comment by ndeadly** [comment]
I've never had to downgrade a controller myself, nor do I own an Xbox, so I can't really help you there.

You said above that you weren't sure whether your controller was a Series X or One X controller. The former can't be downgraded. If you're unsure post a picture of the controller.

**Comment by ndeadly** [comment]
There is also an older variant of the Xbox One controller that doesn't support Bluetooth at all. Yours might be one of those. See [here ](https://support.xbox.com/help/hardware-network/accessories/connect-and-troubleshoot-xbox-one-bluetooth-issues)for info on how do tell the two variants apart.

Otherwise, make sure you've read the usage instructions and verify you're following them https://github.com/ndeadly/MissionControl#usage

**Comment by dmtdabs** [comment]
Im having the same issue, Running the same OFW and CFW version only through Hekate. I installed the newest release and i am unable to open the BTBD app. It crashes each time. Also, I dont see the sysmodule running when i open my Tesla Overlay menu. Lastly, i am unable to sync my PS4 controller when on the sync controller screen.

**Comment by ndeadly** [comment]
> I installed the newest release and i am unable to open the BTBD app. It crashes each time

@dmtdabs how did you install the latest version? I don't officially distribute the btdb application anymore (it's only really meant for identifying unsupported controller ids) , but a [new version](https://github.com/ndeadly/MissionControl/files/7227157/btdb-1300.zip) has been required since 13.0.0 to support changes made in that firmware. 

> Also, I dont see the sysmodule running when i open my Tesla Overlay menu

What do you mean by don't see it running? As far as I know the tesla sysmodules overlay doesn't actually know whether a sysmodule is running, it just controls whether or not it should launch at boot. However, if no entry for Mission Control shows up in the list then it is likely not installed properly.

> Lastly, i am unable to sync my PS4 controller when on the sync controller screen

Make sure you are following the [pairing instructions ](https://github.com/ndeadly/MissionControl#pairing-controllers) for Sony controllers correctly. Some older PS4 controllers be stubborn when it comes to pairing. Try holding the reset button on the controller and trying again.

**Comment by dmtdabs** [comment]
I installed the latest version from your repository on here. I had the BTBD from downloading it on the hbappstore before. 

My other sysmodules would come up on my Tesla Overlay but MissionControl would not show.

I have tried resetting my PS4 but still have not had any success getting it to link,

**Comment by ndeadly** [comment]
I don't know why hbappstore distributes btdb, especially since it's the old version. I don't package it with my releases.

> My other sysmodules would come up on my Tesla Overlay but MissionControl would not show.

Can't really comment much on this one, but as long as Mission Control is installed in the correct place and `toolbox.json` is present in it's install directory I don't see why it wouldn't show.

> UPDATE: I tried resetting and syncing multiple times, finally was able to get it to sync.

Sounds like you've probably got one of the older controllers. Once paired it should connect as usual though when you hit the PS button.
