### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by Kersonz** [ndeadly/MissionControl#431]
### Switch Firmware Version

13.2.1 (Latest)

### Atmosphère Version

1.2.6 (Latest)

### Mission Control Version

0.6.4 (Latest)

### Boot Method

Hekate

### Issue Description

This error will be caused every time you connect the Xbox controller after waking up the NS. However, after injecting hekate and entering the system, the Xbox controller can work normally. If you then put the NS in sleep, wake it up and reconnect to the Xbox controller, it will crash again.
This passage is translated,If there is any unclear expression, please understand
![QQ图片20220223183731](https://user-images.githubusercontent.com/93045568/155303244-17533218-5eba-4df3-ab9c-5d86b8217d60.jpg)

### Error Report

[report_000000910ee0758c.zip](https://github.com/ndeadly/MissionControl/files/8123483/report_000000910ee0758c.zip)

### Additional Context

sdcard : sandisk SDSQUNC-128G-ZN6MA
file system：exFat
Is there any information else I need to provide?

**Comment by ndeadly** [comment]
The error report indicates that this is is an issue with accessing a resource that's already in use. I dont have the 0.6.4 .elf file handy to find the exact location of the crash, but from your description it sounds like something to do with the virtual controller memory file not being closed when the console sleeps. This is strange because those files should be closed when the controller is disconnected as the console goes to sleep. Does it happen with any other controllers? I don't have my Xbox controller available to test. I wonder whether it has anything to do with your use of exFat, which is generally recommended to avoid for CFW.
