### ISSUE TITLE
[Controller Request]: "Xbox Wireless Controller" 1914 

### ISSUE THREAD

**Issue by XargonWan** [ndeadly/MissionControl#434]
### Controller Name

Xbox Wireless Controller (Model: 1914)

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Controller vendor and product ID

Microsoft

### Supported Features

- [X] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

### Additional Details

I am really confused as I got a Microsoft controller that is named "Xbox Wireless Controller". 

Model is 1914 and it seems to have non LE bluetooth. 
However this is not pairing.

**Comment by ndeadly** [comment]
Model 1914 is the new one introduced with the Series X/S. It uses Bluetooth LE and is currently unsupported by Mission Control. The choice by Microsoft to name them all "Xbox Wireless Controller" is indeed confusing. From their point of view the controllers can all be used with Xbox consoles and PC and there is little difference for the end user.

You can see [here](https://en.wikipedia.org/wiki/Xbox_Wireless_Controller#Summary) for the full list of wireless Xbox controllers  made by Microsoft. Only the 1708 and 1797 models are supported by Mission Control.

Closing, because there is already an open ticket for supporting this controller.
