### ISSUE TITLE
[Bug Report]: 8BitDo SN30 Pro Xbox Cloud Gaming Edition 

### ISSUE THREAD

**Issue by BambouVX** [ndeadly/MissionControl#442]
### Switch Firmware Version

Other (please specify in issue description)

### Atmosphère Version

Other (please specify in issue description)

### Mission Control Version

Other (please specify in issue description)

### Boot Method

Fusée

### Issue Description

hi i have a probleme my controller 8BitDo SN30 Pro Xbox Cloud Gaming Edition are connected but not working i use Atmosphère 1.3.0 (pre-release) and HOS: 14.0.0 and MissionControl-0.6.4-develop-33d3a39 can you help me pls ?

**Comment by ndeadly** [comment]
Have you seen this [issue](https://github.com/ndeadly/MissionControl/issues/394)? The user said that clearing the paired devices fixed a similar sounding problem.

Otherwise, a controller that connects but doesn't work usually means one of two things.

1) You controller is pairing, but isn't being recognised by ID. This could mean that there are multiple modes of operation and you have started it with one that Mission Control doesn't support. It could also mean that your controller uses a different ID to the one expected by Mission Control for some reason. You can use [btdb](https://github.com/ndeadly/MissionControl/files/7227157/btdb-1300.zip) to view the pairing database and determine the ID the controller is paired with.

2) Your controller is pairing and being recognised correctly, but is sending a different data format to that which is expected that Mission Control doesn't know how to deal with. This could be due to different controller firmware revisions sending different data formats. This [tool ](https://github.com/ndeadly/MissionControl/files/7628384/hid_report_viewer.zip) will allow you to view the incoming raw data from the controller.

For this controller, Mission Control expects a hardware ID `2dc8:2100`, and an input data format beginning with `01`

If the above is all correct, and clearing the pairing database doesn't work for you, please reach out to me on discord at ndeadly#5317. Github issues aren't really meant for support discussion

**Comment by ndeadly** [comment]
> I had the same issue until I downgraded the controller firmware using 8BitDo's utility

Interesting to know. I wonder whether 8BitDo are mirroring Microsoft and updating their controllers to use BLE in the new firmwares

**Comment by dprossner** [comment]
> Interesting to know. I wonder whether 8BitDo are mirroring Microsoft and updating their controllers to use BLE in the new firmwares

I dont think its Bluetooth LE, the 8BitDo update notes mentioned the HID service was changing so It might be that Mission Control would need to make a new profile for it but i'm not sure how that would work
![Screenshot 2022-05-02 212918](https://user-images.githubusercontent.com/65640171/166404784-062dbf0a-980f-408a-955f-01f427e526a1.png)
.

**Comment by ndeadly** [comment]
Ah yeah, I just re-read the issue where OP stated the controller is connected but not working. It wouldn't connect at all if it was LE. 

This combined with that update notice you posted implies that they might have changed the input packet format or maybe the even the id of the controller or something. I should be able to add support for the new firmware if you or anyone else is willing to spare a bit of time to help figure out what changed.

**Comment by dprossner** [comment]
> I should be able to add support for the new firmware if you or anyone else is willing to spare a bit of time to help figure out what changed.

Sure I can help. What kind of info do you need?

**Comment by ndeadly** [comment]
First you'll want to clear the pairing database as suggested above. You can do that from the system controller menu under `Disconnect Controllers`. You can also do it from my [btdb ](https://github.com/ndeadly/MissionControl/files/7227157/btdb-1300.zip) app by holding X.

Once you've done that, update back to the latest firmware and pair the controller again. If you open the btdb app I linked above you should see the controller listed as one of the entries in the database. Take note of the vid/pid for the controller. The current values I have for this one are `2dc8:2100`. If yours are different then I will need to add them in order to recognise the controller on the new firmware.

If the values above haven't changed, then it's likely the input format that has. Use my [hid_report_viewer](https://github.com/ndeadly/MissionControl/files/7628384/hid_report_viewer.zip) app to view the raw input data. Note down the numeric values displayed for each button on the controller as you press it and post them here. Make sure you don't have any other bluetooth controller connected when you do this as they will interfere.

**Comment by dprossner** [comment]
value has changed to 2dc8:2101

**Comment by ndeadly** [comment]
Try this and see if it's enough. It's quite possible they're also changed the input format.
[MissionControl-0.7.0-sn30pro-new-firmware-afde15a.zip](https://github.com/ndeadly/MissionControl/files/8608601/MissionControl-0.7.0-sn30pro-new-firmware-afde15a.zip)

**Comment by dprossner** [comment]
it works but minus seems to be bound to zl. When i\I press zl it inputs both minus and zl and when I press minus nothing happens.

**Comment by dprossner** [comment]
here's me pressing minus twice

https://user-images.githubusercontent.com/65640171/166417745-7a6f10d4-76e7-47ec-bb2f-90a112e0b562.mp4

**Comment by dprossner** [comment]
and heres zl twice (on the second press it didn't bottom out

https://user-images.githubusercontent.com/65640171/166418008-8c28810c-57e0-4bf6-80df-5b7873e73786.mp4

)

**Comment by dprossner** [comment]
Minus
![Minus](https://user-images.githubusercontent.com/65640171/166507988-c4fbbaca-303c-4cc5-8f1e-ff1ea842221a.jpg)

LT
![LT](https://user-images.githubusercontent.com/65640171/166507875-eab47e32-c990-454c-8f3f-38dbb8132a60.jpg)

RT
![RT](https://user-images.githubusercontent.com/65640171/166507936-65c83876-9f84-4663-b583-d5b7bfa12948.jpg)

**Comment by ndeadly** [comment]
Cool, try this
[MissionControl-0.7.0-sn30pro-new-firmware-1ae5b68.zip](https://github.com/ndeadly/MissionControl/files/8612829/MissionControl-0.7.0-sn30pro-new-firmware-1ae5b68.zip)

**Comment by dprossner** [comment]
yup that did the trick. all working as expected

**Comment by ndeadly** [comment]
I think we'll consider this resolved then. @BambouVX if the build above doesn't fix your issue, please re-open.

**Comment by ajslayer** [comment]
> I think we'll consider this resolved then. @BambouVX if the build above doesn't fix your issue, please re-open.

good day sir.
ofw 14.1.0
ams 1.3.1 /S

i tried the build "[MissionControl-0.7.0-sn30pro-new-firmware-1ae5b68.zip]" but when i tried to connect the xbox cloud gaming sn30, the console crashed and read: "a fatal error occurred when running atmosphere. program id: 010000000000bd00 error desc: std::abort() called (0xffe) report saved to etc etc. press power to reboot" the same error occurred when i tried to connect a ds4 and a xbox one BT controller.

i almost gave up when i decided to try to reconnect the controllers and it worked! the icons were colorful too so thats a plus i guess lol.  i also tried removing the pairings and re-pairing, and the crash didnt happen.

just wanted to let you know about the console crashing on initial pairing but that it ended up working perfectly. thanks for what you do man. ill be sure to contribute when i get my funds up

**Comment by ndeadly** [comment]
If you want to post the error report it made I'll take a look at it, but some degree of buginess can be expected from unofficial dev builds. The controller colour thing is an example of that, which should have been fixed since I posted the build above. It's possible the crashes you saw fall into that category too.

Try this one and see if it still gives you problems
[MissionControl-0.7.0-sn30pro-new-firmware-6321225.zip](https://github.com/ndeadly/MissionControl/files/8864919/MissionControl-0.7.0-sn30pro-new-firmware-6321225.zip)
