### ISSUE TITLE
[Bug Report]: Dualshock 4 is not detected by my Switch

### ISSUE THREAD

**Issue by ru379** [ndeadly/MissionControl#454]
### Switch Firmware Version

Other (please specify in issue description)

### Atmosphère Version

1.3.1 (Latest)

### Mission Control Version

0.7.0 (Latest)

### Boot Method

Hekate

### Issue Description

I have mission control installed correctly but when I go change the order of the controllers and put my Dualshock 4 in pairing mode, my console does not recognise It. I'm on latest mission control, atmosphere, and firmware (14.1.1) versión.
PS. Sorry if my english is not well understood, i am spanish

**Comment by ndeadly** [comment]
When you say the console doesn't recognise the controller, do you mean nothing at all happens when you try to pair it? If this is the case these are the likely possibilities:
- You are not entering the sync mode correctly. Make sure the lightbar is flashing in a heartbeat pattern after pressing PS + Share
- Some controllers, especially the older V1, can be stubborn to connect. Pressing the reset button on the back of the controller can help
- Your controller battery is almost depleted. Try charging the controller or checking the battery level on another device
- You have an incompatible bootleg controller. Unfortunately I can't do much in this case

If you are getting some kind of paired notification, but the controller is not showing up or staying connected:
- Your controller battery may be low
- You may have a bootleg controller which is compatible, but doesn't support a special vendor command the console sends to the controller. See https://github.com/ndeadly/MissionControl/issues/342#issuecomment-954172676 for a workaround
- Initialisation of the controller hander may be failing. This is often due to problems reading files from the sd card. Try deleting the `sdmc:/config/MissionControl/controllers` directory

**Comment by ru379** [comment]
> When you say the console doesn't recognise the controller, do you mean nothing at all happens when you try to pair it? If this is the case these are the likely possibilities:
> - You are not entering the sync mode correctly. Make sure the lightbar is flashing in a heartbeat pattern after pressing PS + Share
> - Some controllers, especially the older V1, can be stubborn to connect. Pressing the reset button on the back of the controller can help
> - Your controller battery is almost depleted. Try charging the controller or checking the battery level on another device
> - You have an incompatible bootleg controller. Unfortunately I can't do much in this case
> 
> If you are getting some kind of paired notification, but the controller is not showing up or staying connected:
> - Your controller battery may be low
> - You may have a bootleg controller which is compatible, but doesn't support a special vendor command the console sends to the controller. See https://github.com/ndeadly/MissionControl/issues/342#issuecomment-954172676 for a workaround
> - Initialisation of the controller hander may be failing. This is often due to problems reading files from the sd card. Try deleting the `sdmc:/config/MissionControl/controllers` directory

Thanks a lot, the problem was the low battery level, I tried again while the controller was charging and it worked.
