### ISSUE TITLE
[Bug Report]: Controllers Immediately disconnect after exiting connect menu.

### ISSUE THREAD

**Issue by M4X40** [ndeadly/MissionControl#471]
### Switch Firmware Version

14.1.1 (Latest)

### Atmosphère Version

1.3.2 (Latest)

### Mission Control Version

0.7.0 (Latest)

### Boot Method

Hekate

### Issue Description

Any controller I try to connect (i have tried WiiMote & Xbox One S) disconnects immediately after I exit the controller screen. I have tried restarting console, rebooting to payload, re-connecting controllers, but to no avail.

### Error Report

N/A

### Additional Context

I boot using sys, due to my sd card only being 32gb. I downloaded missioncontrol from the hb app store and here.

**Comment by ndeadly** [comment]
Which "controller screen" are you referring to? The `Change Grip/Order` one? Is the exiting of this screen what's actually triggering the disconnect (i.e. if you remain on that screen after pairing, does it stay connected?) or does it just appear that way because you exit the screen as soon as it pairs? Anything else you can tell me about your environment? SD card format? Any other custom sysmodules running? etc... I own both of these controllers and have never had an issue with them disconnecting like this.

**Comment by M4X40** [comment]
Its after exiting the main controller screen. (Buttons with Change Grip/Order, Find Controllers, & Pair Controller) I have tried waiting up to 5 minutes before exiting the screen, but nothing has worked. The SD-Card is formatted as FAT32 with 32GB of storage. The sys-modules I have are just MissionControl and sys-ftpd-light.

**Comment by ndeadly** [comment]
Hmm I'm not really sure what could be happening here. I don't know why the controller applet would ever send a disconnect command on exit, and as far as I know the bluetooth management code isn't watching which application is active.

How do you exit the applet? B button? Home? Selecting the Close option? Do the controllers actually disconnect (LEDs turn off or blink)? And they definitely don't respond to inputs?

> like the controller was never paired in the first place

What happens if you try to wake either controller from the home screen. Do they not reconnect?

**Comment by M4X40** [comment]
> How do you exit the applet?

I have tried everything you just listed; B, Home, & Selecting Close.

> Do the controllers actually disconnect (LEDs turn off or blink)? And they definitely don't respond to inputs?

Yep, lights and everything. No inputs recognized either.

> What happens if you try to wake either controller from the home screen. Do they not reconnect?

The conntrollers do not connect back, almost like the swift "forgot" that they exist, but they still show in paired devices, just not connected.

> Is it possible to make a video demonstrating the behaviour?

I can get to work on that.

**Comment by M4X40** [comment]
So i just tried to record the clip now its working. No clue why it wasn't working before, but thank you for your support anyways.
