### ISSUE TITLE
[Bug Report]: DualSense Rumble causes erratic gyroscope behavior

### ISSUE THREAD

**Issue by teconmoon** [ndeadly/MissionControl#472]
### Switch Firmware Version

14.1.1 (Latest)

### Atmosphère Version

1.3.2 (Latest)

### Mission Control Version

0.7.0 (Latest)

### Boot Method

Hekate

### Issue Description

First off, thanks for supporting DualSense controllers in the first place!

I've been playing through Super Mario Galaxy lately which is pretty heavy on being able to point accurately, and something odd I've noticed consistently is that when the controller rumbles, the pointer will drastically move down and then back to it's normal position when the controller stops rumbling.

It's a little hard to explain, so I recorded a clip from Bowser's Fury demonstrating this. In the video, here are the things I'm doing that cause controller vibration:
- Ground Pound
- Land from a normal jump
- When Bowser's storm starts

[Bowser's Fury Video Recording](https://youtu.be/w7RWtw_v4Os)

Corresponding with the controller vibrating to these events, the point wigs out.

I don't know if this is something inherent to the controller or even something that can be fixed, but thought I'd shoot this your way. I've tested three controllers with the same issue, so I don't think it's any one controller causing this. Sorry if my explanation was sub-par, thanks for reading!

**Comment by ndeadly** [comment]
Thanks for reporting. Watching your video, it's clear there's definitely some effect of the rumble motors on the motion controls. I don't currently have access to a Dualsense controller, but I should be getting my hands on a PS5 in a couple of weeks so will be able to do some testing then.

I don't know how controllers normally deal with this kind of thing. Maybe there's some kind of filter or threshold used to minimise the effect. I know some people have complained in the past of the rumble on the Dualsense being too strong, perhaps this has something do with it.

**Comment by Masamune3210** [comment]
Maybe as a stopgap, only use the right motor, as it's finer feedback pattern has less chance to cause as much of a issue than the left or both?

**Comment by teconmoon** [comment]
@ndeadly I happen to have a spare DualSense for sale! I’d definitely be willing to give you a good price for The Cause™, if you’d be interested in it probably the best way to coordinate would be to message me on GBAtemp. I go by the same username there.

**Comment by ndeadly** [comment]
Thanks for the offer, but I'll have one soon enough when my ps5 arrives. Don't really need a second one for now.

**Comment by teconmoon** [comment]
@ndeadly Hey hope you're doing well, just checking if there was any progress on this. Thanks!

**Comment by ndeadly** [comment]
No, not really anything currently. I have my Dualsense controller now and was able to confirm the issue myself. I'm just not really sure what to do about it. 

I thought maybe it was related to the strong rumble of the controller getting picked up on the accelerometer. I found some source code (I think it was DS4Windows) that suggested there was a field for controlling the rumble intensity. I tried setting this value but I didn't feel like it really did much if anything at all. I could try lowering the upper value when mapping vibrations I guess, but then there would be fewer unique intensity levels.

The other thing I thought is that it might be something to do with the controller having a higher polling rate to what the Switch is expecting, and that maybe that's causing some kind of faster-than-usual error accumulation or similar when hit with the acceleration spikes.

I haven't really had the time to look into this in depth because of other things I've been busy with. This kind of thing can be time consuming, and is not really of game-breaking priority as far as I can tell.

**Comment by ndeadly** [comment]
Finally got around to figuring out how to lower the relative rumble intensity. This feels closer to the intensity of the Pro Controller to me, and looks as though it more or less fixes the drifting behaviour you described. Let me know what you think.

[MissionControl-0.7.0-dualsense-da73c8b.zip](https://github.com/ndeadly/MissionControl/files/9143468/MissionControl-0.7.0-dualsense-da73c8b.zip)

**Comment by teconmoon** [comment]
Definitely appears to mitigate the impact! Appreciate your work on this, especially considering how few titles would really be affected by this. Pointing in Super Mario Galaxy should now be fun!
