### ISSUE TITLE
[Bug Report]: Xbox Elite series 2 Unable to connect normally

### ISSUE THREAD

**Issue by trulymust** [ndeadly/MissionControl#475]
### Switch Firmware Version

14.1.1 (Latest)

### Atmosphère Version

1.3.2 (Latest)

### Mission Control Version

0.7.0 (Latest)

### Boot Method

Hekate

### Issue Description

Hello developer, my Xbox Elite Series 2 handle plug-in cable can be used normally, but Bluetooth can't be searched when the switch handle is paired. I'm sure there's no problem with my Bluetooth module. I hope you can help me solve it. Thank you

**Comment by trulymust** [comment]
Thank you very much for your reply. I just returned the firmware version to 4.8, and it can be used normally. Thank you

**Comment by EzioZz** [comment]
I have returned to fireware version 4.8 but still failed to connect switch. 
mission control 0.7.1
switch fimeware 14.1.2
ams 1.3.2

**Comment by ndeadly** [comment]
@EzioZz nothing has changed in either Nintendo firmware or Mission Control regarding controller pairing between the versions reported by @trulymust and yours. Since this was resolved by OP by downgrading the firmware, I assume my bluetooth patches on this firmware are working correctly and that the problem is more likely to be on your end.

Please ensure the sysmodule is installed correctly, running, and you're following the [usage ](https://github.com/ndeadly/MissionControl#usage) and [pairing](https://github.com/ndeadly/MissionControl#pairing-controllers) instructions correctly. If you're still having problems you can reach out to me directly on discord @ ndeadly#5317. The issue tracker is not really meant for troubleshooting.
