### ISSUE TITLE
[Bug Report]: Some PS4 Controllers blink once, then immediately disconnect.

### ISSUE THREAD

**Issue by kirankunigiri** [ndeadly/MissionControl#486]
### Switch Firmware Version

14.1.1 (Latest)

### Atmosphère Version

1.3.2 (Latest)

### Mission Control Version

0.7.0 (Latest)

### Boot Method

Fusée

### Issue Description

I had 4 PS4 controllers that all worked with the Switch. Recently I updated from 13.x firmware to the latest Switch firmware and also updated MissionControl. Now, only 1 of the controllers connects properly. On the other 3 controllers, during pairing mode the Switch will show a "Controller Connected" notification and then the PS4 controller will blink once, and then immediately disconnect.

**Comment by ndeadly** [comment]
There are three major causes that I know of that can be responsible for disconnecting PS4 controllers. Since you have 4 controllers, you might be affected by one or more of these.

1) Issues reading virtual controller memory files. Some people have reported problems to me indicating fs errors when initialising the controller handler. This points to the virtual flash memory files I store to sd card so that controller calibrations etc can work. I'm not really sure what can cause errors here, possibly file corruption? Some people have had success in deleting the `/config/MissionControl/controllers` directory.

2) Low controller battery. When the controller battery is low enough but not quite dead, the controller will switch off soon after you power it on with the PS button. I'm not sure whether this is the switch disconnecting it, or the controller simply switching off due to the critical battery level.

3) Some third party/bootleg controllers use a Bluetooth chipset that doesn't like a certain vendor command the Switch is sending. I used to block this command from all controllers but found it caused problems, so at some point I changed the behaviour to block it only when necessary. Official controllers support this command however, and since we can't tell them apart from software, these problematic controllers need to be manually flagged by creating an empty file called `settsi_disable.flag` under their entry in `/config/MissionControl/controllers`.

The first two in this list are potentially caused be bugs in the software. Unfortunately, to date I have been unable to reproduce these issues for myself so addressing the root cause has proven difficult. If you can provide any additional insight based on your experiences this would be much appreciated.

**Comment by kirankunigiri** [comment]
Thank you so much! It was the second issue and after connecting it to my laptop, I saw the battery level was only at 5-15% on the controllers that weren't working. After charging them they were working properly. Usually when they run out of battery, the light goes at altogether instead of still blinking so I immediately thought it was a different issue instead of trying to charge them.

**Comment by ndeadly** [comment]
> Usually when they run out of battery, the light stops blinking very quickly instead of blinking like normal during so I immediately thought it was a different issue instead of trying to charge them.

Yeah this could be the Switch disconnecting the controller then. My approach to mapping the battery levels between the representations for different controllers may be a bit too naive, as the values reported are not necessarily linear etc. It could be that I'm telling the switch the battery is at a critical level too soon. I'll try to experiment a bit next time my DS4 battery is running low
