### ISSUE TITLE
[Bug Report]: Controller wont connect on fresh install

### ISSUE THREAD

**Issue by Tanju42** [ndeadly/MissionControl#487]
### Switch Firmware Version

14.1.1 (Latest)

### Atmosphère Version

1.3.2 (Latest)

### Mission Control Version

0.7.0 (Latest)

### Boot Method

Fusée

### Issue Description

On older version my Xbox elite 2 would be recognized.

Now on an fresh atmosphere install with fresh mission controll ita not working

When I begin the pairing process it can't find my controller.

And yes I am really sure that I am doing nothing wrong or incorrectly.

**Comment by Tanju42** [comment]
What I found out is that I have an Magic S Pro dongle that worked on older versions with the switch.

Now I tested it as well and it's not working.
With mission control installed and without.

(Magic s Pro simulates an Switch Pro controller and connects to most Bluetooth controllers)

**Comment by ndeadly** [comment]
Which firmware is your controller running? The 5.x.x.x update for Xbox One/Elite controllers changed the controllers to use Bluetooth LE, which is not currently supported. This is the most likely cause for a contoller that was working previously.
The XBE2 controller also requires special patches to the Bluetooth module in order to be able to pair with the console. Please verify that you have the file `/atmosphere/contents/exefs_patches/bluetooth_patches/FEE47E024FC9C62838FF1A476DE243DCE673DA7E.ips` present on your SD card.

**Comment by Tanju42** [comment]
Pro controller wired connection was deactivated now through dongle works.

In the path
/atmosphere/exefs_patches/bluetooth_patches
There is the file:
FEE47E024FC9C62838FF1A476DE243DCE673DA7E.ips

Xbox elite 2 firmware version:
4.8.1908.0

Filght mode is disabled
Bluetooth is enabled

DualSense and xbox e 2 still not working

I can even send a video how I try to pair the controller but I think you could believe that it's not a user error.

Is there no debug possible?
A log file?

**Comment by Tanju42** [comment]
![20220627_184723](https://user-images.githubusercontent.com/16364184/175993703-02c19151-caa3-45e5-895e-dce9385216eb.jpg)
Did what you said but no screenshot was taken.

So the Module wont load.

How I installed Mission Control
1 Download 0.7.0
2 Unzip
3 Move to root on SD
4 reboot switch

Am I missing something?

**Comment by ndeadly** [comment]
Not sure what you're trying to indicate with the numbers there, but those are the buttons for the combo, yeah. If the combo is not working then that's a pretty strong indicator that Mission Control isn't running. 

> How I installed Mission Control
> 1 Download 0.7.0
> 2 Unzip
> 3 Move to root on SD
> 4 reboot switch
> 
> Am I missing something?

This seems fine. Did you download the official zip from github? It might be worth redownloading and unzipping a fresh copy. Also, be sure to check the option to overwrite existing files.

If the module is in the correct location, the only possibilities are either the module is loaded correctly, the module fails to load correctly and the system crashes on boot, or atmosphere doesn't attempt to load the module in the first place (due to missing `boot2.flag` file in `/atmosphere/contents/<title_id>/flags`

**Comment by ndeadly** [comment]
Can you also show me a screenshot of your `/atmosphere/contents/` directory? In case you have any other sysmodules etc that could be interfering

**Comment by Tanju42** [comment]
Official zip
Replaced everything

In the dir
/atmosphere/contents/010000000000bd00/flags
There are no files

And when I unzip it the boot2.flag has 0 bytes
![Screenshot_20220628-120912_My Files](https://user-images.githubusercontent.com/16364184/176153899-896e4adf-e9ea-4c97-bb43-a7414e79e332.jpg)

I will try redownloading it

**Comment by Tanju42** [comment]
Even in winrar(without unziping) it has 0 bytes
![Screenshot_20220628-121049_RAR](https://user-images.githubusercontent.com/16364184/176154228-7725bf9f-deb2-4fde-a1ac-32fffc2b4022.jpg)

**Comment by ndeadly** [comment]
> Even in winrar(without unziping) it has 0 bytes ![Screenshot_20220628-121049_RAR](https://user-images.githubusercontent.com/16364184/176154228-7725bf9f-deb2-4fde-a1ac-32fffc2b4022.jpg)

This is normal. The file is empty and is just there to flag atmosphere whether to load the module or not. This can be used if you want to disable loading it for whatever reason, and is how tools like hekate toolbox or ovl-sysmodules work.

**Comment by Tanju42** [comment]
So the problem was that my ftp programm didn't copy the file.
I think bcs it's 0 bytes (maybe write a text in it what explains its function and it will be copied on shifty ftp programs)

Now everything is working

**Comment by ndeadly** [comment]
Thanks for the followup. This is an issue I haven't (knowingly) encountered before. Good to know about.

> maybe write a text in it that explains its function and it will be copied on shitty ftp programs bcs its large then 0 bytes then

I don't think explaining its function is really necessary. The people that care about this file know what it does. Adding a single byte so it always gets copied could be a good idea though.
