### ISSUE TITLE
Doom (retro): Constant camera spin

### ISSUE THREAD

**Issue by parkerlreed** [ndeadly/MissionControl#49]
Using a DS4. When running classic Doom, the camera spins very fast and cannot move.

Only weird thing I've done is remapped Cross to A and Circle to B in the Nintendo remapper.

**Comment by parkerlreed** [comment]
Undid the mapping. Same result. If I disconnect the controller mid game, the spinning stops.

**Comment by parkerlreed** [comment]
https://www.youtube.com/watch?v=mTEHQtCZ2cM

**Comment by ndeadly** [comment]
This is a [known issue](https://github.com/ndeadly/MissionControl#known-issues-and-limitations) with motion controls at the moment. Motion controls are not currently supported, and this was an oversight during testing since I don't have many games where they're on by default. It's simply due to me not zeroing the data out properly, or maybe bad calibration data. The workaround for now is to disable motion controls if your game allows.

**Comment by parkerlreed** [comment]
Aha that was indeed it. It never crossed my mind that Doom of all things would have motion support... Jeeze.

**Comment by ndeadly** [comment]
Try this build and see if the motion control issues are resolved
[MissionControl-0.1.0-motion-control-fix.zip](https://github.com/ndeadly/MissionControl/files/5179959/MissionControl-0.1.0-motion-control-fix.zip)

**Comment by parkerlreed** [comment]
Resolves the issue. Thanks.
