### ISSUE TITLE
[Bug Report]: Wii U Pro Controller Connection issues

### ISSUE THREAD

**Issue by ManginPlay** [ndeadly/MissionControl#495]
### Switch Firmware Version

14.1.0

### Atmosphère Version

1.3.2 (Latest)

### Mission Control Version

0.7.0 (Latest)

### Boot Method

Hekate

### Issue Description

I've been using MissionControl to connect my Wii U Pro controller to my switch for a good while now, and it used to work, but following a system update earlier this year, (and updating MissionControl), my Wii U Pro controller has never been able to properly connect again.

The behaviour experienced goes as follows:
- Pair controller to Switch
- Controller connects as controller 1
- The controller starts rumbling uncontrollably, then stops
- The controller starts rumbling again as soon as the A button is pressed, then stops and never does it again

Going to the input test menu to check the functioning buttons, only the plus, minus and home buttons are functional.

I have tried reinstalling MissionControl, clearing all the bluetooth connections, and wiping the controllers folder, but none yielded any results.

Thanks in advance for your help, and hoping that a fix can be found for this issue.

**Comment by ndeadly** [comment]
There's a regression in the current release that can cause Wii U Pro controllers to be misidentified. The issue has been fixed in [this commit](https://github.com/ndeadly/MissionControl/commit/6268edb113d3c30cdd965acd599cdd75bb989970), but I haven't got around to making a new release with it included.

Try this build and see if your issues are resolved, or whether there's something else I need to look into.

[MissionControl-0.7.0-develop-d38ca82.zip](https://github.com/ndeadly/MissionControl/files/9083142/MissionControl-0.7.0-develop-d38ca82.zip)

**Comment by ManginPlay** [comment]
That fixed the issue.
Thanks a lot for your help !
