### ISSUE TITLE
Mission control not working with xbox controller nothing seems to fix it

### ISSUE THREAD

**Issue by phillipbruh** [ndeadly/MissionControl#497]
### Switch Firmware Version

14.1.1 (Latest)

### Atmosphère Version

1.3.2 (Latest)

### Mission Control Version

0.7.0 (Latest)

### Boot Method

Fusée

### Issue Description

Hi i tried to connect my xbox controller to the switch with mission control and it is not connecting, I tried to downgrade my xbox controller firmware but on the xbox accessories app it does not show any option to.

I have tried to use the win+R method but instead of downgrading it just says your controller is on the most recent software.

Is there any other way to downgrade it or fix it(i do not have a xbox)?

**Comment by phillipbruh** [comment]
![image](https://user-images.githubusercontent.com/95700058/179265750-ffc5d517-ee97-43bb-a617-80af10f1c250.png)

**Comment by ndeadly** [comment]
Assuming you are doing everything else correctly, my guess would be that you are trying to pair a Series X|S controller or one of the old ones that doesn't have Bluetooth. See [here ](https://en.wikipedia.org/wiki/Xbox_Wireless_Controller#Summary) for the differences between the different models. The only ones supported by Mission Control are the 1708 and 1797 models. The 1904 requires Bluetooth LE support to function, and can't be downgraded because it never had an older firmware that didn't use LE.
