### ISSUE TITLE
[Bug Report]: cannot connect ps4 control with my switch oled run 14.1.2 and AMS 1.3.2

### ISSUE THREAD

**Issue by Khuongkaka** [ndeadly/MissionControl#510]
### Switch Firmware Version

Other (please specify in issue description)

### Atmosphère Version

1.3.2 (Latest)

### Mission Control Version

0.7.0 (Latest)

### Boot Method

Hekate

### Issue Description

canot connect ps4 control witch my switch oled run 14.1.2 and AMS 1.3.2

**Comment by sercal7** [comment]
I have the same exact issue on a normal switch, tried to reset PS4 controller but id does not find it

**Comment by ndeadly** [comment]
Please confirm the module is running (`MINUS` + `DPAD_UP` button combo on the left joycon should activate the capture function when connected wirelessly), that you are on the correct menu (`Controllers->Change Grip/Order`) and following the correct [pairing procedure](https://github.com/ndeadly/MissionControl#pairing-controllers) for the Dualshock4.

**Comment by Khuongkaka** [comment]
> Please confirm the module is running (`MINUS` + `DPAD_UP` button combo on the left joycon should activate the capture function when connected wirelessly), that you are on the correct menu (`Controllers->Change Grip/Order`) and following the correct [pairing procedure](https://github.com/ndeadly/MissionControl#pairing-controllers) for the Dualshock4.

i connected DS4 with my switch when ít's still at 14.1.0 and AMS  1.3.1. But when i upgrade 14.1.2 AMS 1.3.2. I can't connect when I upgrade. even though I did exactly as instructed

**Comment by ndeadly** [comment]
You still didn't confirm the module is actually running.

Nothing Bluetooth related has changed since 14.0.0, and Atmosphere updates don't affect Mission Control (unless they enforce a newer minimum firmware version). There should be no need to re-pair after an update of either. It seems highly likely to me that you have connected the controller to another device in the meantime. Sometimes this can require a reset of the controller before it will pair with the Switch again. Try holding the little reset button on the underside of the controller with a paperclip or similar for a few seconds and pairing again. If this doesn't help, clear the pairing database (`System Settings->Controllers and Sensors->Disconnect Controllers`) and try again.

**Comment by Pentalex** [comment]
I'm having the same issue except I am using a DualSense (PS5) controller.
Exact same atmosphere and nintendo switch OS version as OP also running latest MissionControl. Everything worked until I updated my Switch yesterday.
The module is running, it takes a screenshot if I use the button combo provided in this thread. I have reset the controller using a paperclip and have also cleared the pairing database but to no avail. 
I have also tried deleting the controller configurations folder on the SD card.

Of note: When I try to pair I get a notification saying a controller has been paired but it doesn't work and never shows up in the `Controllers -> Change Grip/Order` menu.
Seems to me this is an issue with the latest Switch OS update breaking something.

**Comment by ndeadly** [comment]
@Pentalex have you tried charging the controller? This can happen with low controller battery too.

**Comment by ndeadly** [comment]
You could also try this build of the current development branch. I've made several minor accuracy improvements to controller emulation that may make connecting more reliable in some cases.

[MissionControl-0.7.0-develop-c5093b2.zip](https://github.com/ndeadly/MissionControl/files/9568524/MissionControl-0.7.0-develop-c5093b2.zip)

**Comment by Pentalex** [comment]
> @Pentalex have you tried charging the controller? This can happen with low controller battery too.

Thank you for the quick and helpful reply. It works now haha. 
I feel so stupid for not trying this as the lights on the controller still turn on but I guess the battery was indeed too low to connect to the Switch.

Again, I appreciate it! :)

**Comment by ndeadly** [comment]
I think it stems from the accuracy of mapping the sony battery level to that of the switch. They have a different number of levels, and I'm not sure whether either of them even use linear scales or not. I think the current release reports the battery level too high, so you never get low battery warning notifications when the controller battery is low enough to switch off. I've tweaked the battery level mapping in the develop branch so that hopefully you at least get battery notifications in the future.

**Comment by ndeadly** [comment]
Since there have been no followups in several weeks, I'll assume this issue has been resolved in one way or another. If there are still issues when running the [latest release](https://github.com/ndeadly/MissionControl/releases/tag/v0.7.1) then this issue can be re-opened.
