### ISSUE TITLE
PS4 Official Alpine Green Controller Not Worked - This is VID PID for Update 

### ISSUE THREAD

**Issue by indewer** [ndeadly/MissionControl#53]
HID\VID_054C&PID_09CC&REV_0100&MI_03
HID\VID_054C&PID_09CC&MI_03
HID\VID_054C&UP:0001_U:0005
HID_DEVICE_SYSTEM_GAME
HID_DEVICE_UP:0001_U:0005
HID_DEVICE

**Comment by indewer** [comment]
default ps4 black controller - worked, but "alpine green" - not :(

**Comment by ndeadly** [comment]
This device ID is already supported. I suspect you might be running into the DS4 battery bug if it's not working. Try this build where I've fixed the issue.

[MissionControl-0.1.0-ds4-battery-fix.zip](https://github.com/ndeadly/MissionControl/files/5178971/MissionControl-0.1.0-ds4-battery-fix.zip)

**Comment by DeathChaos25** [comment]
Having same problem with a regular black DS4 (v2), even the battery fix hasn't allowed me to pair it successfully, even after a database wipe, I also tried using it for a bit on PS4 to use up a good chunk of battery, no success either.

Device ID is VID_054C&PID_09CC&REV_0100&MI_00

**Comment by ndeadly** [comment]
"Same problem" isn't particularly meaningful here as @indewer never stated what the actual problem was. Does the console crash? Freeze? Does the controller just never connect? Have you been able to pair other non-switch controllers? I need detailed information in order to offer any real assistance.

**Comment by DeathChaos25** [comment]
Same problem as in the DS4 never pairs successfully with the console.

I have 2 different pairs of joycon (Gray and Purple/Yellow pairs) as well as a GCN Adapter and they all pair/work correctly before/after the database wipe, don't have any other non-Switch controllers to test.

**Comment by ndeadly** [comment]
@DeathChaos25 since you don't have another non-switch controller to test with I can't rule out the case that MissionControl isn't actually running. I would first try reinstalling MissionControl making sure you accept any prompts to overwrite existing files. 

Next, make sure you are actually entering pairing mode successfully. If you are unsure how to do this please refer to the project readme. The LED blinking should resemble a heartbeat.

I haven't had any reports of DS4 v2 controllers not working apart from those affected by the battery level bug. Some users with v1 controllers have reported that multiple attempts are required before the controller will actually pair with the console. It's possible that this happens with some v2 controller too, so I would try several times over before concluding it's not working.

If all else fails, consider opening your own issue detailing your specific experience.

Lastly, I have some questions about the GCN adapter with regards to users asking about analog trigger support. If you are interested in helping me out with some research there please shoot me a message. I'm available under the name ndeadly on reddit, gbatemp and many of the switch related discord servers

**Comment by indewer** [comment]
> Этот идентификатор устройства уже поддерживается. Я подозреваю, что вы можете столкнуться с ошибкой батареи DS4, если она не работает. Попробуйте эту сборку, в которой я исправил проблему.
> 
> [MissionControl-0.1.0-ds4-battery-fix.zip](https://github.com/ndeadly/MissionControl/files/5178971/MissionControl-0.1.0-ds4-battery-fix.zip)


thanks, it helped! =]

**Comment by ndeadly** [comment]
The DS4 battery bug is now fixed in the latest release.

**Comment by DeathChaos25** [comment]
Just commenting to say that the latest release made my DS4 successfully connect first try.
