### ISSUE TITLE
[Bug Report]: Cannot pair dualsense

### ISSUE THREAD

**Issue by Babbosh** [ndeadly/MissionControl#542]
### Switch Firmware Version

14.1.2

### Atmosphère Version

1.4.0 (Latest)

### Mission Control Version

0.8.0 (Latest)

### Boot Method

Fusée

### Issue Description

I am trying every-thing possible to connect the dualsense  but it doesn't want to pair. 

I did manage to pair it before my last factory reset and it worked when I paired it. Then I put the switch to sleep and the following day the dualsense would connect (showing hard blue light) but switch wouldn't recognize the controller (question mark over the controller icon) and therefore it was unresponsive to any input. 

I tried hekate and fusee. Same problem

Please help.

**Comment by ndeadly** [comment]
> I am trying every-thing possible to connect the dualsense but it doesn't want to pair.

You say this, and yet you haven't stated a single thing that you tried. Please elaborate on what hasn't worked so far.

> question mark over the controller icon

Where does this occur? I don't recall ever having seen a question mark before.

**Comment by Babbosh** [comment]
Hi

I did state that I tried two different payloads (hekate and fusee). 

When I was trying to reconnect the dualsense, it would connect (showing the hard blue led light on dualsense) but the switch would be unresponsive to any input. I, therefore, tried to click on the joypad icon on the previously paired peripherals, then the system would try to connect with sound and the sliding 4 dots at the bottom of the icon but would fail resulting in a question mark being displayed over the joypad icon. 

Do you wanna help or are you gonna  try again to berate me by treating me like a moron?

**Comment by ndeadly** [comment]
The bootloader makes no difference to run-time issues like this. The question is only there in the issue template to help diagnose boot issues.

> I, therefore, tried to click on the joypad icon on the previously paired peripherals, then the system would try to connect with sound and the sliding 4 dots at the bottom of the icon but would fail resulting in a question mark being displayed over the joypad icon.

Oh, I see what you mean. Yeah, I don't think that feature works for anything other than official controllers.

> Do you wanna help or are you gonna try again to berate me by treating me like a moron?

Relax, nobody is berating you. These kind of questions get asked multiple times every week. They are almost _always_ user issues rather than software bugs. When the issue template asks you to "Please include as much information as possible so the issue can be replicated and identified" and you make sweeping statements like "I've tried everything", please understand that you are actually providing very little information and potentially wasting both your own and my time.

Have you tried redownloading and reinstalling Mission Control from the github release? Resetting the controller? Clearing the controller database? Deleting the `/config/MissionControl/controllers/` directory?

If you have tried all of the above without luck, install this build and post the `mc-mitm.log` file it creates on the root of your sd card after attempting to pair the controller.

[MissionControl-0.8.0-debug-logging-7fe293f.zip](https://github.com/ndeadly/MissionControl/files/10059053/MissionControl-0.8.0-debug-logging-7fe293f.zip)

**Comment by Babbosh** [comment]
Don't worry, I managed to fix this myself. 

You might wanna settle down a bit, buddy. Before somebody declares war on your broken English.

**Comment by Masamune3210** [comment]
The author of the project replies, trying to help you figure out the issue, and you decide to go after their non-existent English issues. Something tells me that they aren't the one that people are going to be mad at.......

**Comment by Babbosh** [comment]
I Understand. Well at least I provided your daily dose of d@ck riding, white knight.  Wait a couple of hours and  you might even have a w@nking session beholding  a blissful myriad of thumbs up.

**Comment by ndeadly** [comment]
Guess you hadn't tried everything after all, eh?

> You might wanna settle down a bit, buddy. Before somebody declares war on your broken English.

Lol what? I'm a native speaker, mate...
