### ISSUE TITLE
[Bug Report]: Buttons not responding

### ISSUE THREAD

**Issue by Whaleman1** [ndeadly/MissionControl#563]
### Switch Firmware Version

15.0.1 (Latest)

### Atmosphère Version

1.4.0 (Latest)

### Mission Control Version

0.8.0 (Latest)

### Boot Method

Hekate

### Issue Description

Wiimote + classic/pro controller not letting me use r-triggers. Hekate(6.0.1) emunand(fimrware 15.0.1) Atmosphere(1.4.0) Mission control(0.8.0)

### Additional Context

xaw4000
also running tesla-menu, Nxovlloader, and sys-con.
downloaded all cfw, homebrew, and payloads from github.
OEM wiimote + extensions
booting hekate + emunand (hekate pushed by PC, not using auto-rcm)
Issue occurs both docked and handheld.

**Comment by Banz99** [comment]
This is a known issue due to an oversight when changing the mapping (now 1 and 2 on the wiimote work as left and right stick press) and has been already fixed in the development builds. It'll be fixed by the time 0.8.1 or whatever new version is out. In the meanwhile you can use the build I'm attaching here.
[MissionControl-0.8.0-develop-de306be.zip](https://github.com/ndeadly/MissionControl/files/10369927/MissionControl-0.8.0-develop-de306be.zip)

**Comment by ndeadly** [comment]
As above, this is a known issue that has been fixed already and will be included in the next release.
