### ISSUE TITLE
Controller Support for Gulikit Kingkong Pro Controller

### ISSUE THREAD

**Issue by DrAllen694** [ndeadly/MissionControl#58]
I attached a photo of the controller itself and the paired devices on Btdb. (054c prolly my 2 ds4)

![20200910_051757](https://user-images.githubusercontent.com/71043330/92657160-e684ef80-f326-11ea-8101-a7edf49fbb41.jpg)
![20200910_050746](https://user-images.githubusercontent.com/71043330/92657162-e8e74980-f326-11ea-8fa7-ef4be68bb580.jpg)

i tried to connect the gulikit controller via bluetooth and while my switch gave a "paired" notif, the controller itself doesnt show up on the "change grip" window. i also, tried connecting it wired and it properly connected so i doubt, the problem is on the controller.

note: i paired 4 controllers so far (2 of which are ds4, 1 gulikit controller and another of unknown brand)
since, the btdb shows 5 procon, i think the gulikit mightve paired twice after trying to connect via bluetooth and wired

**Comment by parkerlreed** [comment]
That's already a Switch controller, no? Why would you need Mission Control for that?

**Comment by ndeadly** [comment]
@parkerlreed there's currently an issue with identifying 3rd party pro controllers. I use hardware ID's reported by the controllers to identify them to determine how to deal with them. I've whitelisted all the official controllers, but I don't have the IDs of the 3rd party ones. Many of them don't even use unique identifiers (`0000:0000` is not uncommon). 
With other switch controllers I can fall back to checking the controller name if I can't match the ID, but the Pro Controller is a special case, because I have to rename non-switch controllers to look like Pro Controllers in order for the switch to accept them. This creates a situation where there is no way to tell the difference between a Pro Controller with an unidentified hardware ID, and some other random bluetooth controller. I choose to ignore any controller I can't identify.

@DrAllen694 I have a solution to the problem described above, but I'm running into some technical issues on older firmwares preventing me from adding it to the upcoming release. Not sure when I'll be able to integrate it into the rest of the codebase. If you're feeling impatient, let me know and I'll make you a custom build to support your controller in the meantime.

**Comment by parkerlreed** [comment]
Ahh thanks. Was not aware.

**Comment by DrAllen694** [comment]
no need bro. i dont mind the wait since i still havent got the need to use that many controllers yet anyways. just taking it in consideration is enough for me.

good luck with the future releases and hopefully it starts working on 14.2 atmos soon

**Comment by ndeadly** [comment]
So things worked out in the end and I just released a new version with the changes I described above. Your controller should work now.
