### ISSUE TITLE
[Feature Request]: Utilizing dualsense's haptic feedback to offer a faithful experience.

### ISSUE THREAD

**Issue by BENEMERITO** [ndeadly/MissionControl#610]
### Feature Description

I could not find any mention of the dualsense's haptic feedpack funtionality in this repository.  I make this question in order to know if it is feasible for mission control to match the haptic feedback you can get from a pro controller on a dualsense since, as it is, the dualsense seems to behave more like a traditional controller when it comes to the rumble function. As a final comment, I find the dualshock 3's rumble performance more akin to how the joy-con feels. I send my regards and I apologize in advance for any inconvenience these words may have caused.

### Rationale

The purpose of this inquiry is to know in advance what users can realistically expect from this project.

### Additional Details

Unfortunately, I lack any skill necesary to help answer my doubts, but I'm confident the author of this project already knows the answer I seek.

**Comment by ndeadly** [comment]
Currently it's not really feasible to support Dualsense haptics. The only public method for doing so uses Bluetooth audio to send the data to the controller. While we now have Bluetooth audio support on the console now since 13.0.0, it's pretty heavily bandwidth constrained, and it's just not really practical to convert Rumble instructions into an audio stream and then reroute that to a device that the system sees only as an HID gamepad.

The Sony dev that added official support for Dualsense controllers to the Linux kernel has suggested that it's also possible to send haptics data to the controller via HID reports, but there is no other public information regarding this. If this ever becomes known then it should be possible to faithfully recreate HD rumble on the Dualsense. Only time will tell.

In the future, please use the discussions tab for these kind of inquiries.
