### ISSUE TITLE
[Controller Request]: Generic USB Joystick

### ISSUE THREAD

**Issue by JoneHermer** [ndeadly/MissionControl#613]
### Controller Name

Generic USB Joystick

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [X] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

### Additional Details

This controller is using USB cable and it only support PC only.

**Comment by ndeadly** [comment]
Mission Control doesn't currently support USB controllers. Additionally, there is no such thing as a "generic" controller. I know you probably mean some unknown brand or even unbranded controller from somewhere like aliexpress, but even these have a vendor and product id, and unique data format that must be known in order to support them.
