### ISSUE TITLE
[Bug Report]: Yellow Cons

### ISSUE THREAD

**Issue by BurAndBY** [ndeadly/MissionControl#621]
### Switch Firmware Version

15.0.1

### Atmosphère Version

1.5.2 (Latest)

### Mission Control Version

0.9.2 (Latest)

### Boot Method

Fusée

### Issue Description

Any controller connected (even official Joy-Cons) are yellow.

### Error Report

Not crashing

### Additional Context

Mission control from hb appstore
Atmos from github

**Comment by ndeadly** [comment]
Heh. This isn't a bug, but an [easter egg](https://github.com/ndeadly/MissionControl/commit/bb805477f66dbe8cee74b48b41555a9cb115f078) intended for our Russian friends. Unfortunately it's not possible to exclude other Russian-speaking nations from the fun due to Nintendo's limited locale options.

You can contact me on discord for a clean version, or remove the changes and build one for yourself.

**Comment by impeeza** [comment]
wow, cool feature, not able to reproduce on my console.  regards.

**Comment by ndeadly** [comment]
> wow, cool feature, not able to reproduce on my console. regards.

Depends on your system language. There are also AIO packs out there distributing copies compiled with the changes removed if you don't obtain releases from github
