### ISSUE TITLE
[Bug Report]: Controller disconnects since last update

### ISSUE THREAD

**Issue by Alvarii5** [ndeadly/MissionControl#648]
### Switch Firmware Version

16.0.2 (Latest)

### Atmosphère Version

1.5.2 (Latest)

### Mission Control Version

0.9.2 (Latest)

### Boot Method

Hekate

### Issue Description

Hi, 
I have a TL-GP01 which was running good until I updated firmware to play TOTK so I had to uptade to 0.9.2 too (was running good on 0.8.0). At this moment the controller disconnects after one or two minutes of connection, but, after some tries of connecting, it works perfectly. The problem is that it takes like 20 minutes til I can make it works. Also had problems with the RT trigger that sometimes doesnt works. What could be happening?
Thanks in advance.

**Comment by ndeadly** [comment]
Not really sure about that one. This is not a controller I have heard of or officially support. The fact that it works at all means it must share the same vendor/product ID as something else.

> At this moment the controller disconnects after one or two minutes of connection, but, after some tries of connecting, it works perfectly. The problem is that it takes like 20 minutes til I can make it works

The only potential problems I know about would cause consistent failure. You wouldn't be able to make it work perfectly no matter how many tries. Maybe you have some intermittent RF interference where you are or something? Could also be worth checking whether you have the atmosphere setting for USB3 enabled. This is known to cause problems with wireless.

> Also had problems with the RT trigger that sometimes doesnt works

This sounds like a hardware issue to me. Input mapping is all or nothing. All inputs are all sent together. It's impossible for some to work and others not. Alternately, this could be due to this controller not having exactly the same input layout to the controller that the Switch thinks is connected.

**Comment by Alvarii5** [comment]
Switched off USB3 in /atmosphere/config/system_settings.ini and still the same. The weird is that it was working fine on 0.8.0. How can I generate a log file or report?
P.S. Dont worry about the trigger, I dont care so much.

**Comment by ndeadly** [comment]
> How can I generate a log file or report?

You can use [this build](https://github.com/ndeadly/MissionControl/files/11429143/MissionControl-0.9.2-debug-logging-ff1ffb3.zip) to make a log. It's not capable of logging much, because a lot of the connection stuff happens inside the layers of the Bluetooth stack, but it may give some clues. Logs are stored in `sdmc:/mc-mitm.log`
