### ISSUE TITLE
[Controller Request]: PowerA - Wireless Controller for Nintendo Switch - Mario Joy

### ISSUE THREAD

**Issue by jruby2023** [ndeadly/MissionControl#664]
### Controller Name

PowerA - Wireless Controller for Nintendo Switch - Mario Joy

### Current Controller Behaviour

Controller successfully pairs with the console but doesn't respond to inputs

### Controller vendor and product ID

0000:0000

### Supported Features

- [ ] Rumble/Vibration
- [ ] Motion Controls
- [X] Player Number Indicator
- [ ] Battery Level Reporting

### Additional Details

Bluetooth device shows up in btdb as: 30:31:7d:a0:c8:6e 0000:0000 Lic2 Pro Controller

**Comment by ndeadly** [comment]
It turns out `Lic2 Pro Controller` is a new official device name string [introduced in firmware 15.0.0](https://yls8.mtheall.com/ninupdates/sysupdatedl/autodl_sysupdates/2022-10-11_00-15-06-hac/0100000000000818/ALL/v1006634080/settings_parseout.diff.info). I've added it to the list of official device names, so this should allow newer PowerA and other 3rd party licensed controllers to be detected correctly.

[MissionControl-0.9.2-develop-2612b88.zip](https://github.com/ndeadly/MissionControl/files/11786534/MissionControl-0.9.2-develop-2612b88.zip)

**Comment by jruby2023** [comment]
That did the trick. I just tested it on Firmware 14.1.2 and it worked perfectly. I have a Firmware 16.0.3 Switch I can test it on, also, if you need anything from that one. Really appreciate your work on this!

**Comment by jruby2023** [comment]
![2023061906232300-DB1426D1DFD034027CECDE9C2DD914B8](https://github.com/ndeadly/MissionControl/assets/136861139/726f9996-3def-417d-983c-6f0fb3c6903c)

**Comment by ndeadly** [comment]
> That did the trick. I just tested it on Firmware 14.1.2 and it worked perfectly. I have a Firmware 16.0.3 Switch I can test it on, also, if you need anything from that one. Really appreciate your work on this!

That's fine, if it works on one it will work across all firmwares.
