### ISSUE TITLE
[Feature Request]: Input lag

### ISSUE THREAD

**Issue by itsDarkEye** [ndeadly/MissionControl#666]
### Feature Description

I've noticed that there's a lot of input lag when playing with a controller (in my case dualshock 5) and this makes it quite unplayable for competitive level gaming (eg: splatoon 3)

### Rationale

Less input lag, less mad

### Additional Details

I know this emulation stuff is optimized to work on a janky console like the switch but I hope that it can be perfected even more by reducing input delay between the controller and the switch.

**Comment by ndeadly** [comment]
> [Feature Request]: Input lag

I don't think you want input lag as a feature...

> I know this emulation stuff is optimized to work on a janky console like the switch but I hope that it can be perfected even more by reducing input delay between the controller and the switch.

While technically there is going to be some additional input lag introduced due to the extra processing Mission Control must do to convert the input data format etc. I have my doubts that one would actually be able to perceive the difference. 

What is _more_ likely, in my experience, is that the lag is introduced by one or more of the following:
- Devices generating local RF interference. Wifi routers, refridgerators, AC units or other nearby electrical devices are the usual suspects
- USB3.0 support enabled in atmosphere's settings file (`/atmosphere/config/system_settings.ini`). This is known to create internal noise that interferes with wireless comms.
- Other controllers are connected at the same time that don't support a command the console sends to manage bandwidth usage. This includes Xbox controllers and other 3rd party Bluetooth controllers. While the offending controllers themselves might not be affected, they can broadcast over the top of others and cause packets to be dropped or delayed.
- Many other controllers connected simultaneously. It's possible that too many controllers connected to the console at once can saturate either the Bluetooth link, or the CPU core doing the processing, leading to delays.
- Other homebrew or system software hogging the CPU core that Mission Control is running on.

Try to eliminate possible causes listed above and see if you notice any difference. Disable other homebrew, don't connect other controllers via Bluetooth, and try playing in a different room. External interference aside, there's not a lot I can do to make it faster than it currently is. That's the nature of doing this in software and having to share the limited resources with the rest of the system.

**Comment by itsDarkEye** [comment]
Alright thanks for the list. Though, I've read something about USB 3. Can I connect my controller wired to the dock, would that work or it's not a feature yet?

**Comment by Mohsemm** [comment]
I hope you can try and add wired controller support because that would really change how third party controllers are used with the switch
