### ISSUE TITLE
[Bug Report]: wii u pro controller

### ISSUE THREAD

**Issue by ManualJoystick** [ndeadly/MissionControl#696]
### Switch Firmware Version

16.1.0 (Latest)

### Atmosphère Version

1.5.5 (Latest)

### Mission Control Version

0.9.3 (Latest)

### Boot Method

Hekate

### Issue Description

Whenever I trying to connect the wii u pro controller the console freezes but everything else like my ps4 controller does

**Comment by ndeadly** [comment]
This has been reported a couple of times on my discord server, and appears to be something to do with my Bluetooth patches that slipped through the cracks during my testing. Strange because I tested with both a DS4 and WiiU controller without issue.

I'm not sure how much time I will have have to look into it over the weekend, but as a workaround for now you can delete the `btm_patches` and `bluetooth_patches` directories inside of `/atmosphere/exefs_patches`. This will stop Wii/WiiU and Xbox Elite 2 controllers from pairing, but should eliminate the freezes.

**Comment by ManualJoystick** [comment]
> 

Alright thanks information I'll stay up to date

**Comment by ndeadly** [comment]
@ManualJoystick this should be working now

[MissionControl-0.9.3-develop-913c89b.zip](https://github.com/ndeadly/MissionControl/files/12451454/MissionControl-0.9.3-develop-913c89b.zip)
