### ISSUE TITLE
8bitdo SN30 pro plus support Xinput/dinput

### ISSUE THREAD

**Issue by retromanMx** [ndeadly/MissionControl#71]
I know that there is already support for switch in this controller. However, currently there is a issue with phantom inputs on the analog stick that cannot be solved with 8bitdo software for switch. Xinput and dinput work correctly.

**Comment by ndeadly** [comment]
This has already been discussed in #10 . The controller should already connect in Xinput mode and will be detected as an Xbox One controller but uses the old button mapping that' I don't support. @evertonstz has stated that there's an issue with a large outer deadzone in switch mode on those controllers, but it also seems to be the case in Xinput mode on the switch too for some reason.

**Comment by evertonstz** [comment]
Hey @retromanMx I've heard about this problem before, as @ndeadly said these bugs that seem to happen on the Switch Mode only aren't actually on Switch Mode only, but it only happens in the Switch, take a look at issue 10 and it'll be clear.

Now about your problem, I heard the way to solve it is by downgrading the FW to something around 3.01, as it seems this bug was introduced at 3.02. What I would suggest is: test all the FW starting by the newest one and go downgrading from there until you see the problem is gone.
