### ISSUE TITLE
[Bug Report]: Switch freezes when connecting Wii Remote

### ISSUE THREAD

**Issue by I2000C** [ndeadly/MissionControl#725]
### Switch Firmware Version

16.1.0 (Latest)

### Atmosphère Version

1.5.5 (Latest)

### Mission Control Version

0.9.4 (Latest)

### Boot Method

Fusée

### Issue Description

When I try to connect a Wii controller to the switch in the latest version of Mission Control (0.9.4), Atmosphere (1.5.5) and Firmware (16.1.0), the switch freezes and I have to shutdown it by pressing the POWER button 10 seconds.

Steps to reproduce the issue:
1- Select "Controllers" on the HOME Menu.
2- Select "Change Grip/Order"
3- Press the "sync" button of a Wii controller that wasn't previously synced with the Nintendo Switch (I haven't tested with already synced Wii controllers).
4- The switch stops responding and freezes

What could be causing that issue?

**Comment by ndeadly** [comment]
Are you absolutely sure you're running 0.9.4? Freezing when pairing new controllers was a bug in 0.9.3 that 0.9.4 was released to fix a few days later. Since the issue was with the bluetooth exefs patches, this could also occur if you installed 0.9.4 but didn't overwrite the patches properly. Re-download the latest release and install it again. I'm fairly sure your issue will go away.

**Comment by I2000C** [comment]
Sorry, I was using the previous version of Mission Control. Now, Wii controllers are working again.
Thanks
