### ISSUE TITLE
[Bug Report]: Wrong button mapping for 8BitDo SN30 Pro Xbox Cloud Gaming Edition

### ISSUE THREAD

**Issue by chrisipa** [ndeadly/MissionControl#744]
### Switch Firmware Version

16.1.0

### Atmosphère Version

1.5.5

### Mission Control Version

0.9.4

### Boot Method

Fusée

### Issue Description

Hi @ndeadly, 

first of all thank you and the other contributors so much for your fantastic work on this project. It's really great what you have achieved so far.

When testing mission control with my **8BitDo SN30 Pro Xbox Cloud Gaming Edition** I noticed, that the **button mapping for ZL and ZR is switched** with each other.

This is especially painful when playing racing games because the brake and acceleration buttons are mixed up with each other.

Can you please fix this behaviour? Thank you very much.

PS: The rest of the buttons seem to be mapped correctly.

Best regards
Chris

**Comment by ndeadly** [comment]
Thanks, @chrisipa!

You are indeed correct. Seems I had the left and right _analog_ values for the triggers the wrong way around (see https://github.com/ndeadly/MissionControl/issues/442#issuecomment-1116367255). A few months back I switched to using the analog trigger values for all controllers (where available) instead of the digital ones, to allow people to set their own activation levels. The digital values are correct, however, which is why this wasn't picked up during initial testing.

[MissionControl-0.10.0-develop-958616c.zip](https://github.com/ndeadly/MissionControl/files/13236223/MissionControl-0.10.0-develop-958616c.zip)

**Comment by chrisipa** [comment]
Wow I'm really impressed. Your dev build  has fixed the issue.

Thank you very much.

Looking forward to the new release.
