### ISSUE TITLE
[Feature Request]: xbox one controller trigger sensitivity 

### ISSUE THREAD

**Issue by v18281** [ndeadly/MissionControl#755]
### Feature Description

In a previous version of Mission Control(I forgot which version) the xbox one controller triggers were more sensitive, but now at version 0.10.0 it requires significantly more travel for the triggers to register. Can you make it as sensitive as before? Thanks.

### Rationale

In a previous version of Mission Control(I forgot which version) the xbox one controller triggers were more sensitive, but now at version 0.10.0 it requires significantly more travel for the triggers to register. Can you make it as sensitive as before? Thanks.

**Comment by ndeadly** [comment]
This is because the activation threshold was made configurable for all controllers with analog triggers, with a default value now set to 50%.

Refer to the `analog_trigger_activation_threshold ` option under the module configuration [instructions](https://github.com/ndeadly/MissionControl#module-configuration). Setting this value to 0 will restore the previous sensitivity.

**Comment by v18281** [comment]
Thanks. I love you.
