### ISSUE TITLE
[Feature Request]: When the Bluetooth Audio is open，the MissonControl will make a high input lag

### ISSUE THREAD

**Issue by CBCBA** [ndeadly/MissionControl#777]
### Feature Description

But if the Bluetooth Audio is closed，the MissonControl is back to normal

### Rationale

Could you optimize this problem？

**Comment by ndeadly** [comment]
Bluetooth bandwidth in general is rather limited on the switch. Even with official controllers one can expect an increase in lag when Bluetooth audio is active, especially when more than one controller is connected.

There is nothing to be optimised in the software, this is purely a hardware limitation. Some controllers connected via mission control may make performance worse than official controllers due to either sending data at a higher rate. Controllers that don't use Broadcom Bluetooth chips (eg many cheap generic or clone controllers) can also cause problems due to the console not being able to configure them for sharing the available bandwidth effectively.

In general, I would not really recommend using Bluetooth audio outside of handheld mode, with or without mission control.

**Comment by CBCBA** [comment]
Thank you for your patient answer
