### ISSUE TITLE
[Bug Report]: 0.11.0 fails to boot on firmware 17

### ISSUE THREAD

**Issue by kuba-orlik** [ndeadly/MissionControl#798]
### Switch Firmware Version

17.0.1

### Atmosphère Version

1.6.2

### Mission Control Version

0.11.0 (Latest)

### Boot Method

Hekate

### Issue Description

Mission Control 0.11.0 fails booting on firmware 17.0. Versoin 0.10.0 works fine 

### Error Report

[report_0b00be46.zip](https://github.com/ndeadly/MissionControl/files/14822429/report_0b00be46.zip)

**Comment by ndeadly** [comment]
I think you just need to update your Atmosphere to latest

**Comment by kuba-orlik** [comment]
You mean the 1.7.0 pre-release?

**Comment by ndeadly** [comment]
Yeah, that's the one

**Comment by JimZiii** [comment]
Same, doesn't work on 1.6.2

**Comment by ndeadly** [comment]
You need to update to 1.7.0

**Comment by JimZiii** [comment]
1.7.0 is still pre-release, I'd rather wait for a full release.
I get that updating will fix it, just thought the dev might wanna fix the app instead of leaving it broken on older versions and expecting everyone to update. There's plenty of ppl using older firmware and atmosphere versions, especially during the pre-release period.

Should be easy to fix, if i knew how to code i would have contributed it myself

**Comment by ndeadly** [comment]
It's not a bug to be fixed, it's a requirement enforced by the atmosphere libraries that mission control depends upon.

If you're unwilling to update atmosphere that's fine, but then you don't need the mission control update either.
