### ISSUE TITLE
Xbox series elite 2[Controller Request]: 

### ISSUE THREAD

**Issue by THEKINGFIGTHER** [ndeadly/MissionControl#804]
### Controller Name

Xbox series elite 2

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [ ] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

**Comment by ndeadly** [comment]
This controller is already supported. If you can't connect it then one of these things is likely true:
- you have the updated Bluetooth LE firmware and need to downgrade to a legacy version
- you have a newer XBE2 model that shipped with the Bluetooth LE firmware and _cannot_ be downgraded
- you haven't installed Mission Control correctly and are missing the binary patches that specifically enable this controller
- you haven't correctly followed the procedure for either installing Mission Control or pairing controllers

**Comment by THEKINGFIGTHER** [comment]
Excuse me, could you show me how to install the binary files for mission
control since I searched and no one has used that control on the Nintendo
switch

**Comment by THEKINGFIGTHER** [comment]
Thanks, I'll check it out! , Another question, are not all control motors
compatible? I mean, only some of them work

**Comment by ndeadly** [comment]
The issue tracker is not really the place for questions. In the future, direct questions to the discussions page, or discord.

Vibration motor support is only really implemented for major console console controllers, because they tend to be well understood and documented. Support for arbitrary controllers is possible, but people don't often provide me with the information to implement it. Output packets can't simply be observed on the console like we can for input data. One needs to make a packet capture of the vibration working on PC, or grab an HID descriptor in order to know the layout of the output data.

**Comment by THEKINGFIGTHER** [comment]
Ok, thanks for the clarification.
