### ISSUE TITLE
[Feature Request]: Is there a way to raise the limit of 2 bluetooth controllers while using bluetooth audio?

### ISSUE THREAD

**Issue by D1yt** [ndeadly/MissionControl#808]
### Feature Description

Hello, I was looking for a way to bypass the "2 wireless controller limit" during the usage of the "new" bluetooth audio feature. Is there any possibility of this being implemented by software like MissionControl? If not, could somebody recommend a dongle for bluetooth audio?

### Rationale

Software-only way to bypass this limitation

**Comment by ndeadly** [comment]
It's probably technically possible to patch out the check, but the 2 controller limit is there for a reason. The console has pretty limited wireless bandwidth, and Bluetooth audio consumes a large amount of it. Even with a single controller connected there is noticeable input lag introduced when used in conjunction with an audio device. I'm sure they set the limit as high as 2 only because they need to support dual joycons in wireless mode. Anything more than this is going to border upon unplayable. I consider the built-in Bluetooth audio to only be useful for handheld mode, and suggest you look into USB dongles if you want to use it otherwise.
