### ISSUE TITLE
PS3 controller without USB cable 

### ISSUE THREAD

**Issue by momazossky** [ndeadly/MissionControl#815]
### Feature Description

We can connect the controller to the Nintendo without needing that annoying USB cable and without errors

### Rationale

my ps3 controller does not connect with the usb cable on the nintendo switch

**Comment by ndeadly** [comment]
The USB cable is required for pairing the controller. There is no way around this. That's how it works on PS3 too.

**Comment by Masamune3210** [comment]
To add to this, in case anyone was wondering if some smart programming wizardry is all that's needed, the issue is that the controller firmware itself will only accept new paring information through USB. Its simply a limitation of how Sony decided to make the controller work, the same issue presents itself even on PC
