### ISSUE TITLE
[Bug Report]: btdb crash

### ISSUE THREAD

**Issue by tinnnysu** [ndeadly/MissionControl#820]
### Switch Firmware Version

17.0.1

### Atmosphère Version

1.6.2

### Mission Control Version

0.10.0

### Boot Method

Fusée

### Issue Description

btdb crash
![2024-05-25 071712](https://github.com/ndeadly/MissionControl/assets/4081096/1e1e7f3c-7197-40cb-95b1-7a75c20fe302)

**Comment by ndeadly** [comment]
Since HOS 17.0.0, the `btm` service has had fewer free session handles available. This error occurs when an application tries to obtain a session handle when there are no more available.

There is no "simple" solution to this problem. I could also consider removing the features that rely upon the service, but that's not ideal. Ultimately, I might end up proxying the calls that require the `btm` service through the Mission Control sysmodule (it obtains a handle for its own purposes). The workaround for now is to disable the Mission Control sysmodule if you need to use the `btdb` application.
