### ISSUE TITLE
[Bug Report]: Super Mario Party crashes Atmosphere with Wii Remote/third party controller

### ISSUE THREAD

**Issue by CalMemer32** [ndeadly/MissionControl#835]
### Switch Firmware Version

18.0.1

### Atmosphère Version

1.7.1 (Latest)

### Mission Control Version

0.11.1 (Latest)

### Boot Method

Hekate

### Issue Description

When playing Super Mario Party, Attempting to connect any third party controller that supports MissionControl such as a Wii Remote, Crashes Atmosphere. You can replicate this on the initial controller screen when selecting the player count, this always happens with 3+ players but should happen with any amount.

### Error Report

![IMG_2678](https://github.com/ndeadly/MissionControl/assets/132810513/ad371c25-69c8-4563-83af-1f382dec4abb)

### Additional Context

Both Atmosphere and MissionControl were installed separately.

**Comment by ndeadly** [comment]
Does this only happen with Mario party? And/or at that screen? I can't think of any reasons for getting that kind of crash for a specific title only. Usually I see this if mission control can't read/write the virtual memory files for controllers in the /config/missioncontrol directory (due to corruption or archive bits)

Please share the error report from your SD card. The screen you shared only shows that it was mission control that crashed, it lacks any diagnostic information.

**Comment by CalMemer32** [comment]
N/A
