### ISSUE TITLE
[Bug Report]: No vibration on Xbox Series S controller

### ISSUE THREAD

**Issue by u4113057** [ndeadly/MissionControl#866]
### Switch Firmware Version

18.1.0 (Latest)

### Atmosphère Version

1.7.1 (Latest)

### Mission Control Version

0.11.1 (Latest)

### Boot Method

Fusée

### Issue Description

No vibration on Xbox Series S controller. In the list Xbox Series S is listed as compatible controller but i'm not sure is this normal that it is not vibrate in game.

**Comment by ndeadly** [comment]
> In the list Xbox Series S is listed as compatible controller

This is not true. It's explicitly listed as an exception, due to its use of Bluetooth LE.

The only way you could be using the controller wirelessly is if you've installed an experimental version originating from my discord server. Those are assumed to to be unstable, and you shouldn't be reporting issues here. 

In any case, it's not currently possible to support vibrations for BLE controllers due to a technical limitation.
