### ISSUE TITLE
[Bug Report]: 8bitdo usb wireless adapter 2 and stadia controller not working

### ISSUE THREAD

**Issue by lorenzocaputo18** [ndeadly/MissionControl#874]
### Switch Firmware Version

18.1.0

### Atmosphère Version

1.7.1

### Mission Control Version

0.11.1

### Boot Method

Hekate

### Issue Description

cannot use the stadia controller paired with 8bitdo usb wireless adapter 2. The controller is paired, the switch detects it but no buttons can be used

**Comment by ndeadly** [comment]
What makes you think mission control is responsible? Neither USB or Bluetooth LE (used by Stadia controllers) is supported in the release version. This sounds like a problem with the 8bitdo dongle, or you have something like sys-con installed which is taking control of the device.

**Comment by pixel2user** [comment]
Since the adapter doesn't need any special driver or config on the Switch, make sure everything is deactivated that changes the normal USB controller handling. Activate wired Pro controller support in Switch settings!

"Stadia controller works on Nintendo Switch with 8BitDo Bluetooth adapter" https://www.reddit.com/r/Stadia/comments/12uinbl/stadia_controller_works_on_nintendo_switch_with/
