### ISSUE TITLE
[Controller Request]: Razer Raiju Ultimate

### ISSUE THREAD

**Issue by GitMathHub** [ndeadly/MissionControl#881]
### Controller Name

Razer Raiju Ultimate RZ06-0260

### Current Controller Behaviour

Other (please specify below)

### Controller vendor and product ID

21532:1009

### Supported Features

- [X] Rumble/Vibration
- [X] Motion Controls
- [ ] Player Number Indicator
- [X] Battery Level Reporting

### Additional Details

Controller pairs successfully and controls seem to be correct. The controller blinks like when it is successfully paired. BUT after few seconds the controller disconnect and switch off.

**Comment by Alihedrn** [comment]
Hi. I hava same problem. My controller back switch button no different and i set on PS bt or usb or ‌PC bt، not do anything. When i connect it to pc with usb،just red light on and nothing else، and when i tried connect with bluetooth، just connected for 10 seconds and turned off، i cant upgrade or downgrade my controller because my device manager no action when i connect my controller(with usb). Help me pleass

**Comment by ndeadly** [comment]
If it doesn't work on PC then this is not a Mission Control issue. I can't help you with that, I don't even own this controller.
